/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Issue 4226 - property naming convention for zod schemas
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

export const GetWidgetParams = zod.object({
  widget_id: zod.string(),
});

export const GetWidgetQueryParams = zod.object({
  page_size: zod.int().optional(),
});

export const getWidgetResponsePagingOptionsDefault = { page_size: 20 as const };

export const GetWidgetResponse = zod
  .strictObject({
    widget_id: zod.string(),
    display_name: zod.string(),
    nested_data: zod
      .strictObject({
        inner_value: zod.number().optional(),
      })
      .transform(({ inner_value: innerValue, ...rest }) => ({
        ...rest,
        ...(innerValue !== undefined && { innerValue }),
      }))
      .optional(),
    tag_list: zod
      .array(
        zod
          .strictObject({
            tag_name: zod.string(),
          })
          .transform(({ tag_name: tagName, ...rest }) => ({
            ...rest,
            tagName,
          })),
      )
      .optional(),
    paging_options: zod
      .strictObject({
        page_size: zod.int().optional(),
      })
      .transform(({ page_size: pageSize, ...rest }) => ({
        ...rest,
        ...(pageSize !== undefined && { pageSize }),
      }))
      .prefault(getWidgetResponsePagingOptionsDefault),
    Class: zod.string().optional(),
  })
  .transform(
    ({
      widget_id: widgetId,
      display_name: displayName,
      nested_data: nestedData,
      tag_list: tagList,
      paging_options: pagingOptions,
      Class: _5,
      ...rest
    }) => ({
      ...rest,
      widgetId,
      displayName,
      ...(nestedData !== undefined && { nestedData }),
      ...(tagList !== undefined && { tagList }),
      ...(pagingOptions !== undefined && { pagingOptions }),
      ...(_5 !== undefined && { class: _5 }),
    }),
  );

export const UpdateWidgetParams = zod.object({
  widget_id: zod.string(),
});

export const updateWidgetBodyOnePagingOptionsDefault = {
  page_size: 20 as const,
};

export const UpdateWidgetBody = zod
  .strictObject({
    widget_id: zod.string(),
    display_name: zod.string(),
    nested_data: zod
      .strictObject({
        inner_value: zod.number().optional(),
      })
      .transform(({ inner_value: innerValue, ...rest }) => ({
        ...rest,
        ...(innerValue !== undefined && { innerValue }),
      }))
      .optional(),
    tag_list: zod
      .array(
        zod
          .strictObject({
            tag_name: zod.string(),
          })
          .transform(({ tag_name: tagName, ...rest }) => ({
            ...rest,
            tagName,
          })),
      )
      .optional(),
    paging_options: zod
      .strictObject({
        page_size: zod.int().optional(),
      })
      .transform(({ page_size: pageSize, ...rest }) => ({
        ...rest,
        ...(pageSize !== undefined && { pageSize }),
      }))
      .prefault(updateWidgetBodyOnePagingOptionsDefault),
    Class: zod.string().optional(),
    owner_id: zod.string(),
  })
  .transform(
    ({
      widget_id: widgetId,
      display_name: displayName,
      nested_data: nestedData,
      tag_list: tagList,
      paging_options: pagingOptions,
      Class: _5,
      owner_id: ownerId,
      ...rest
    }) => ({
      ...rest,
      widgetId,
      displayName,
      ...(nestedData !== undefined && { nestedData }),
      ...(tagList !== undefined && { tagList }),
      ...(pagingOptions !== undefined && { pagingOptions }),
      ...(_5 !== undefined && { class: _5 }),
      ownerId,
    }),
  );

export const updateWidgetResponseOnePagingOptionsDefault = {
  page_size: 20 as const,
};

export const UpdateWidgetResponse = zod
  .strictObject({
    widget_id: zod.string(),
    display_name: zod.string(),
    nested_data: zod
      .strictObject({
        inner_value: zod.number().optional(),
      })
      .transform(({ inner_value: innerValue, ...rest }) => ({
        ...rest,
        ...(innerValue !== undefined && { innerValue }),
      }))
      .optional(),
    tag_list: zod
      .array(
        zod
          .strictObject({
            tag_name: zod.string(),
          })
          .transform(({ tag_name: tagName, ...rest }) => ({
            ...rest,
            tagName,
          })),
      )
      .optional(),
    paging_options: zod
      .strictObject({
        page_size: zod.int().optional(),
      })
      .transform(({ page_size: pageSize, ...rest }) => ({
        ...rest,
        ...(pageSize !== undefined && { pageSize }),
      }))
      .prefault(updateWidgetResponseOnePagingOptionsDefault),
    Class: zod.string().optional(),
    owner_id: zod.string(),
  })
  .transform(
    ({
      widget_id: widgetId,
      display_name: displayName,
      nested_data: nestedData,
      tag_list: tagList,
      paging_options: pagingOptions,
      Class: _5,
      owner_id: ownerId,
      ...rest
    }) => ({
      ...rest,
      widgetId,
      displayName,
      ...(nestedData !== undefined && { nestedData }),
      ...(tagList !== undefined && { tagList }),
      ...(pagingOptions !== undefined && { pagingOptions }),
      ...(_5 !== undefined && { class: _5 }),
      ownerId,
    }),
  );

export const GetShapesResponseItem = zod.discriminatedUnion('shape_type', [
  zod
    .strictObject({
      shape_type: zod.enum(['circle']),
      radius_px: zod.number(),
    })
    .transform(({ shape_type: shapeType, radius_px: radiusPx, ...rest }) => ({
      ...rest,
      shapeType,
      radiusPx,
    })),
  zod
    .strictObject({
      shape_type: zod.enum(['square']),
      side_length: zod.number(),
    })
    .transform(
      ({ shape_type: shapeType, side_length: sideLength, ...rest }) => ({
        ...rest,
        shapeType,
        sideLength,
      }),
    ),
]);
export const GetShapesResponse = zod.array(GetShapesResponseItem);

export const GetCollisionResponse = zod
  .strictObject({
    first_name: zod.string().optional(),
    firstName: zod.string().optional(),
    'special-value': zod.string().optional(),
    already_camel: zod.string().optional(),
  })
  .transform(
    ({
      'special-value': specialValue,
      already_camel: alreadyCamel,
      ...rest
    }) => ({
      ...rest,
      ...(specialValue !== undefined && { specialValue }),
      ...(alreadyCamel !== undefined && { alreadyCamel }),
    }),
  );
