/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Recursive discriminator with allOf base
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

import type { Derived1, Derived2 } from './model';

export const getDerived1 = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Derived1>> => {
  return axios.get(`/derived1`, options);
};

export const getDerived2 = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Derived2>> => {
  return axios.get(`/derived2`, options);
};

export type GetDerived1Result = AxiosResponse<Derived1>;
export type GetDerived2Result = AxiosResponse<Derived2>;
