/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Angular httpResource both regression
 * OpenAPI spec version: 1.0.0
 */

export * from './createPetsBody';
export * from './error';
export * from './pet';
export * from './pets';
export * from './searchPetsBody';
export * from './searchPetsBodyStatus';
