/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Issue 2465 - override.mock.properties inside arrays
 * OpenAPI spec version: 1.0.0
 */
import type { BaseUser } from './baseUser';

/**
 * User object as it shall be retrieved
 */
export type RetrievedUser = BaseUser & {
  id: string;
};
