/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Date Type Test
 * OpenAPI spec version: 1.0.0
 */
import type { EventStatus } from './eventStatus';
import type { Dayjs } from 'dayjs';

export interface Event {
  id: string;
  name: string;
  startsAt: Dayjs;
  date: Temporal.PlainDate;
  status?: EventStatus;
}
