/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * MSW array item factories - unexported top-level array item aliases
 * OpenAPI spec version: 1.0.0
 */
import type {
  CatalogItems,
  GetCatalogItemsInline200Item,
  GetNullableCatalogItems200Item,
  GetNullableList200,
  Items,
} from './model';

import { faker } from '@faker-js/faker';

import { HttpResponse, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import type {
  CatalogItemsItem,
  GetNullableList200RowsItem,
  ItemsItem,
} from './model';

export type getCatalogItemsResponse200 = {
  data: CatalogItems;
  status: 200;
};

export type getCatalogItemsResponseSuccess = getCatalogItemsResponse200 & {
  headers: Headers;
};
export type getCatalogItemsResponse = getCatalogItemsResponseSuccess;

export const getGetCatalogItemsUrl = () => {
  return `/catalog-items`;
};

export const getCatalogItems = async (
  options?: RequestInit,
): Promise<getCatalogItemsResponse> => {
  const res = await fetch(getGetCatalogItemsUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getCatalogItemsResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getCatalogItemsResponse;
};

export type getCatalogItemsInlineResponse200 = {
  data: GetCatalogItemsInline200Item[];
  status: 200;
};

export type getCatalogItemsInlineResponseSuccess =
  getCatalogItemsInlineResponse200 & {
    headers: Headers;
  };
export type getCatalogItemsInlineResponse =
  getCatalogItemsInlineResponseSuccess;

export const getGetCatalogItemsInlineUrl = () => {
  return `/catalog-items-inline`;
};

export const getCatalogItemsInline = async (
  options?: RequestInit,
): Promise<getCatalogItemsInlineResponse> => {
  const res = await fetch(getGetCatalogItemsInlineUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getCatalogItemsInlineResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getCatalogItemsInlineResponse;
};

export type getCatalogItemsShortResponse200 = {
  data: Items;
  status: 200;
};

export type getCatalogItemsShortResponseSuccess =
  getCatalogItemsShortResponse200 & {
    headers: Headers;
  };
export type getCatalogItemsShortResponse = getCatalogItemsShortResponseSuccess;

export const getGetCatalogItemsShortUrl = () => {
  return `/items`;
};

export const getCatalogItemsShort = async (
  options?: RequestInit,
): Promise<getCatalogItemsShortResponse> => {
  const res = await fetch(getGetCatalogItemsShortUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getCatalogItemsShortResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getCatalogItemsShortResponse;
};

export type getNullableListResponse200 = {
  data: GetNullableList200;
  status: 200;
};

export type getNullableListResponseSuccess = getNullableListResponse200 & {
  headers: Headers;
};
export type getNullableListResponse = getNullableListResponseSuccess;

export const getGetNullableListUrl = () => {
  return `/nullable-list`;
};

export const getNullableList = async (
  options?: RequestInit,
): Promise<getNullableListResponse> => {
  const res = await fetch(getGetNullableListUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getNullableListResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getNullableListResponse;
};

export type getNullableCatalogItemsResponse200 = {
  data: GetNullableCatalogItems200Item[] | null;
  status: 200;
};

export type getNullableCatalogItemsResponseSuccess =
  getNullableCatalogItemsResponse200 & {
    headers: Headers;
  };
export type getNullableCatalogItemsResponse =
  getNullableCatalogItemsResponseSuccess;

export const getGetNullableCatalogItemsUrl = () => {
  return `/nullable-catalog-items`;
};

export const getNullableCatalogItems = async (
  options?: RequestInit,
): Promise<getNullableCatalogItemsResponse> => {
  const res = await fetch(getGetNullableCatalogItemsUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getNullableCatalogItemsResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getNullableCatalogItemsResponse;
};

export type KeysWithNull<O> = {
  [K in keyof O]-?: null extends O[K] ? K : never;
}[keyof O];

export type MockWithNullableOverrides<
  T,
  O extends Partial<T>,
  M extends Record<keyof T, unknown>,
> = Omit<M, Extract<KeysWithNull<O>, keyof T>> & {
  [K in Extract<KeysWithNull<O>, keyof T>]: M[K] | null;
};

export type CatalogItemsMock = CatalogItems;

export type CatalogItemsItemMock = {
  [K in keyof Required<NonNullable<CatalogItemsItem>>]: NonNullable<
    Required<NonNullable<CatalogItemsItem>>[K]
  >;
};

export type GetCatalogItemsInline200ItemMock = {
  [K in keyof Required<NonNullable<GetCatalogItemsInline200Item>>]: NonNullable<
    Required<NonNullable<GetCatalogItemsInline200Item>>[K]
  >;
};

export type ItemsMock = Items;

export type ItemsItemMock = {
  [K in keyof Required<NonNullable<ItemsItem>>]: NonNullable<
    Required<NonNullable<ItemsItem>>[K]
  >;
};

export type GetNullableList200Mock = {
  [K in keyof Required<NonNullable<GetNullableList200>>]: NonNullable<
    Required<NonNullable<GetNullableList200>>[K]
  >;
};

export type GetNullableList200RowsItemMock = {
  [K in keyof Required<NonNullable<GetNullableList200RowsItem>>]: NonNullable<
    Required<NonNullable<GetNullableList200RowsItem>>[K]
  >;
};

export type GetNullableCatalogItems200ItemMock = GetNullableCatalogItems200Item;

export const getGetCatalogItemsResponseCatalogItemsItemMock = <
  O extends Partial<CatalogItemsItem> = {},
>(
  overrideResponse?: O,
): MockWithNullableOverrides<CatalogItemsItem, O, CatalogItemsItemMock> =>
  ({
    ...{
      sku: faker.string.alpha({ length: { min: 10, max: 20 } }),
      price: faker.number.float({ fractionDigits: 2 }),
    },
    ...overrideResponse,
  }) as MockWithNullableOverrides<CatalogItemsItem, O, CatalogItemsItemMock>;

export const getGetCatalogItemsResponseMock = (): CatalogItemsMock =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    ...(getGetCatalogItemsResponseCatalogItemsItemMock() as CatalogItemsItemMock),
  }));

export const getGetCatalogItemsInlineResponseGetCatalogItemsInline200ItemItemMock =
  <O extends Partial<GetCatalogItemsInline200Item> = {}>(
    overrideResponse?: O,
  ): MockWithNullableOverrides<
    GetCatalogItemsInline200Item,
    O,
    GetCatalogItemsInline200ItemMock
  > =>
    ({
      ...{
        id: faker.string.alpha({ length: { min: 10, max: 20 } }),
        label: faker.string.alpha({ length: { min: 10, max: 20 } }),
      },
      ...overrideResponse,
    }) as MockWithNullableOverrides<
      GetCatalogItemsInline200Item,
      O,
      GetCatalogItemsInline200ItemMock
    >;

export const getGetCatalogItemsInlineResponseMock =
  (): GetCatalogItemsInline200ItemMock[] =>
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      ...(getGetCatalogItemsInlineResponseGetCatalogItemsInline200ItemItemMock() as GetCatalogItemsInline200ItemMock),
    }));

export const getGetCatalogItemsShortResponseItemsItemMock = <
  O extends Partial<ItemsItem> = {},
>(
  overrideResponse?: O,
): MockWithNullableOverrides<ItemsItem, O, ItemsItemMock> =>
  ({
    ...{ id: faker.string.alpha({ length: { min: 10, max: 20 } }) },
    ...overrideResponse,
  }) as MockWithNullableOverrides<ItemsItem, O, ItemsItemMock>;

export const getGetCatalogItemsShortResponseMock = (): ItemsMock =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    ...(getGetCatalogItemsShortResponseItemsItemMock() as ItemsItemMock),
  }));

export const getGetNullableListResponseRowsItemMock = <
  O extends Partial<GetNullableList200RowsItem> = {},
>(
  overrideResponse?: O,
): MockWithNullableOverrides<
  GetNullableList200RowsItem,
  O,
  GetNullableList200RowsItemMock
> =>
  ({
    ...{ id: faker.string.alpha({ length: { min: 10, max: 20 } }) },
    ...overrideResponse,
  }) as MockWithNullableOverrides<
    GetNullableList200RowsItem,
    O,
    GetNullableList200RowsItemMock
  >;

export const getGetNullableListResponseMock = <
  O extends Partial<Extract<GetNullableList200, object>> = {},
>(
  overrideResponse?: O,
): MockWithNullableOverrides<GetNullableList200, O, GetNullableList200Mock> =>
  ({
    rows: Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => ({
      ...(getGetNullableListResponseRowsItemMock() as GetNullableList200RowsItemMock),
    })),
    ...overrideResponse,
  }) as MockWithNullableOverrides<
    GetNullableList200,
    O,
    GetNullableList200Mock
  >;

export const getGetNullableCatalogItemsResponseGetNullableCatalogItems200ItemNullItemMock =
  <O extends Partial<GetNullableCatalogItems200Item> = {}>(
    overrideResponse?: O,
  ): MockWithNullableOverrides<
    GetNullableCatalogItems200Item,
    O,
    GetNullableCatalogItems200ItemMock
  > =>
    ({
      ...{
        id: faker.string.alpha({ length: { min: 10, max: 20 } }),
        name: faker.string.alpha({ length: { min: 10, max: 20 } }),
      },
      ...overrideResponse,
    }) as MockWithNullableOverrides<
      GetNullableCatalogItems200Item,
      O,
      GetNullableCatalogItems200ItemMock
    >;

export const getGetNullableCatalogItemsResponseMock = ():
  | GetNullableCatalogItems200ItemMock[]
  | null =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    ...(getGetNullableCatalogItemsResponseGetNullableCatalogItems200ItemNullItemMock() as GetNullableCatalogItems200ItemMock),
  }));

export const getGetCatalogItemsMockHandler = (
  overrideResponse?:
    | CatalogItems
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<CatalogItems> | CatalogItems),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/catalog-items',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetCatalogItemsResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetCatalogItemsInlineMockHandler = (
  overrideResponse?:
    | GetCatalogItemsInline200Item[]
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) =>
        | Promise<GetCatalogItemsInline200Item[]>
        | GetCatalogItemsInline200Item[]),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/catalog-items-inline',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetCatalogItemsInlineResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetCatalogItemsShortMockHandler = (
  overrideResponse?:
    | Items
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<Items> | Items),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/items',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetCatalogItemsShortResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetNullableListMockHandler = (
  overrideResponse?:
    | GetNullableList200
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<GetNullableList200> | GetNullableList200),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/nullable-list',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetNullableListResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetNullableCatalogItemsMockHandler = (
  overrideResponse?:
    | GetNullableCatalogItems200Item[]
    | null
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) =>
        | Promise<GetNullableCatalogItems200Item[] | null>
        | GetNullableCatalogItems200Item[]
        | null),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/nullable-catalog-items',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetNullableCatalogItemsResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};
export const getMSWArrayItemFactoriesUnexportedTopLevelArrayItemAliasesMock =
  () => [
    getGetCatalogItemsMockHandler(),
    getGetCatalogItemsInlineMockHandler(),
    getGetCatalogItemsShortMockHandler(),
    getGetNullableListMockHandler(),
    getGetNullableCatalogItemsMockHandler(),
  ];
