/*
 * Generated by orval v3.2.3 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import {
  MutationConfig,
  QueryConfig,
  useMutation,
  useQuery,
} from 'react-query';
import { CreatePetsBody, ListPetsParams, Pet, Pets } from '../model';
import { customInstance } from '../mutator/custom-instance';
type AsyncReturnType<T extends (...args: any) => Promise<any>> = T extends (
  ...args: any
) => Promise<infer R>
  ? R
  : any;

export const listPets = (params?: ListPetsParams, version: number = 1) => {
  return customInstance<Pets>({
    url: `/v${version}/pets`,
    method: 'get',
    params,
  });
};

export const getListPetsQueryKey = (
  params?: ListPetsParams,
  version: number = 1,
) => [`/v${version}/pets`, ...(params ? [params] : [])];

export const useListPets = <Error = unknown>(
  params?: ListPetsParams,
  version: number = 1,
  queryConfig?: QueryConfig<AsyncReturnType<typeof listPets>, Error>,
) => {
  const queryKey = getListPetsQueryKey(params, version);

  const query = useQuery<AsyncReturnType<typeof listPets>, Error>(
    queryKey,
    () => listPets(params, version),
    { enabled: version, ...queryConfig },
  );

  return {
    queryKey,
    ...query,
  };
};
export const createPets = (
  createPetsBody: CreatePetsBody,
  version: number = 1,
) => {
  return customInstance<unknown>({
    url: `/v${version}/pets`,
    method: 'post',
    data: createPetsBody,
  });
};

export const useCreatePets = <Error = unknown>(
  mutationConfig?: MutationConfig<
    AsyncReturnType<typeof createPets>,
    Error,
    { data: CreatePetsBody; version?: number }
  >,
) => {
  return useMutation<
    AsyncReturnType<typeof createPets>,
    Error,
    { data: CreatePetsBody; version?: number }
  >((props) => {
    const { data, version } = props || {};

    return createPets(data, version);
  }, mutationConfig);
};
export const showPetById = (petId: string, version: number = 1) => {
  return customInstance<Pet>({
    url: `/v${version}/pets/${petId}`,
    method: 'get',
  });
};

export const getShowPetByIdQueryKey = (petId: string, version: number = 1) => [
  `/v${version}/pets/${petId}`,
];

export const useShowPetById = <Error = unknown>(
  petId: string,
  version: number = 1,
  queryConfig?: QueryConfig<AsyncReturnType<typeof showPetById>, Error>,
) => {
  const queryKey = getShowPetByIdQueryKey(petId, version);

  const query = useQuery<AsyncReturnType<typeof showPetById>, Error>(
    queryKey,
    () => showPetById(petId, version),
    { enabled: version && petId, ...queryConfig },
  );

  return {
    queryKey,
    ...query,
  };
};
