/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Circular references
 * OpenAPI spec version: 0.0.0
 */
import * as zod from 'zod';

/**
 * @summary Example
 */
export const GetExampleResponse = zod.object({
  id: zod.coerce.number().optional(),
  name: zod.coerce.string().optional(),
  child: zod.unknown().optional(),
});

/**
 * @summary Node with required child
 */
export const GetNodeWithRequiredChildResponse = zod.object({
  id: zod.coerce.number(),
  name: zod.coerce.string(),
  child: zod.unknown(),
});

/**
 * @summary Add list
 */
export const addListQueryLimitRegExp = new RegExp('^\\+\\d{10, 15}');

export const AddListQueryParams = zod.object({
  limit: zod.coerce
    .string()
    .regex(addListQueryLimitRegExp)
    .optional()
    .describe('How many items to return at one time (max 100)'),
  birthdate: zod.coerce.string().date().optional().describe('birth date'),
});

export const addListBodyListItemMax = 10;

export const addListBodyListMax = 10;

export const AddListBody = zod.object({
  list: zod
    .array(zod.coerce.number().min(1).max(addListBodyListItemMax))
    .min(1)
    .max(addListBodyListMax),
});
