/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Combined enums
 * OpenAPI spec version: 1.0.0
 */

export * from './colorObject';
export * from './colors';
export * from './colors1';
export * from './colors2';
