/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Union enum ref mock
 * A parent schema references a string enum component via $ref while
 * enumGenerationType is 'union'. The union renders the enum as a pure type
 * (no runtime value), so the generated faker/msw mock must inline the enum
 * values instead of calling Object.values(EnumName) — which would fail tsc
 * with TS2693 (#3690).
 *
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';

import type { DisplayValueDto } from './model';

export const getUnionEnumRefMock = (axiosInstance: AxiosInstance = axios) => {
  const getDisplay = (
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<DisplayValueDto>> => {
    return axiosInstance.get(`/display`, options);
  };

  return { getDisplay };
};
export type GetDisplayResult = AxiosResponse<DisplayValueDto>;
