/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import { httpResource } from '@angular/common/http';
import type {
  HttpResourceOptions,
  HttpResourceRef,
} from '@angular/common/http';

import type { ResourceStatus, Signal } from '@angular/core';

export type OrvalHttpResourceOptions<
  TValue,
  TRaw = unknown,
  TOmitParse extends boolean = false,
> = TOmitParse extends true
  ? Omit<HttpResourceOptions<TValue, TRaw>, 'parse'>
  : HttpResourceOptions<TValue, TRaw>;
/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function healthCheckResource(
  options: OrvalHttpResourceOptions<string, string> & {
    defaultValue: NoInfer<string>;
  },
): HttpResourceRef<string>;
export function healthCheckResource(
  options?: OrvalHttpResourceOptions<string, string>,
): HttpResourceRef<string | undefined>;
export function healthCheckResource(
  options?: OrvalHttpResourceOptions<string, string>,
): HttpResourceRef<string | undefined> {
  return httpResource.text<string>(() => `/health`, options);
}

export type HealthCheckResourceResult = NonNullable<string>;

/**
 * Utility type for httpResource results with status tracking.
 * Inspired by @angular-architects/ngrx-toolkit withResource pattern.
 *
 * Uses `globalThis.Error` to avoid collision with API model types named `Error`.
 */
export interface ResourceState<T> {
  readonly value: Signal<T | undefined>;
  readonly status: Signal<ResourceStatus>;
  readonly error: Signal<globalThis.Error | undefined>;
  readonly isLoading: Signal<boolean>;
  readonly hasValue: () => boolean;
  readonly reload: () => boolean;
}

/**
 * Wraps an HttpResourceRef to expose a consistent ResourceState interface.
 * Useful when integrating with NgRx SignalStore via withResource().
 */
export function toResourceState<T>(ref: HttpResourceRef<T>): ResourceState<T> {
  return {
    value: ref.value,
    status: ref.status,
    error: ref.error,
    isLoading: ref.isLoading,
    hasValue: () => ref.hasValue(),
    reload: () => ref.reload(),
  };
}
