/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const Pet = zod
  .union([
    zod
      .union([
        zod.object({
          cuteness: zod.number(),
          breed: zod.enum(['Labradoodle']),
        }),
        zod.object({
          length: zod.number(),
          breed: zod.enum(['Dachshund']),
        }),
      ])
      .and(
        zod.object({
          barksPerMinute: zod.number().optional(),
          type: zod.enum(['dog']),
        }),
      ),
    zod.object({
      petsRequested: zod.number().optional(),
      type: zod.enum(['cat']),
    }),
  ])
  .and(
    zod.object({
      '@id': zod.string().optional(),
      id: zod.number(),
      name: zod.string(),
      tag: zod.string().optional(),
      email: zod.string().email().optional(),
      callingCode: zod.enum(['+33', '+420']).optional(),
      country: zod.enum(["People's Republic of China", 'Uruguay']).optional(),
    }),
  );

export type Pet = zod.input<typeof Pet>;
