/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Infinite Query Require Param
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  DashboardPageDto,
  GetFloorplanImageParams,
  ListDashboardsParams,
} from './model';

/**
 * @summary Get floorplan image by floor id
 */
export type getFloorplanImageResponse200 = {
  data: Blob;
  status: 200;
};

export type getFloorplanImageResponseSuccess = getFloorplanImageResponse200 & {
  headers: Headers;
};
export type getFloorplanImageResponse = getFloorplanImageResponseSuccess;

export const getGetFloorplanImageUrl = (
  id: string,
  params?: GetFloorplanImageParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/facility/floors/${id}/image?${stringifiedParams}`
    : `/api/facility/floors/${id}/image`;
};

export const getFloorplanImage = async (
  id: string,
  params?: GetFloorplanImageParams,
  options?: RequestInit,
): Promise<getFloorplanImageResponse> => {
  const res = await fetch(getGetFloorplanImageUrl(id, params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getFloorplanImageResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getFloorplanImageResponse;
};

export const getGetFloorplanImageQueryKey = (
  id: string,
  params?: GetFloorplanImageParams,
) => {
  return [
    `/api/facility/floors/${id}/image`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetFloorplanImageQueryOptions = <
  TData = Awaited<ReturnType<typeof getFloorplanImage>>,
  TError = unknown,
>(
  id: string,
  params?: GetFloorplanImageParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFloorplanImage>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetFloorplanImageQueryKey(id, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getFloorplanImage>>
  > = ({ signal }) =>
    getFloorplanImage(id, params, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getFloorplanImage>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFloorplanImageQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFloorplanImage>>
>;
export type GetFloorplanImageQueryError = unknown;

export function useGetFloorplanImage<
  TData = Awaited<ReturnType<typeof getFloorplanImage>>,
  TError = unknown,
>(
  id: string,
  params: undefined | GetFloorplanImageParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFloorplanImage>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFloorplanImage>>,
          TError,
          Awaited<ReturnType<typeof getFloorplanImage>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFloorplanImage<
  TData = Awaited<ReturnType<typeof getFloorplanImage>>,
  TError = unknown,
>(
  id: string,
  params?: GetFloorplanImageParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFloorplanImage>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFloorplanImage>>,
          TError,
          Awaited<ReturnType<typeof getFloorplanImage>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFloorplanImage<
  TData = Awaited<ReturnType<typeof getFloorplanImage>>,
  TError = unknown,
>(
  id: string,
  params?: GetFloorplanImageParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFloorplanImage>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get floorplan image by floor id
 */

export function useGetFloorplanImage<
  TData = Awaited<ReturnType<typeof getFloorplanImage>>,
  TError = unknown,
>(
  id: string,
  params?: GetFloorplanImageParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getFloorplanImage>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFloorplanImageQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List dashboards with pagination
 */
export type listDashboardsResponse200 = {
  data: DashboardPageDto;
  status: 200;
};

export type listDashboardsResponseSuccess = listDashboardsResponse200 & {
  headers: Headers;
};
export type listDashboardsResponse = listDashboardsResponseSuccess;

export const getListDashboardsUrl = (params?: ListDashboardsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/dashboard/dashboard?${stringifiedParams}`
    : `/api/dashboard/dashboard`;
};

export const listDashboards = async (
  params?: ListDashboardsParams,
  options?: RequestInit,
): Promise<listDashboardsResponse> => {
  const res = await fetch(getListDashboardsUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listDashboardsResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as listDashboardsResponse;
};

export const getListDashboardsQueryKey = (params?: ListDashboardsParams) => {
  return [`/api/dashboard/dashboard`, ...(params ? [params] : [])] as const;
};

export const getListDashboardsQueryOptions = <
  TData = Awaited<ReturnType<typeof listDashboards>>,
  TError = unknown,
>(
  params?: ListDashboardsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listDashboards>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListDashboardsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listDashboards>>> = ({
    signal,
  }) => listDashboards(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listDashboards>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListDashboardsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listDashboards>>
>;
export type ListDashboardsQueryError = unknown;

export function useListDashboards<
  TData = Awaited<ReturnType<typeof listDashboards>>,
  TError = unknown,
>(
  params: undefined | ListDashboardsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listDashboards>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDashboards>>,
          TError,
          Awaited<ReturnType<typeof listDashboards>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListDashboards<
  TData = Awaited<ReturnType<typeof listDashboards>>,
  TError = unknown,
>(
  params?: ListDashboardsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listDashboards>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDashboards>>,
          TError,
          Awaited<ReturnType<typeof listDashboards>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListDashboards<
  TData = Awaited<ReturnType<typeof listDashboards>>,
  TError = unknown,
>(
  params?: ListDashboardsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listDashboards>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List dashboards with pagination
 */

export function useListDashboards<
  TData = Awaited<ReturnType<typeof listDashboards>>,
  TError = unknown,
>(
  params?: ListDashboardsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listDashboards>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListDashboardsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
