/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

export type PetCallingCode =
  (typeof PetCallingCode)[keyof typeof PetCallingCode];

export const PetCallingCode = {
  '+33': '+33',
  '+420': '+420',
} as const;

export type PetCountry = (typeof PetCountry)[keyof typeof PetCountry];

export const PetCountry = {
  "People's_Republic_of_China": "People's Republic of China",
  Uruguay: 'Uruguay',
} as const;

export type LabradoodleBreed =
  (typeof LabradoodleBreed)[keyof typeof LabradoodleBreed];

export const LabradoodleBreed = {
  Labradoodle: 'Labradoodle',
} as const;

export interface Labradoodle {
  cuteness: number;
  breed: LabradoodleBreed;
}

export type DachshundBreed =
  (typeof DachshundBreed)[keyof typeof DachshundBreed];

export const DachshundBreed = {
  Dachshund: 'Dachshund',
} as const;

export interface Dachshund {
  length: number;
  breed: DachshundBreed;
}

export type DogType = (typeof DogType)[keyof typeof DogType];

export const DogType = {
  dog: 'dog',
} as const;

export type Dog =
  | (Labradoodle & {
      barksPerMinute?: number;
      type: DogType;
    })
  | (Dachshund & {
      barksPerMinute?: number;
      type: DogType;
    });

export type CatType = (typeof CatType)[keyof typeof CatType];

export const CatType = {
  cat: 'cat',
} as const;

export interface Cat {
  petsRequested?: number;
  type: CatType;
}

export type Pet =
  | (Dog & {
      '@id'?: string;
      id: number;
      name: string;
      tag?: string;
      email?: string;
      callingCode?: PetCallingCode;
      country?: PetCountry;
    })
  | (Cat & {
      '@id'?: string;
      id: number;
      name: string;
      tag?: string;
      email?: string;
      callingCode?: PetCallingCode;
      country?: PetCountry;
    });

export type Pets = Pet[];

export interface Error {
  code: number;
  message: string;
}

export interface PetWithTag {
  tag: string;
  pet: Pet | null;
}

export type ListPetsParams = {
  /**
   * How many items to return at one time (max 100)
   */
  limit?: string;
  /**
 * Which property to sort by?
Example: name sorts ASC while -name sorts DESC.

 */
  sort: ListPetsSort;
};

export type ListPetsSort = (typeof ListPetsSort)[keyof typeof ListPetsSort];

export const ListPetsSort = {
  name: 'name',
  '-name': '-name',
  email: 'email',
  '-email': '-email',
} as const;

export type CreatePetsParams = {
  /**
   * How many items to return at one time (max 100)
   */
  limit?: string;
  /**
 * Which property to sort by?
Example: name sorts ASC while -name sorts DESC.

 */
  sort: CreatePetsSort;
};

export type CreatePetsSort =
  (typeof CreatePetsSort)[keyof typeof CreatePetsSort];

export const CreatePetsSort = {
  name: 'name',
  '-name': '-name',
  email: 'email',
  '-email': '-email',
} as const;

export type CreatePetsBody = {
  name: string;
  tag: string;
};

/**
 * @summary List all pets
 */
export const listPets = (
  params: ListPetsParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Pets>> => {
  return axios.get(`/pets`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

/**
 * @summary Create a pet
 */
export const createPets = (
  createPetsBody: CreatePetsBody,
  params: CreatePetsParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Pet>> => {
  return axios.post(`/pets`, createPetsBody, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

/**
 * @summary Info for a specific pet
 */
export const showPetById = (
  petId: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Pet>> => {
  return axios.get(`/pets/${petId}`, options);
};

/**
 * @summary Deletes a specific pet
 */
export const deletePetById = (
  petId: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.delete(`/pets/${petId}`, options);
};

/**
 * @summary health check
 */
export const healthCheck = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<string>> => {
  return axios.get(`/health`, {
    responseType: 'text',
    ...options,
  });
};

/**
 * @summary combinate nullable and $ref
 */
export const showPetWithOwner = (
  petId: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<PetWithTag>> => {
  return axios.get(`/pets/${petId}/owner`, options);
};

export type ListPetsResult = AxiosResponse<Pets>;
export type CreatePetsResult = AxiosResponse<Pet>;
export type ShowPetByIdResult = AxiosResponse<Pet>;
export type DeletePetByIdResult = AxiosResponse<void>;
export type HealthCheckResult = AxiosResponse<string>;
export type ShowPetWithOwnerResult = AxiosResponse<PetWithTag>;
