/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Issue 3326 - Angular object query parameter support
 * OpenAPI spec version: 1.0.0
 */
import type { SearchParams, SearchResult } from './model';

import { customParamsSerializer } from '../../../mutators/fetch-params-serializer';
export type searchResponse200 = {
  data: SearchResult;
  status: 200;
};

export type searchResponseSuccess = searchResponse200 & {
  headers: Headers;
};
export type searchResponse = searchResponseSuccess;

export const getSearchUrl = (params?: SearchParams) => {
  const stringifiedParams = customParamsSerializer(params);

  return stringifiedParams.length > 0
    ? `/api/search?${stringifiedParams}`
    : `/api/search`;
};

export const search = async (
  params?: SearchParams,
  options?: RequestInit,
): Promise<searchResponse> => {
  const res = await fetch(getSearchUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: searchResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as searchResponse;
};
