/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Issue 3301 - keep unreferenced schemas under tag filter
 * OpenAPI spec version: 1.0.0
 */

export type UnusedStatus = (typeof UnusedStatus)[keyof typeof UnusedStatus];

export const UnusedStatus = {
  active: 'active',
  archived: 'archived',
} as const;
