/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';

import type {
  CreatePetsBody,
  CreatePetsParams,
  ListPetsParams,
  Pet,
  PetWithTag,
  Pets,
} from '.././model';

export const getPets = (axiosInstance: AxiosInstance = axios) => {
  /**
   * @summary List all pets
   */
  const listPets = (
    params: ListPetsParams,
    version: number = 1,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<Pets>> => {
    return axiosInstance.get(`/v${version}/pets`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  /**
   * @summary Create a pet
   */
  const createPets = (
    createPetsBody: CreatePetsBody,
    params: CreatePetsParams,
    version: number = 1,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<Pet>> => {
    return axiosInstance.post(`/v${version}/pets`, createPetsBody, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  /**
   * @summary Info for a specific pet
   */
  const showPetById = (
    petId: string,
    version: number = 1,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<Pet>> => {
    return axiosInstance.get(`/v${version}/pets/${petId}`, options);
  };
  /**
   * @summary Deletes a specific pet
   */
  const deletePetById = (
    petId: string,
    version: number = 1,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(`/v${version}/pets/${petId}`, options);
  };
  /**
   * @summary combinate nullable and $ref
   */
  const showPetWithOwner = (
    petId: string,
    version: number = 1,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<PetWithTag>> => {
    return axiosInstance.get(`/v${version}/pets/${petId}/owner`, options);
  };
  return { listPets, createPets, showPetById, deletePetById, showPetWithOwner };
};
export type ListPetsResult = AxiosResponse<Pets>;
export type CreatePetsResult = AxiosResponse<Pet>;
export type ShowPetByIdResult = AxiosResponse<Pet>;
export type DeletePetByIdResult = AxiosResponse<void>;
export type ShowPetWithOwnerResult = AxiosResponse<PetWithTag>;
