/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Discriminator duplication reproduction
 * OpenAPI spec version: 1.0.0
 */
import type { Cat } from './cat';
import type { Dog } from './dog';

export type Animal = Dog | Cat;
