/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Nullables
 * Nullable types
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

import type { NullableObject } from './model';

/**
 * @summary Nullable response
 */
export const fetchNullable = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<string | null>> => {
  return axios.get(`/nullable`, options);
};

/**
 * @summary Nullable object response
 */
export const fetchNullableObject = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<NullableObject>> => {
  return axios.get(`/nullable-object`, options);
};

/**
 * @summary Nullable with multipart/form-data request
 */
export const nullableWithMultipartFormRequest = (
  nullableObject: NullableObject,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<NullableObject>> => {
  const formData = new FormData();
  if (nullableObject.name !== undefined && nullableObject.name !== null) {
    formData.append(`name`, nullableObject.name);
  }
  if (nullableObject.age !== undefined && nullableObject.age !== null) {
    formData.append(`age`, nullableObject.age.toString());
  }
  if (nullableObject.address !== undefined && nullableObject.address !== null) {
    formData.append(`address`, nullableObject.address);
  }
  if (
    nullableObject.is_active !== undefined &&
    nullableObject.is_active !== null
  ) {
    formData.append(`is_active`, nullableObject.is_active.toString());
  }

  return axios.post(`/nullable-with-multipart-form-data`, formData, options);
};

export type FetchNullableResult = AxiosResponse<string | null>;
export type FetchNullableObjectResult = AxiosResponse<NullableObject>;
export type NullableWithMultipartFormRequestResult =
  AxiosResponse<NullableObject>;
