/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Faker array item factories
 * OpenAPI spec version: 1.0.0
 */
import { faker } from '@faker-js/faker';

import type {
  Cat,
  Dog,
  GetCollide200,
  GetNames200,
  GetNullable200,
  GetTenants200,
  GetTenants200ValueItem,
  GetThings200,
  TenantListResponse,
  TenantResponseModelDto,
} from './model';

export const getGetTenantsResponseValueItemMock = (
  overrideResponse: Partial<GetTenants200ValueItem> = {},
): GetTenants200ValueItem => ({
  ...{
    id: faker.string.uuid(),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  },
  ...overrideResponse,
});

export const getGetTenantsResponseMock = (
  overrideResponse: Partial<Extract<GetTenants200, object>> = {},
): GetTenants200 => ({
  value: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({ ...getGetTenantsResponseValueItemMock() })),
  count: faker.number.int(),
  ...overrideResponse,
});

export const getTenantResponseModelDtoMock = (
  overrideResponse: Partial<TenantResponseModelDto> = {},
): TenantResponseModelDto => ({
  ...{
    id: faker.string.uuid(),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  },
  ...overrideResponse,
});

export const getGetTenantsByRefResponseMock = (
  overrideResponse: Partial<Extract<TenantListResponse, object>> = {},
): TenantListResponse => ({
  value: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({ ...getTenantResponseModelDtoMock() })),
  count: faker.number.int(),
  ...overrideResponse,
});

export const getGetTenantsAResponseMock = (
  overrideResponse: Partial<Extract<TenantListResponse, object>> = {},
): TenantListResponse => ({
  value: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({ ...getTenantResponseModelDtoMock() })),
  count: faker.number.int(),
  ...overrideResponse,
});

export const getGetTenantsBResponseMock = (
  overrideResponse: Partial<Extract<TenantListResponse, object>> = {},
): TenantListResponse => ({
  value: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({ ...getTenantResponseModelDtoMock() })),
  count: faker.number.int(),
  ...overrideResponse,
});

export const getGetNamesResponseMock = (
  overrideResponse: Partial<Extract<GetNames200, object>> = {},
): GetNames200 => ({
  names: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() => faker.internet.email()),
    undefined,
  ]),
  ...overrideResponse,
});

export const getGetThingsResponseCatMock = (
  overrideResponse: Partial<Cat> = {},
): Cat => ({
  ...{
    meow: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  },
  ...overrideResponse,
});

export const getGetThingsResponseDogMock = (
  overrideResponse: Partial<Dog> = {},
): Dog => ({
  ...{
    bark: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  },
  ...overrideResponse,
});

export const getGetThingsResponseMock = (
  overrideResponse: Partial<Extract<GetThings200, object>> = {},
): GetThings200 => ({
  things: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() =>
      faker.helpers.arrayElement([
        { ...getGetThingsResponseCatMock() },
        { ...getGetThingsResponseDogMock() },
      ]),
    ),
    undefined,
  ]),
  ...overrideResponse,
});

export const getGetNullableResponseMock = (
  overrideResponse: Partial<Extract<GetNullable200, object>> = {},
): GetNullable200 => ({
  rows: faker.helpers.arrayElement([
    Array.from(
      { length: faker.number.int({ min: 1, max: 10 }) },
      (_, i) => i + 1,
    ).map(() =>
      faker.helpers.arrayElement([
        {
          id: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
        },
        null,
      ]),
    ),
    undefined,
  ]),
  ...overrideResponse,
});

export const getGetCollideResponseMock = (
  overrideResponse: Partial<Extract<GetCollide200, object>> = {},
): GetCollide200 => ({
  outer: faker.helpers.arrayElement([
    {
      items: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ min: 1, max: 10 }) },
          (_, i) => i + 1,
        ).map(() => ({
          a: faker.helpers.arrayElement([
            faker.string.alpha({ length: { min: 10, max: 20 } }),
            undefined,
          ]),
        })),
        undefined,
      ]),
    },
    undefined,
  ]),
  inner: faker.helpers.arrayElement([
    {
      items: faker.helpers.arrayElement([
        Array.from(
          { length: faker.number.int({ min: 1, max: 10 }) },
          (_, i) => i + 1,
        ).map(() => ({
          b: faker.helpers.arrayElement([
            faker.number.float({ fractionDigits: 2 }),
            undefined,
          ]),
        })),
        undefined,
      ]),
    },
    undefined,
  ]),
  ...overrideResponse,
});
