import type { Metadata } from 'next';

import { setupServer } from 'msw/node';
import { Inter } from 'next/font/google';

import { getPetsMock } from './gen/pets/pets.msw';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const server = setupServer();
server.use(...getPetsMock());
server.listen();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
