/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
export interface Error {
  code: number;
  message: string;
}

export interface PetWithTag {
  tag: string;
  pet: Pet | null;
}
