/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Faker array item factories (tags-split)
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';

import type { TenantListResponse } from '../model';

export const getBeta = (axiosInstance: AxiosInstance = axios) => {
  const getB = (
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<TenantListResponse>> => {
    return axiosInstance.get(`/b`, options);
  };
  return { getB };
};
export type GetBResult = AxiosResponse<TenantListResponse>;
