/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Discriminator with oneOf union and allOf-inherited variants
 * OpenAPI spec version: 1.0
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

import type { DiscriminatorTest } from './model';

export const getTest = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<DiscriminatorTest>> => {
  return axios.get(`/test`, options);
};

export type GetTestResult = AxiosResponse<DiscriminatorTest>;
