nodeLinker: node-modules

packageExtensions:
  # issue with @vue/test-utils@2.4.6
  # https://github.com/vuejs/test-utils/issues/2581
  '@vue/test-utils@*':
    peerDependencies:
      vue: '*'

enableScripts: false
