nodeLinker: node-modules

packageExtensions:
  # issue with @vue/test-utils@2.4.6
  # https://github.com/vuejs/test-utils/issues/2581
  '@vue/test-utils@*':
    peerDependencies:
      vue: '*'

enableScripts: false
npmPublishAccess: public
npmRegistryServer: https://registry.npmjs.org

# https://yarnpkg.com/features/catalogs
catalog:
  eslint: 9.39.2
  '@eslint/js': 9.39.2
  prettier: 3.8.1
  rimraf: 6.1.2
  tslib: 2.8.1
  tsdown: 0.18.2
  typescript: 5.9.3
  vitest: 4.0.16
  '@types/node': 22.18.12
  '@scalar/openapi-types': 0.5.3

# using named catalogs to align packages in /tests with /samples
catalogs:
  angular:
    # Runtime packages kept in sync (https://github.com/angular/angular/blob/main/tools/bazel/npm_packages.bzl)
    '@angular/core': 21.1.4
    '@angular/common': 21.1.4
    '@angular/compiler': 21.1.4
    '@angular/compiler-cli': 21.1.4
    '@angular/animations': 21.1.4
    '@angular/platform-browser': 21.1.4
    '@angular/forms': 21.1.4
    '@angular/router': 21.1.4
    rxjs: 7.8.2
    # Build tooling uses last available patch
    '@angular/build': 21.1.4
    '@angular/cli': 21.1.4
  tooling:
    '@faker-js/faker': 10.3.0
    msw: 2.12.10
