nodeLinker: node-modules

packageExtensions:
  # issue with @vue/test-utils@2.4.6
  # https://github.com/vuejs/test-utils/issues/2581
  '@vue/test-utils@*':
    peerDependencies:
      vue: '*'

enableScripts: false
npmPublishAccess: public
npmRegistryServer: https://registry.npmjs.org

# https://yarnpkg.com/features/catalogs
catalog:
  eslint: 9.39.2
  '@eslint/js': 9.39.2
  prettier: 3.8.1
  rimraf: 6.1.2
  tslib: 2.8.1
  tsdown: 0.20.3
  typescript: 5.9.3
  npm-run-all2: 8.0.4
  vite: 7.2.2
  vitest: 4.0.18
  '@types/node': 22.18.12 # pinned to minimum supported version by orval
  '@scalar/openapi-types': 0.5.3

# using named catalogs to align packages in /tests with /samples
catalogs:
  angular:
    # Runtime packages kept in sync (https://github.com/angular/angular/blob/main/tools/bazel/npm_packages.bzl)
    '@angular/core': 21.1.4
    '@angular/common': 21.1.4
    '@angular/compiler': 21.1.4
    '@angular/compiler-cli': 21.1.4
    '@angular/animations': 21.1.4
    '@angular/platform-browser': 21.1.4
    '@angular/forms': 21.1.4
    '@angular/router': 21.1.4
    rxjs: 7.8.2
    # Build tooling uses last available patch
    '@angular/build': 21.1.4
    '@angular/cli': 21.1.4
  axios:
    axios: 1.13.5
  tooling:
    '@faker-js/faker': 10.3.0
    msw: 2.12.10
  hono:
    hono: 4.11.9
    '@hono/zod-validator': 0.7.6
  zod3:
    zod: 3.25.76
  swr:
    swr: 2.3.6
  vue:
    vue: 3.5.26
    vue-tsc: 3.2.4
    '@tanstack/vue-query': 5.92.7
  svelte:
    svelte: 5.53.0
    svelte-check: 3.8.6
    '@tanstack/svelte-query': 4.41.0
  react:
    react: 18.3.1
    '@types/react': 18.3.24
    '@tanstack/react-query': 5.62.16
  mcp:
    '@modelcontextprotocol/sdk': 1.26.0
