nodeLinker: node-modules

packageExtensions:
  # issue with @vue/test-utils@2.4.6
  # https://github.com/vuejs/test-utils/issues/2581
  '@vue/test-utils@*':
    peerDependencies:
      vue: '*'

enableScripts: false
npmPublishAccess: public
npmRegistryServer: https://registry.npmjs.org

# https://yarnpkg.com/features/catalogs
catalog:
  eslint: 9.38.0
  '@eslint/js': 9.38.0
  prettier: 3.6.2
  rimraf: 6.0.1
  tsdown: 0.15.9
  typescript: 5.9.3
  vitest: 4.0.6
  '@types/node': 22.18.12

# using named catalogs to align packages in /tests with /samples
catalogs:
  angular:
    '@angular/common': ^20.3.0
    '@angular/core': ^20.3.0
