nodeLinker: node-modules

packageExtensions:
  # issue with @vue/test-utils@2.4.6
  # https://github.com/vuejs/test-utils/issues/2581
  '@vue/test-utils@*':
    peerDependencies:
      vue: '*'

enableScripts: false
npmPublishAccess: public
npmRegistryServer: https://registry.npmjs.org

# https://yarnpkg.com/features/catalogs

# using named catalogs to align packages in /tests with /samples
catalogs:
  lint:
    eslint: 9.39.2
    '@eslint/js': 9.39.2
    '@typescript-eslint/eslint-plugin': 8.54.0
    '@typescript-eslint/parser': 8.54.0
    prettier: 3.7.4
  test:
    vitest: 4.0.18
    msw: 2.12.9
    '@testing-library/angular': 19.0.0
    '@faker-js/faker': 10.3.0
  tooling:
    rimraf: 6.1.2
    tsdown: 0.18.2
    typescript: 5.9.3
    '@types/node': 22.18.12
    '@scalar/openapi-types': 0.5.3
    zod: 3.25.76
  angular:
    # Runtime packages kept in sync (https://github.com/angular/angular/blob/main/tools/bazel/npm_packages.bzl)
    '@angular/core': 21.1.0
    '@angular/common': 21.1.0
    '@angular/compiler': 21.1.0
    '@angular/compiler-cli': 21.1.0
    '@angular/animations': 21.1.0
    '@angular/platform-browser': 21.1.0
    '@angular/forms': 21.1.0
    '@angular/router': 21.1.0
    rxjs: 7.8.2
    tslib: 2.8.1
    '@tanstack/angular-query-experimental': 5.62.7
    # Build tooling uses last available patch
    '@angular/build': 21.1.0
    '@angular/cli': 21.1.0
    # Linting (Angular ESLint)
    '@angular-eslint/builder': 21.1.0
    '@angular-eslint/eslint-plugin': 21.1.0
    '@angular-eslint/eslint-plugin-template': 21.1.0
    '@angular-eslint/template-parser': 21.1.0
