# This is just for testing purposes, pnpm is not used in this project.
# We do however read package.json to figure out which version of different
# packages the user has, and some users use pnpm with the catalog feature.
# We support this by reading the pnpm-workspace.yaml file they have instead
# of package.json.
catalog:
  typescript: ^5.2.0
  '@tanstack/react-query': '^5.67.2'

catalogs:
  # Can be referenced through "catalog:ts4"
  ts4:
    typescript: ^4.4.0

  # Can be referenced through "catalog:ts5"
  ts5:
    typescript: ^5.2.0
