/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import type { AnotherSchema, Pet } from './model';

export type postPetsResponse200 = {
  data: Pet;
  status: 200;
};

export type postPetsResponseSuccess = postPetsResponse200 & {
  headers: Headers;
};
export type postPetsResponse = postPetsResponseSuccess;

export const getPostPetsUrl = () => {
  return `/pets`;
};

export const postPets = async (
  options?: RequestInit,
): Promise<postPetsResponse> => {
  const res = await fetch(getPostPetsUrl(), {
    ...options,
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postPetsResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as postPetsResponse;
};

export type getPetsResponse200 = {
  data: AnotherSchema;
  status: 200;
};

export type getPetsResponseSuccess = getPetsResponse200 & {
  headers: Headers;
};
export type getPetsResponse = getPetsResponseSuccess;

export const getGetPetsUrl = () => {
  return `/pets`;
};

export const getPets = async (
  options?: RequestInit,
): Promise<getPetsResponse> => {
  const res = await fetch(getGetPetsUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getPetsResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getPetsResponse;
};
