/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import type { Pet } from './pet';

export interface N42PetsNestedArray {
  data?: Pet[];
}
