/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import { Hono } from 'hono';

import {
  listPetsHandlers,
  createPetsHandlers,
  showPetByIdHandlers,
  deletePetByIdHandlers,
  showPetWithOwnerHandlers,
} from './pets.handlers';

const app = new Hono()
  /**
   * @summary List all pets
   */

  .get('/pets', ...listPetsHandlers)
  /**
   * @summary Create a pet
   */

  .post('/pets', ...createPetsHandlers)
  /**
   * @summary Info for a specific pet
   */

  .get('/pets/:petId', ...showPetByIdHandlers)
  /**
   * @summary Deletes a specific pet
   */

  .delete('/pets/:petId', ...deletePetByIdHandlers)
  /**
   * @summary combinate nullable and $ref
   */

  .get('/pets/:petId/owner', ...showPetWithOwnerHandlers);
export default app;
