/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Circular references
 * OpenAPI spec version: 0.0.0
 */

export type AddListParams = {
  /**
   * How many items to return at one time (max 100)
   * @pattern ^\+\d{10, 15}
   */
  limit?: string;
  /**
   * birth date
   */
  birthdate?: string;
};
