/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Circular references
 * OpenAPI spec version: 0.0.0
 */
import type { Node as __Node } from './node';

export interface Node {
  id?: number;
  name?: string;
  child?: __Node;
}
