/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Gateway Tuple Demo
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';

import type { GetInventoryStockParams, Product } from '../model';

export const getInventory = (axiosInstance: AxiosInstance = axios) => {
  const getStock = (
    params?: GetInventoryStockParams,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<Product>> => {
    return axiosInstance.get(`/api/inventory/stock`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };
  const postStock = (
    product: Product,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<Product>> => {
    return axiosInstance.post(`/api/inventory/stock`, product, options);
  };
  return { getStock, postStock };
};
export type GetInventoryStockResult = AxiosResponse<Product>;
export type PostInventoryStockResult = AxiosResponse<Product>;
