/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import type { ICatType } from './iCatType';

export interface ICat {
  petsRequested?: number;
  type: ICatType;
}
