/**
 * Generated by orval v6.1.2 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */

export type PetCountry = "People's Republic of China" | 'Uruguay';

export const PetCountry = {
  Peoples_Republic_of_China: "People's Republic of China" as PetCountry,
  Uruguay: 'Uruguay' as PetCountry,
};
