/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import { Hono } from 'hono';
import {
  listPetsHandlers,
  createPetsHandlers,
  updatePetsHandlers,
  showPetByIdHandlers,
} from './endpoints/pets/pets.handlers';

const app = new Hono()
  .get('/pets', ...listPetsHandlers)
  .post('/pets', ...createPetsHandlers)
  .put('/pets', ...updatePetsHandlers)
  .get('/pets/:petId', ...showPetByIdHandlers);

export default app;
