/*
 * Generated by orval v2.5.9 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import { AxiosInstance, AxiosPromise } from 'axios';
export interface Pet {
  id: number;
  name: string;
  tag?: string;
}

export type Pets = Pet[];

export interface Error {
  code: number;
  message: string;
}

export type ListPetsParams = { limit?: number };

export interface SwaggerPetstoreApi {
  // List all pets
  listPets(params?: ListPetsParams): AxiosPromise<Pets>;
  // Create a pet
  createPets(): AxiosPromise<unknown>;
  // Info for a specific pet
  showPetById(petId: string, testId: string): AxiosPromise<Pet>;
}

export const getSwaggerPetstoreApi = (
  axios: AxiosInstance,
): SwaggerPetstoreApi => ({
  listPets(params?: ListPetsParams): AxiosPromise<Pets> {
    return axios.get(`/pets`, {
      params,
    });
  },
  createPets(): AxiosPromise<unknown> {
    return axios.post(`/pets`, undefined);
  },
  showPetById(petId: string, testId: string): AxiosPromise<Pet> {
    return axios.get(`/pets/${petId}/test/${testId}`);
  },
});
