/*
 * Generated by orval v4.0.0 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
export interface Pet {
  id: number;
  name: string;
  tag?: string;
}

export type Pets = Pet[];

export interface Error {
  code: number;
  message: string;
}

export type ListPetsParams = { limit?: string };

export type CreatePetsBody = {
  name: string;
  tag: string;
};

export const getSwaggerPetstore = () => ({
  listPets(params?: ListPetsParams) {
    return axios.get<Pets>(`/pets`, {
      params,
    });
  },
  createPets(createPetsBody: CreatePetsBody) {
    return axios.post<unknown>(`/pets`, createPetsBody);
  },
  showPetById(petId: string) {
    return axios.get<Pet>(`/pets/${petId}`);
  },
});
