/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * NestedArrays
 * OpenAPI spec version: 1.0.0
 */
import type { Arguments, Key } from 'swr';

import useSWRMutation from 'swr/mutation';
import type { SWRMutationConfiguration } from 'swr/mutation';

import { faker } from '@faker-js/faker';

import { HttpResponse, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import type { ResSampleModel } from './model';

/**
 * @summary sample
 */
export type postApiSampleResponse200 = {
  data: ResSampleModel;
  status: 200;
};

export type postApiSampleResponseSuccess = postApiSampleResponse200 & {
  headers: Headers;
};
export type postApiSampleResponse = postApiSampleResponseSuccess;

export const getPostApiSampleUrl = () => {
  return `/api/sample`;
};

export const postApiSample = async (
  options?: RequestInit,
): Promise<postApiSampleResponse> => {
  const res = await fetch(getPostApiSampleUrl(), {
    ...options,
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postApiSampleResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postApiSampleResponse;
};

export const getPostApiSampleMutationFetcher = (options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return postApiSample(options);
  };
};
export const getPostApiSampleMutationKey = () => [`/api/sample`] as const;

export type PostApiSampleMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiSample>>
>;

/**
 * @summary sample
 */
export const usePostApiSample = <TError = Promise<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postApiSample>>,
    TError,
    Key,
    Arguments,
    Awaited<ReturnType<typeof postApiSample>>
  > & { swrKey?: string };
  fetch?: RequestInit;
}) => {
  const { swr: swrOptions, fetch: fetchOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostApiSampleMutationKey();
  const swrFn = getPostApiSampleMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

export const getPostApiSampleResponseMock = (
  overrideResponse: Partial<Extract<ResSampleModel, object>> = {},
): ResSampleModel => ({
  items: Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() =>
    Array.from(
      { length: faker.number.int({ min: 2, max: 5 }) },
      (_, i) => i + 1,
    ).map(() => faker.string.alpha({ length: { min: 10, max: 20 } })),
  ),
  ...overrideResponse,
});

export const getPostApiSampleMockHandler = (
  overrideResponse?:
    | ResSampleModel
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ResSampleModel> | ResSampleModel),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/api/sample',
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getPostApiSampleResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};
export const getNestedArraysMock = () => [getPostApiSampleMockHandler()];
