/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Vue Query hook mutator - path and query param unref
 * OpenAPI spec version: 1.0.0
 */

export type GetProductParams = {
  q?: string;
};
