/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Tags Split Shared Models
 * OpenAPI spec version: 1.0.0
 */
import type { SortOrder } from '../sortOrder';

export type ListPetsParams = {
  limit?: number;
  sort?: SortOrder;
};
