/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: V1
 */
import type { ParentType } from './parentType';

export type DescendantTwo = ParentType & {
  value: string;
};
