/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: V1
 */

export * from './descendantOne';
export * from './descendantTwo';
export * from './parentType';
export * from './parentTypeType';
