/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: V1
 */
import type { ParentTypeType } from './parentTypeType';

export interface ParentType {
  key?: string;
  type: ParentTypeType;
}
