/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Recursive discriminator with allOf base
 * OpenAPI spec version: 0.1.0
 */
import type { Derived1 } from './derived1';
import type { Derived2 } from './derived2';

export interface Base {
  discriminator?: string;
  /** @nullable */
  BaseProp: string | null;
  Parent?: Derived1 | Derived2 | null;
}
