/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

import type { PrivateNote, SharedNote } from './model';

export const createSharedNote = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<SharedNote>> => {
  return axios.post(`/shared-notes`, undefined, options);
};

/**
 * @summary Create a private note for the beneficiary.
 */
export const createPrivateNote = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<PrivateNote>> => {
  return axios.post(`/private-notes`, undefined, options);
};

export type CreateSharedNoteResult = AxiosResponse<SharedNote>;
export type CreatePrivateNoteResult = AxiosResponse<PrivateNote>;
