/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * Issue 3200
 * Reproduces the case where an object schema used as a dictionary
 * (`additionalProperties: { $ref: <primitive union> }`) generates an invalid
 * faker schema mock under `schemas: true`. The delegated `$ref` was wrapped in
 * `{ ...get<X>Mock() }`, but the factory returns a primitive union
 * (e.g. number | string), so spreading it is invalid TypeScript (TS2698) and
 * yields `{}` at runtime. The generated dictionary value should be the bare
 * `get<X>Mock()` call instead.
 *
 * OpenAPI spec version: 1.0.0
 */

export * from './integerLike';
export * from './numberLike';
export * from './stringToIntegerMap';
export * from './stringToNumberMap';
