/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Angular httpResource Request Extension Test
 * Test spec for the httpResource request descriptor extension (#3710): a required `in: header` parameter combined with multiple success content types, used to pin the applyOrvalRequestExtension + Accept-header ordering in the generated multi-content-type branches.
 * OpenAPI spec version: 1.0.0
 */

export * from './error';
export * from './getItemEventsHeaders';
export * from './itemEvent';
export * from './itemEvents';
