/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Sample API
 * A sample api
 * OpenAPI spec version: 1.0
 */

export type SampleAccountStatus =
  (typeof SampleAccountStatus)[keyof typeof SampleAccountStatus];

export const SampleAccountStatus = {
  Unknown: 0,
  NotStarted: 1,
  InProgress: 2,
  Completed: 3,
} as const;
