/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Dates transform
 * OpenAPI spec version: 1.0.0
 */
import type { OrderEvent } from './orderEvent';

export interface OrderDetails {
  placedAt: Date;
  /** @nullable */
  deliveredAt?: Date | null;
  lastViewedAt?: Date;
  name?: string;
  events: OrderEvent[];
}
