/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Enums
 * OpenAPI spec version: 1.0.0
 */
import type { RequiredSiamese } from './requiredSiamese';

export interface RequiredCat {
  petsRequested?: RequiredSiamese[];
}
