/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Issue 1879 - Header $ref to another path's parameter
 * OpenAPI spec version: 1.0.0
 */

export type RequestBHeaders = {
  /**
   * The expected content type.
   * @pattern ^application\/json$
   */
  'Content-Type'?: string;
};
