/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Issue 3590 - strict faker schema mock type errors
 * OpenAPI spec version: 1.0.0
 */
import type { PetCategory } from './petCategory';

export interface PetSetting {
  name: string;
  category: PetCategory;
  /** @nullable */
  notes?: string | null;
}
