/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/solid-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  SolidQueryOptions,
  UndefinedInitialDataOptions,
  UseQueryResult,
} from '@tanstack/solid-query';

import { mergeProps } from 'solid-js';

import type { Error } from '../model';

export const getHealthCheckUrl = () => {
  return `/health`;
};

/**
 * @summary health check
 */
export const healthCheck = async (options?: RequestInit): Promise<string> => {
  const res = await fetch(getHealthCheckUrl(), {
    ...options,
    method: 'GET',
  });

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: string = body
    ? contentType.includes('json')
      ? JSON.parse(body)
      : body
    : {};
  return data;
};

export const getHealthCheckQueryKey = () => {
  return [`/health`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = Error,
>(options?: {
  query?: Omit<
    Partial<
      SolidQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>
    >,
    'initialData'
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = Error;

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = Error,
>(
  options: {
    query: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof healthCheck>>,
          TError,
          TData
        >
      >,
      'initialData'
    > &
      Pick<
        ReturnType<
          DefinedInitialDataOptions<
            Awaited<ReturnType<typeof healthCheck>>,
            TError,
            TData
          >
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = Error,
>(
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof healthCheck>>,
          TError,
          TData
        >
      >,
      'initialData'
    > &
      Pick<
        ReturnType<
          UndefinedInitialDataOptions<
            Awaited<ReturnType<typeof healthCheck>>,
            TError,
            TData
          >
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = Error,
>(
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof healthCheck>>,
          TError,
          TData
        >
      >,
      'initialData'
    >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = Error,
>(
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof healthCheck>>,
          TError,
          TData
        >
      >,
      'initialData'
    >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(
    () => getHealthCheckQueryOptions(options),
    queryClient,
  );

  return mergeProps(query, { queryKey: queryOptions.queryKey }) as any;
}
