openapi: '3.0.0'
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /search:
    get:
      summary: Search pets by query params
      operationId: searchPets
      tags:
        - pets
      parameters:
        - name: requirednullableString
          in: query
          required: true
          schema:
            type: string
            nullable: true
        - name: requirednullableStringTwo
          in: query
          required: true
          schema:
            type: string
            nullable: true
        - name: nonRequirednullableString
          in: query
          required: false
          schema:
            type: string
            nullable: true
        - name: status
          in: query
          required: false
          description: Filter by adoption status
          schema:
            type: string
            enum:
              - available
              - pending
              - sold
        - name: limit
          in: query
          required: false
          description: Maximum number of results to return
          schema:
            type: integer
            minimum: 1
            maximum: 100
      responses:
        '200':
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pets'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pets'
            application/xml:
              schema:
                $ref: '#/components/schemas/Pets'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a pet
      operationId: createPets
      tags:
        - pets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - 'name'
                - 'tag'
              properties:
                name:
                  type: string
                  minLength: 1
                  maxLength: 100
                  description: Name of the pet
                tag:
                  type: string
                  minLength: 1
                  maxLength: 50
                  description: Classification tag
                email:
                  type: string
                  format: email
                  description: Owner contact email
                status:
                  type: string
                  enum:
                    - available
                    - pending
                    - sold
                  default: available
                  description: Initial adoption status
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /pets/{petId}:
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
        - name: testId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            text/plain:
              schema:
                type: string
              example: plain-pet
            application/xml:
              schema:
                $ref: '#/components/schemas/Pet'
              example:
                id: 101
                name: xml-pet
                tag: xml
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
              example:
                id: 102
                name: json-pet
                tag: json
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /pets/{petId}/text:
    get:
      summary: Info for a specific pet as plain text
      operationId: showPetText
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            text/plain:
              schema:
                type: string
              example: plain-text-only-pet
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /pet/{petId}/uploadImage:
    post:
      tags:
        - pets
      summary: Uploads an image.
      description: Upload image of the pet.
      operationId: uploadFile
      parameters:
        - name: petId
          in: path
          description: ID of pet to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: successful operation
        '400':
          description: No file uploaded
        '404':
          description: Pet not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /pet/{petId}/downloadImage:
    get:
      tags:
        - pets
      summary: Download an image.
      description: Download image of the pet.
      operationId: downloadFile
      parameters:
        - name: petId
          in: path
          description: ID of pet to download
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          description: No file downloaded
        '404':
          description: Pet not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
        - requiredNullableString
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
          description: Unique identifier for the pet
        name:
          type: string
          minLength: 1
          maxLength: 100
          description: Name of the pet
        tag:
          type: string
          minLength: 1
          maxLength: 50
          description: Optional classification tag
        email:
          type: string
          format: email
          description: Owner contact email
        status:
          type: string
          enum:
            - available
            - pending
            - sold
          default: available
          description: Current adoption status
        age:
          type: integer
          format: int32
          minimum: 0
          maximum: 30
          description: Age of the pet in years
        rating:
          type: number
          format: double
          minimum: 0
          maximum: 5
          multipleOf: 0.5
          description: Average customer rating
        phone:
          type: string
          pattern: '^\+?[1-9]\d{1,14}$'
          description: Contact phone in E.164 format
        requiredNullableString:
          type: string
          nullable: true
        optionalNullableString:
          type: string
          nullable: true
    Pets:
      type: array
      maxItems: 100
      items:
        $ref: '#/components/schemas/Pet'
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          minimum: 100
          maximum: 600
          description: HTTP-like error code
        message:
          type: string
          minLength: 1
          description: Human-readable error message
