/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse,
} from '@angular/common/http';
import type { HttpContext, HttpEvent, HttpParams } from '@angular/common/http';

import { Injectable, inject } from '@angular/core';

import { Observable } from 'rxjs';

import { PETSTORE_API_BASE_URL } from './endpoints.base-url';

import type {
  CreatePetsBody,
  CreatePetsParams,
  ListPetsParams,
  Pet,
  PetWithTag,
  Pets,
} from './model';

interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
    | HttpParams
    | Record<
        string,
        string | number | boolean | Array<string | number | boolean>
      >;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: { includeHeaders?: string[] } | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};

type AngularHttpParamValue =
  | string
  | number
  | boolean
  | Array<string | number | boolean>;
type AngularHttpParamValueWithNullable = AngularHttpParamValue | null;

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys?: ReadonlySet<string>,
  preserveRequiredNullables?: false,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValue>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: true,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValueWithNullable>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: boolean | undefined,
  passthroughKeys: ReadonlySet<string>,
): Record<string, unknown>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> = new Set(),
  preserveRequiredNullables = false,
  passthroughKeys: ReadonlySet<string> = new Set(),
): Record<string, unknown> {
  const filteredParams: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(params)) {
    if (passthroughKeys.has(key)) {
      if (value !== undefined) {
        filteredParams[key] = value;
      }
      continue;
    }
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' ||
            typeof item === 'number' ||
            typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (
      preserveRequiredNullables &&
      value === null &&
      requiredNullableKeys.has(key)
    ) {
      filteredParams[key] = null;
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
}

@Injectable({ providedIn: 'root' })
export class SwaggerPetstoreService {
  private readonly http = inject(HttpClient);
  private readonly baseUrl = inject(PETSTORE_API_BASE_URL);
  /**
   * @summary List all pets
   */
  listPets<TData = Pets>(
    params: ListPetsParams,
    options?: HttpClientBodyOptions,
  ): Observable<TData>;
  listPets<TData = Pets>(
    params: ListPetsParams,
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  listPets<TData = Pets>(
    params: ListPetsParams,
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  listPets<TData = Pets>(
    params: ListPetsParams,
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams(
      { ...params, ...options?.params },
      new Set<string>([]),
    );

    if (options?.observe === 'events') {
      return this.http.get<TData>(`${this.baseUrl}/pets`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`${this.baseUrl}/pets`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,
      });
    }

    return this.http.get<TData>(`${this.baseUrl}/pets`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
      params: filteredParams,
    });
  }

  /**
   * @summary Create a pet
   */
  createPets<TData = Pet>(
    createPetsBody: CreatePetsBody,
    params: CreatePetsParams,
    options?: HttpClientBodyOptions,
  ): Observable<TData>;
  createPets<TData = Pet>(
    createPetsBody: CreatePetsBody,
    params: CreatePetsParams,
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  createPets<TData = Pet>(
    createPetsBody: CreatePetsBody,
    params: CreatePetsParams,
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  createPets<TData = Pet>(
    createPetsBody: CreatePetsBody,
    params: CreatePetsParams,
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams(
      { ...params, ...options?.params },
      new Set<string>([]),
    );

    if (options?.observe === 'events') {
      return this.http.post<TData>(`${this.baseUrl}/pets`, createPetsBody, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,
      });
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(`${this.baseUrl}/pets`, createPetsBody, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,
      });
    }

    return this.http.post<TData>(`${this.baseUrl}/pets`, createPetsBody, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
      params: filteredParams,
    });
  }

  /**
   * @summary Info for a specific pet
   */
  showPetById<TData = Pet>(
    petId: string,
    options?: HttpClientBodyOptions,
  ): Observable<TData>;
  showPetById<TData = Pet>(
    petId: string,
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  showPetById<TData = Pet>(
    petId: string,
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  showPetById<TData = Pet>(
    petId: string,
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`${this.baseUrl}/pets/${petId}`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`${this.baseUrl}/pets/${petId}`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      });
    }

    return this.http.get<TData>(`${this.baseUrl}/pets/${petId}`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
    });
  }

  /**
   * @summary Deletes a specific pet
   */
  deletePetById<TData = void>(
    petId: string,
    options?: HttpClientBodyOptions,
  ): Observable<TData>;
  deletePetById<TData = void>(
    petId: string,
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  deletePetById<TData = void>(
    petId: string,
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  deletePetById<TData = void>(
    petId: string,
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(`${this.baseUrl}/pets/${petId}`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      });
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(`${this.baseUrl}/pets/${petId}`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      });
    }

    return this.http.delete<TData>(`${this.baseUrl}/pets/${petId}`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
    });
  }

  /**
   * @summary health check
   */
  healthCheck(options?: HttpClientBodyOptions): Observable<string>;
  healthCheck(options?: HttpClientEventOptions): Observable<HttpEvent<string>>;
  healthCheck(
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<string>>;
  healthCheck(
    options?: HttpClientObserveOptions,
  ): Observable<string | HttpEvent<string> | AngularHttpResponse<string>> {
    if (options?.observe === 'events') {
      return this.http.get(`${this.baseUrl}/health`, {
        responseType: 'text',
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }) as Observable<HttpEvent<string>>;
    }

    if (options?.observe === 'response') {
      return this.http.get(`${this.baseUrl}/health`, {
        responseType: 'text',
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }) as Observable<AngularHttpResponse<string>>;
    }

    return this.http.get(`${this.baseUrl}/health`, {
      responseType: 'text',
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
    }) as Observable<string>;
  }

  /**
   * @summary combinate nullable and $ref
   */
  showPetWithOwner<TData = PetWithTag>(
    petId: string,
    options?: HttpClientBodyOptions,
  ): Observable<TData>;
  showPetWithOwner<TData = PetWithTag>(
    petId: string,
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  showPetWithOwner<TData = PetWithTag>(
    petId: string,
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  showPetWithOwner<TData = PetWithTag>(
    petId: string,
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`${this.baseUrl}/pets/${petId}/owner`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`${this.baseUrl}/pets/${petId}/owner`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      });
    }

    return this.http.get<TData>(`${this.baseUrl}/pets/${petId}/owner`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
    });
  }
}
