/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Dates transform
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

export const UpdateAppointmentReminderBody = zod.object({
  remindOn: zod.date().optional(),
});

export type UpdateAppointmentReminderBody = zod.input<
  typeof UpdateAppointmentReminderBody
>;
export type UpdateAppointmentReminderBodyOutput = zod.output<
  typeof UpdateAppointmentReminderBody
>;
