/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Stream
 * OpenAPI spec version: 1.0.0
 */
import type { StreamEntry } from './model';

interface TypedResponse<T> extends Response {
  json(): Promise<T>;
}

function mergeOrvalHeaders(
  ...headers: Array<HeadersInit | undefined>
): Record<string, string> {
  const mergedHeaders: Record<string, string> = {};

  for (const header of headers) {
    new Headers(header).forEach((value, key) => {
      mergedHeaders[key] = value;
    });
  }

  return mergedHeaders;
}
export type streamResponse200 = {
  stream: TypedResponse<StreamEntry>;
  status: 200;
};

export type streamResponseSuccess = streamResponse200 & {
  headers: Headers;
};
export type streamResponse = streamResponseSuccess;

export const getStreamUrl = () => {
  return `/stream`;
};

/**
 * Stream results
 */
export const stream = async (
  options?: RequestInit,
): Promise<streamResponse> => {
  const stream = await fetch(getStreamUrl(), {
    ...options,
    method: 'GET',
    headers: mergeOrvalHeaders(
      { Accept: 'application/x-ndjson' },
      options?.headers,
    ),
  });

  return {
    status: stream.status,
    stream,
    headers: stream.headers,
  } as streamResponse;
};
