/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * API
 * OpenAPI spec version: V1
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { faker } from '@faker-js/faker';

import { HttpResponse, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import type { DescendantOne, DescendantTwo } from './model';

export type getPolymorphicResponseResponse200 = {
  data: DescendantOne | DescendantTwo;
  status: 200;
};

export type getPolymorphicResponseResponseSuccess =
  getPolymorphicResponseResponse200 & {
    headers: Headers;
  };
export type getPolymorphicResponseResponse =
  getPolymorphicResponseResponseSuccess;

export const getGetPolymorphicResponseUrl = () => {
  return `/demo`;
};

export const getPolymorphicResponse = async (
  options?: RequestInit,
): Promise<getPolymorphicResponseResponse> => {
  const res = await fetch(getGetPolymorphicResponseUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getPolymorphicResponseResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getPolymorphicResponseResponse;
};

export const getGetPolymorphicResponseQueryKey = () => {
  return [`/demo`] as const;
};

export const getGetPolymorphicResponseQueryOptions = <
  TData = Awaited<ReturnType<typeof getPolymorphicResponse>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getPolymorphicResponse>>,
      TError,
      TData
    >
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetPolymorphicResponseQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPolymorphicResponse>>
  > = ({ signal }) => getPolymorphicResponse({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPolymorphicResponse>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPolymorphicResponseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPolymorphicResponse>>
>;
export type GetPolymorphicResponseQueryError = unknown;

export function useGetPolymorphicResponse<
  TData = Awaited<ReturnType<typeof getPolymorphicResponse>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPolymorphicResponse>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPolymorphicResponse>>,
          TError,
          Awaited<ReturnType<typeof getPolymorphicResponse>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPolymorphicResponse<
  TData = Awaited<ReturnType<typeof getPolymorphicResponse>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPolymorphicResponse>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPolymorphicResponse>>,
          TError,
          Awaited<ReturnType<typeof getPolymorphicResponse>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPolymorphicResponse<
  TData = Awaited<ReturnType<typeof getPolymorphicResponse>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPolymorphicResponse>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetPolymorphicResponse<
  TData = Awaited<ReturnType<typeof getPolymorphicResponse>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPolymorphicResponse>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPolymorphicResponseQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetPolymorphicResponseResponseDescendantOneMock = (
  overrideResponse: Partial<DescendantOne> = {},
): DescendantOne => ({
  ...{
    ...{
      key: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      type: faker.helpers.arrayElement(['BOOLEAN', 'STRING'] as const),
    },
    ...{
      value: faker.datatype.boolean(),
      count: faker.number.int(),
      otherCount: faker.helpers.arrayElement([faker.number.int(), undefined]),
    },
  },
  ...overrideResponse,
});

export const getGetPolymorphicResponseResponseDescendantTwoMock = (
  overrideResponse: Partial<DescendantTwo> = {},
): DescendantTwo => ({
  ...{
    ...{
      key: faker.helpers.arrayElement([
        faker.string.alpha({ length: { min: 10, max: 20 } }),
        undefined,
      ]),
      type: faker.helpers.arrayElement(['BOOLEAN', 'STRING'] as const),
    },
    ...{ value: faker.string.alpha({ length: { min: 10, max: 20 } }) },
  },
  ...overrideResponse,
});

export const getGetPolymorphicResponseResponseMock = ():
  | DescendantOne
  | DescendantTwo =>
  faker.helpers.arrayElement([
    { ...getGetPolymorphicResponseResponseDescendantOneMock() },
    { ...getGetPolymorphicResponseResponseDescendantTwoMock() },
  ]);

export const getGetPolymorphicResponseMockHandler = (
  overrideResponse?:
    | DescendantOne
    | DescendantTwo
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) =>
        | Promise<DescendantOne | DescendantTwo>
        | DescendantOne
        | DescendantTwo),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/demo',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetPolymorphicResponseResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};
export const getApiMock = () => [getGetPolymorphicResponseMockHandler()];
