/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Nullable OneOf Enums
 * Test case for issue
 * OpenAPI spec version: 1.0.0
 */

export type BlankEnum = (typeof BlankEnum)[keyof typeof BlankEnum];

export const BlankEnum = {
  '': '',
} as const;
