/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Nullable OneOf Enums
 * Test case for issue
 * OpenAPI spec version: 1.0.0
 */
import { BlankEnum } from './blankEnum';
import { HelloEnum } from './helloEnum';
import { NotNullEnum } from './notNullEnum';

export const MixedEnumItemMixed = {
  ...HelloEnum,
  ...BlankEnum,
  ...NotNullEnum,
} as const;
