/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Nullable OneOf Enums
 * Test case for issue
 * OpenAPI spec version: 1.0.0
 */
import { NumberEnumNotNull } from './numberEnumNotNull';
import { NumberEnumNullable } from './numberEnumNullable';

export const MixedTypeEnumsNumberEnum = {
  ...NumberEnumNullable,
  ...NumberEnumNotNull,
} as const;
