/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AnyOf Schema
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

import type {
  AllOfPet,
  GetNotHasPropertiesWithAllOfPets200,
  ItemWithNullableRequired,
  Pet,
  PetDetail,
} from './model';

/**
 * @summary Create a pet
 */
export const createPets = (
  allOfPet: AllOfPet,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  const formData = new FormData();
  formData.append(`tag`, allOfPet.tag);

  return axios.post(`/pets`, formData, options);
};
export const getCreatePetsUrl = () => {
  return axios
    .create({
      baseURL: '',
      params: null,
    })
    .getUri({
      url: `/pets`,
      baseURL: '',
    });
};

/**
 * Not has properties with allOf pets.
 */
export const getNotHasPropertiesWithAllOfPets = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<GetNotHasPropertiesWithAllOfPets200>> => {
  return axios.get(`/not-has-properties-with-all-of-pets`, options);
};
export const getGetNotHasPropertiesWithAllOfPetsUrl = () => {
  return axios
    .create({
      baseURL: '',
      params: null,
    })
    .getUri({
      url: `/not-has-properties-with-all-of-pets`,
      baseURL: '',
    });
};

/**
 * Nested ref in allOf pets.
 */
export const getNestedRefInAllOfPets = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Pet & PetDetail>> => {
  return axios.get(`/rested-ref-in-all-of-pets`, options);
};
export const getGetNestedRefInAllOfPetsUrl = () => {
  return axios
    .create({
      baseURL: '',
      params: null,
    })
    .getUri({
      url: `/rested-ref-in-all-of-pets`,
      baseURL: '',
    });
};

/**
 * Test allOf with nullable and required fields.
 */
export const getItemsWithNullableRequired = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ItemWithNullableRequired[]>> => {
  return axios.get(`/items-with-nullable-required`, options);
};
export const getGetItemsWithNullableRequiredUrl = () => {
  return axios
    .create({
      baseURL: '',
      params: null,
    })
    .getUri({
      url: `/items-with-nullable-required`,
      baseURL: '',
    });
};

export type CreatePetsResult = AxiosResponse<void>;
export type GetNotHasPropertiesWithAllOfPetsResult =
  AxiosResponse<GetNotHasPropertiesWithAllOfPets200>;
export type GetNestedRefInAllOfPetsResult = AxiosResponse<Pet & PetDetail>;
export type GetItemsWithNullableRequiredResult = AxiosResponse<
  ItemWithNullableRequired[]
>;
