/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * orval enum value escaping repro
 * OpenAPI spec version: 1.0.0
 */

export type DirectoryPrefix =
  (typeof DirectoryPrefix)[keyof typeof DirectoryPrefix];

export const DirectoryPrefix = {
  'C:\\logs\\': 'C:\\logs\\',
  'C:\\tmp\\': 'C:\\tmp\\',
} as const;
