/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Orval Regression Tests
 * OpenAPI spec version: 0.0.0
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

export type Type = (typeof Type)[keyof typeof Type];

export const Type = {
  Type1: 'Type1',
  Type2: 'Type2',
} as const;

export interface Base {
  type: Type;
}

export type TypeObj1Type = (typeof TypeObj1Type)[keyof typeof TypeObj1Type];

export const TypeObj1Type = {
  Type1: 'Type1',
} as const;

export type TypeObj1 = Base & {
  moreProp?: string;
  type: TypeObj1Type;
};

export type TypeObj2Type = (typeof TypeObj2Type)[keyof typeof TypeObj2Type];

export const TypeObj2Type = {
  Type2: 'Type2',
} as const;

export type TypeObj2 = Base & {
  prop?: string;
  type: TypeObj2Type;
};

export type Resp = TypeObj1 | TypeObj2;

export const getTest = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Resp>> => {
  return axios.get(`/test`, options);
};

export type GetTestResult = AxiosResponse<Resp>;
