/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Issue 1026 - Vue Query header parameters
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/vue-query';
import type {
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query';

import axios from 'axios';
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from 'axios';

import { unref } from 'vue';
import type { MaybeRef } from 'vue';

import type { GetSomeEndpointHeaders, SomeEndpointResult } from './model';

/**
 * @summary Get something with header parameters
 */
export const getSomeEndpoint = (
  headers?: MaybeRef<GetSomeEndpointHeaders>,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<SomeEndpointResult>> => {
  headers = unref(headers);

  return axios.get(`/api/v1/someEndPoint`, {
    ...options,
    headers: { ...headers, ...options?.headers },
  });
};

export const getGetSomeEndpointQueryKey = () => {
  return ['api', 'v1', 'someEndPoint'] as const;
};

export const getGetSomeEndpointQueryOptions = <
  TData = Awaited<ReturnType<typeof getSomeEndpoint>>,
  TError = AxiosError<unknown>,
>(
  headers?: MaybeRef<GetSomeEndpointHeaders>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSomeEndpoint>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = getGetSomeEndpointQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSomeEndpoint>>> = ({
    signal,
  }) => getSomeEndpoint(headers, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSomeEndpoint>>,
    TError,
    TData
  >;
};

export type GetSomeEndpointQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSomeEndpoint>>
>;
export type GetSomeEndpointQueryError = AxiosError<unknown>;

/**
 * @summary Get something with header parameters
 */

export function useGetSomeEndpoint<
  TData = Awaited<ReturnType<typeof getSomeEndpoint>>,
  TError = AxiosError<unknown>,
>(
  headers?: MaybeRef<GetSomeEndpointHeaders>,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getSomeEndpoint>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetSomeEndpointQueryOptions(headers, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}
