/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Case Sensitive Schema Names
 * OpenAPI spec version: 1.0.0
 */
import type { Address2Kind } from './address2Kind';

export interface Address2 {
  kind: Address2Kind;
  prop1?: string;
  prop3: string;
}
