/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Issue 3027 - zod suffix ref regression
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const ExternalHolderSchema = zod.object({
  holderId: zod.string(),
});

export type ExternalHolderSchema = zod.input<typeof ExternalHolderSchema>;
export type ExternalHolderSchemaOutput = zod.output<
  typeof ExternalHolderSchema
>;
