/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */

export interface Error {
  /**
   * HTTP-like error code
   * @minimum 100
   * @maximum 600
   */
  code: number;
  /**
   * Human-readable error message
   * @minLength 1
   */
  message: string;
}
