/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

export type CatType = (typeof CatType)[keyof typeof CatType];

export const CatType = {
  cat: 'cat',
} as const;

export interface Cat {
  petsRequested?: number;
  type: CatType;
}

export interface Error {
  code: number;
  message: string;
}

/**
 * @summary health check
 */
export const healthCheck = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<string>> => {
  return axios.get(`/health`, {
    responseType: 'text',
    ...options,
  });
};

export type HealthCheckResult = AxiosResponse<string>;
