/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Issue 3574 - strict mock tags-split multi-schema
 * OpenAPI spec version: 1.0.0
 */
import { faker } from '@faker-js/faker';

import type { Owner, Pet } from '.';

export type KeysWithNull<O> = {
  [K in keyof O]-?: null extends O[K] ? K : never;
}[keyof O];

export type MockWithNullableOverrides<
  T,
  O extends Partial<T>,
  M extends Record<keyof T, unknown>,
> = Omit<M, Extract<KeysWithNull<O>, keyof T>> & {
  [K in Extract<KeysWithNull<O>, keyof T>]: M[K] | null;
};

export type PetMock = {
  [K in keyof Required<Pet>]: NonNullable<Required<Pet>[K]>;
};

export type OwnerMock = {
  [K in keyof Required<Owner>]: NonNullable<Required<Owner>[K]>;
};

export const getPetMock = <O extends Partial<Pet> = {}>(
  overrideResponse?: O,
): MockWithNullableOverrides<Pet, O, PetMock> =>
  ({
    id: faker.number.int(),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    ...overrideResponse,
  }) as MockWithNullableOverrides<Pet, O, PetMock>;

export const getOwnerMock = <O extends Partial<Owner> = {}>(
  overrideResponse?: O,
): MockWithNullableOverrides<Owner, O, OwnerMock> =>
  ({
    id: faker.number.int(),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    email: faker.string.alpha({ length: { min: 10, max: 20 } }),
    ...overrideResponse,
  }) as MockWithNullableOverrides<Owner, O, OwnerMock>;
