/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Angular httpResource both regression
 * OpenAPI spec version: 1.0.0
 */
import { HttpResponse, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import {
  getCreatePetsResponseMock,
  getListPetsResponseMock,
  getSearchPetsResponseMock,
} from '../../faker/pets/pets.faker';

import type { Pet, Pets } from '../../schemas';

export {
  getSearchPetsResponseMock,
  getListPetsResponseMock,
  getCreatePetsResponseMock,
} from '../../faker/pets/pets.faker';

export const getSearchPetsMockHandler = (
  overrideResponse?:
    | Pets
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<Pets> | Pets),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/search',
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getSearchPetsResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getListPetsMockHandler = (
  overrideResponse?:
    | Pets
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<Pets> | Pets),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/pets',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getListPetsResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getCreatePetsMockHandler = (
  overrideResponse?:
    | Pet
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<Pet> | Pet),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/pets',
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getCreatePetsResponseMock(),
        { status: 201 },
      );
    },
    options,
  );
};
export const getPetsMock = () => [
  getSearchPetsMockHandler(),
  getListPetsMockHandler(),
  getCreatePetsMockHandler(),
];
