/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Angular httpResource both regression
 * OpenAPI spec version: 1.0.0
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import type { Pet, Pets } from '../../schemas';

export const getSearchPetsResponseMock = (): Pets =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.number.int(),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    tag: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
  }));

export const getListPetsResponseMock = (): Pets =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    id: faker.number.int(),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    tag: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
  }));

export const getCreatePetsResponseMock = (
  overrideResponse: Partial<Extract<Pet, object>> = {},
): Pet => ({
  id: faker.number.int(),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  tag: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getSearchPetsMockHandler = (
  overrideResponse?:
    | Pets
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<Pets> | Pets),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/search',
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getSearchPetsResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getListPetsMockHandler = (
  overrideResponse?:
    | Pets
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<Pets> | Pets),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/pets',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getListPetsResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getCreatePetsMockHandler = (
  overrideResponse?:
    | Pet
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<Pet> | Pet),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/pets',
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getCreatePetsResponseMock(),
        { status: 201 },
      );
    },
    options,
  );
};
export const getPetsMock = () => [
  getSearchPetsMockHandler(),
  getListPetsMockHandler(),
  getCreatePetsMockHandler(),
];
