/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse,
  httpResource
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams,
  HttpResourceOptions,
  HttpResourceRef,
  HttpResourceRequest
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';
import type {
  ResourceStatus,
  Signal
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  CreatePetsBody,
  ListPetsParams,
  Pet,
  Pets,
  SearchPetsParams
} from '../../model';



export type OrvalHttpResourceOptions<TValue, TRaw = unknown, TOmitParse extends boolean = false> = TOmitParse extends true
  ? Omit<HttpResourceOptions<TValue, TRaw>, 'parse'>
  : HttpResourceOptions<TValue, TRaw>;
export type ListPetsAccept = typeof ListPetsAccept[keyof typeof ListPetsAccept];

export const ListPetsAccept = {
  application_json: 'application/json',
  application_xml: 'application/xml',
} as const;

export type ShowPetByIdAccept = typeof ShowPetByIdAccept[keyof typeof ShowPetByIdAccept];

export const ShowPetByIdAccept = {
  text_plain: 'text/plain',
  application_xml: 'application/xml',
  application_json: 'application/json',
} as const;

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function searchPetsResource(params: Signal<SearchPetsParams>,
    version: Signal<number> | undefined,
  options: OrvalHttpResourceOptions<Pets, unknown> & { defaultValue: NoInfer<Pets> }): HttpResourceRef<Pets>;
export function searchPetsResource(params: Signal<SearchPetsParams>,
    version?: Signal<number>,
  options?: OrvalHttpResourceOptions<Pets, unknown>): HttpResourceRef<Pets | undefined>;
export function searchPetsResource(params: Signal<SearchPetsParams>,
    version?: Signal<number>,
  options?: OrvalHttpResourceOptions<Pets, unknown>): HttpResourceRef<Pets | undefined> {
  return httpResource<Pets>(() => {
    
    const request = ({
      url: `/v${version?.() ?? 1}/search`,
      params: (() => {
  const requiredNullableParamKeys = new Set<string>(["requirednullableString","requirednullableStringTwo"]);
  const filteredParams = {} as Record<string, string | number | boolean | null | Array<string | number | boolean>>;
  for (const [key, value] of Object.entries(params?.() ?? {})) {
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' ||
            typeof item === 'number' ||
            typeof item === 'boolean'),
          ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (value === null && requiredNullableParamKeys.has(key)) {
      filteredParams[key] = value;
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value as string | number | boolean;
    }
  }
  return filteredParams as unknown as Record<string, string | number | boolean | Array<string | number | boolean>>;
})()
    });
    return request;
  }, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function listPetsResource(accept: 'application/json',
    params?: Signal<ListPetsParams>,
    version?: Signal<number>,
    options?: OrvalHttpResourceOptions<Pets | string, unknown>): HttpResourceRef<Pets | undefined>;
export function listPetsResource(accept: 'application/xml',
    params?: Signal<ListPetsParams>,
    version?: Signal<number>,
    options?: OrvalHttpResourceOptions<Pets | string, unknown>): HttpResourceRef<string | undefined>;
export function listPetsResource(
    accept?: ListPetsAccept,
    params?: Signal<ListPetsParams>,
    version?: Signal<number>,
    options?: OrvalHttpResourceOptions<Pets | string, unknown>
  ): HttpResourceRef<Pets | string | undefined>;
export function listPetsResource(
    accept: ListPetsAccept = 'application/json',
    params?: Signal<ListPetsParams>,
    version?: Signal<number>,
    options?: OrvalHttpResourceOptions<Pets | string, unknown>
): HttpResourceRef<Pets | string | undefined> {
  return (() => {
    
    const request = ({
      url: `/v${version?.() ?? 1}/pets`,
      params: (() => {
  const requiredNullableParamKeys = new Set<string>([]);
  const filteredParams = {} as Record<string, string | number | boolean | null | Array<string | number | boolean>>;
  for (const [key, value] of Object.entries(params?.() ?? {})) {
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' ||
            typeof item === 'number' ||
            typeof item === 'boolean'),
          ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (value === null && requiredNullableParamKeys.has(key)) {
      filteredParams[key] = value;
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value as string | number | boolean;
    }
  }
  return filteredParams as unknown as Record<string, string | number | boolean | Array<string | number | boolean>>;
})()
    });
    const normalizedRequest: HttpResourceRequest = typeof request === 'string' ? { url: request } : request;
    const headers = normalizedRequest.headers instanceof HttpHeaders
      ? normalizedRequest.headers.set('Accept', accept)
      : { ...(normalizedRequest.headers ?? {}), Accept: accept };

    if (accept.includes('json') || accept.includes('+json')) {
      return httpResource<Pets>(() => ({
        ...normalizedRequest,
        headers,
      }), options as unknown as OrvalHttpResourceOptions<Pets, unknown>);
    }

    if (accept.startsWith('text/') || accept.includes('xml')) {
      return httpResource.text<string>(() => ({
        ...normalizedRequest,
        headers,
      }), options as unknown as OrvalHttpResourceOptions<string, string>);
    }

    return httpResource.text<string>(() => ({
      ...normalizedRequest,
      headers,
    }), options as unknown as OrvalHttpResourceOptions<string, string>);
  })();
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function showPetByIdResource(petId: Signal<string>,
    accept: 'text/plain',
    version?: Signal<number>,
    options?: OrvalHttpResourceOptions<string | Pet, unknown>): HttpResourceRef<string | undefined>;
export function showPetByIdResource(petId: Signal<string>,
    accept: 'application/xml',
    version?: Signal<number>,
    options?: OrvalHttpResourceOptions<string | Pet, unknown>): HttpResourceRef<string | undefined>;
export function showPetByIdResource(petId: Signal<string>,
    accept: 'application/json',
    version?: Signal<number>,
    options?: OrvalHttpResourceOptions<string | Pet, unknown>): HttpResourceRef<Pet | undefined>;
export function showPetByIdResource(
    petId: Signal<string>,
    accept?: ShowPetByIdAccept,
    version?: Signal<number>,
    options?: OrvalHttpResourceOptions<string | Pet, unknown>
  ): HttpResourceRef<string | Pet | undefined>;
export function showPetByIdResource(
    petId: Signal<string>,
    accept: ShowPetByIdAccept = 'application/json',
    version?: Signal<number>,
    options?: OrvalHttpResourceOptions<string | Pet, unknown>
): HttpResourceRef<string | Pet | undefined> {
  return (() => {
    
    const request = `/v${version?.() ?? 1}/pets/${petId()}`;
    const normalizedRequest: HttpResourceRequest = typeof request === 'string' ? { url: request } : request;
    const headers = normalizedRequest.headers instanceof HttpHeaders
      ? normalizedRequest.headers.set('Accept', accept)
      : { ...(normalizedRequest.headers ?? {}), Accept: accept };

    if (accept.includes('json') || accept.includes('+json')) {
      return httpResource<Pet>(() => ({
        ...normalizedRequest,
        headers,
      }), options as unknown as OrvalHttpResourceOptions<Pet, unknown>);
    }

    if (accept.startsWith('text/') || accept.includes('xml')) {
      return httpResource.text<string>(() => ({
        ...normalizedRequest,
        headers,
      }), options as unknown as OrvalHttpResourceOptions<string, string>);
    }

    return httpResource.text<string>(() => ({
      ...normalizedRequest,
      headers,
    }), options as unknown as OrvalHttpResourceOptions<string, string>);
  })();
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function showPetTextResource(petId: Signal<string>,
    version: Signal<number> | undefined,
  options: OrvalHttpResourceOptions<string, string> & { defaultValue: NoInfer<string> }): HttpResourceRef<string>;
export function showPetTextResource(petId: Signal<string>,
    version?: Signal<number>,
  options?: OrvalHttpResourceOptions<string, string>): HttpResourceRef<string | undefined>;
export function showPetTextResource(petId: Signal<string>,
    version?: Signal<number>,
  options?: OrvalHttpResourceOptions<string, string>): HttpResourceRef<string | undefined> {
  return httpResource.text<string>(() => `/v${version?.() ?? 1}/pets/${petId()}/text`, options);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function downloadFileResource(petId: Signal<number>,
    version: Signal<number> | undefined,
  options: OrvalHttpResourceOptions<Blob, Blob> & { defaultValue: NoInfer<Blob> }): HttpResourceRef<Blob>;
export function downloadFileResource(petId: Signal<number>,
    version?: Signal<number>,
  options?: OrvalHttpResourceOptions<Blob, Blob>): HttpResourceRef<Blob | undefined>;
export function downloadFileResource(petId: Signal<number>,
    version?: Signal<number>,
  options?: OrvalHttpResourceOptions<Blob, Blob>): HttpResourceRef<Blob | undefined> {
  return httpResource.blob<Blob>(() => `/v${version?.() ?? 1}/pet/${petId()}/downloadImage`, options);
}


interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};





@Injectable({ providedIn: 'root' })
export class PetsService {
  private readonly http = inject(HttpClient);

 createPets<TData = void>(createPetsBody: CreatePetsBody,
    version?: number, options?: HttpClientBodyOptions): Observable<TData>;
 createPets<TData = void>(createPetsBody: CreatePetsBody,
    version?: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 createPets<TData = void>(createPetsBody: CreatePetsBody,
    version?: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  createPets<TData = void>(
    createPetsBody: CreatePetsBody,
    version: number = 1, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/v${version}/pets`,
      createPetsBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/v${version}/pets`,
      createPetsBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/v${version}/pets`,
      createPetsBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }

 uploadFile<TData = void>(petId: number,
    uploadFileBody: Blob,
    version?: number, options?: HttpClientBodyOptions): Observable<TData>;
 uploadFile<TData = void>(petId: number,
    uploadFileBody: Blob,
    version?: number, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 uploadFile<TData = void>(petId: number,
    uploadFileBody: Blob,
    version?: number, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  uploadFile<TData = void>(
    petId: number,
    uploadFileBody: Blob,
    version: number = 1, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
      `/v${version}/pet/${petId}/uploadImage`,
      uploadFileBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
      `/v${version}/pet/${petId}/uploadImage`,
      uploadFileBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.post<TData>(
      `/v${version}/pet/${petId}/uploadImage`,
      uploadFileBody,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }

};

export type SearchPetsResourceResult = NonNullable<Pets>
export type ListPetsResourceResult = NonNullable<Pets | string>
export type ShowPetByIdResourceResult = NonNullable<string | Pet>
export type ShowPetTextResourceResult = NonNullable<string>
export type DownloadFileResourceResult = NonNullable<Blob>








/**
 * Utility type for httpResource results with status tracking.
 * Inspired by @angular-architects/ngrx-toolkit withResource pattern.
 *
 * Uses `globalThis.Error` to avoid collision with API model types named `Error`.
 */
export interface ResourceState<T> {
  readonly value: Signal<T | undefined>;
  readonly status: Signal<ResourceStatus>;
  readonly error: Signal<globalThis.Error | undefined>;
  readonly isLoading: Signal<boolean>;
  readonly hasValue: () => boolean;
  readonly reload: () => boolean;
}

/**
 * Wraps an HttpResourceRef to expose a consistent ResourceState interface.
 * Useful when integrating with NgRx SignalStore via withResource().
 */
export function toResourceState<T>(ref: HttpResourceRef<T>): ResourceState<T> {
  return {
    value: ref.value,
    status: ref.status,
    error: ref.error,
    isLoading: ref.isLoading,
    hasValue: () => ref.hasValue(),
    reload: () => ref.reload(),
  };
}
