/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Infinite Query Require Param
 * OpenAPI spec version: 1.0.0
 */
import type { DashboardPageDtoItemsItem } from './dashboardPageDtoItemsItem';

export interface DashboardPageDto {
  page?: number;
  pageSize?: number;
  items?: DashboardPageDtoItemsItem[];
}
