/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Union enum ref mock
 * A parent schema references a string enum component via $ref while
 * enumGenerationType is 'union'. The union renders the enum as a pure type
 * (no runtime value), so the generated faker/msw mock must inline the enum
 * values instead of calling Object.values(EnumName) — which would fail tsc
 * with TS2693 (#3690).
 *
 * OpenAPI spec version: 1.0.0
 */
import type { DisplayColor } from './displayColor';

export interface DisplayValueDto {
  color?: DisplayColor;
  value: string;
}
