/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Swagger Petstore - OpenAPI 3.0
 * This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
 * Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
 * You can now help us improve the API whether it's by making changes to the definition itself or to the code.
 * That way, with time, we can improve the API in general, and expose some of the new features in OAS3.
 *
 * Some useful links:
 * - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
 * - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 * OpenAPI spec version: 1.0.27-SNAPSHOT
 */
import type {
  FindPetsByStatusParams,
  FindPetsByTagsParams,
  UpdatePetWithFormParams,
  LoginUserParams,
} from './http-schemas';

import {
  findPetsByStatus,
  findPetsByTags,
  getPetById,
  updatePetWithForm,
  deletePet,
  getInventory,
  getOrderById,
  deleteOrder,
  loginUser,
  logoutUser,
  getUserByName,
  deleteUser,
} from './http-client';

import { customHandler } from '../custom-handler';
import type { RequestHandlerExtra } from '@modelcontextprotocol/sdk/shared/protocol.js';
import type {
  ServerNotification,
  ServerRequest,
} from '@modelcontextprotocol/sdk/types.js';

/**
 * Multiple status values can be provided with comma separated strings.
 * @summary Finds Pets by status.
 */

export type findPetsByStatusArgs = {
  queryParams: FindPetsByStatusParams;
};

export const findPetsByStatusHandler = async (
  args: findPetsByStatusArgs,
  options?: RequestInit,
  ctx?: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const fetcher = (overrides?: RequestInit) => {
    const headers = new Headers(options?.headers);
    new Headers(overrides?.headers).forEach((value, name) =>
      headers.set(name, value),
    );

    return findPetsByStatus(args.queryParams, {
      ...options,
      ...overrides,
      headers,
    });
  };

  return customHandler(fetcher, ctx);
};

/**
 * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
 * @summary Finds Pets by tags.
 */

export type findPetsByTagsArgs = {
  queryParams: FindPetsByTagsParams;
};

export const findPetsByTagsHandler = async (
  args: findPetsByTagsArgs,
  options?: RequestInit,
  ctx?: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const fetcher = (overrides?: RequestInit) => {
    const headers = new Headers(options?.headers);
    new Headers(overrides?.headers).forEach((value, name) =>
      headers.set(name, value),
    );

    return findPetsByTags(args.queryParams, {
      ...options,
      ...overrides,
      headers,
    });
  };

  return customHandler(fetcher, ctx);
};

/**
 * Returns a single pet.
 * @summary Find pet by ID.
 */

export type getPetByIdArgs = {
  pathParams: {
    petId: number;
  };
};

export const getPetByIdHandler = async (
  args: getPetByIdArgs,
  options?: RequestInit,
  ctx?: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const fetcher = (overrides?: RequestInit) => {
    const headers = new Headers(options?.headers);
    new Headers(overrides?.headers).forEach((value, name) =>
      headers.set(name, value),
    );

    return getPetById(args.pathParams.petId, {
      ...options,
      ...overrides,
      headers,
    });
  };

  return customHandler(fetcher, ctx);
};

/**
 * Updates a pet resource based on the form data.
 * @summary Updates a pet in the store with form data.
 */

export type updatePetWithFormArgs = {
  pathParams: {
    petId: number;
  };
  queryParams: UpdatePetWithFormParams;
};

export const updatePetWithFormHandler = async (
  args: updatePetWithFormArgs,
  options?: RequestInit,
  ctx?: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const fetcher = (overrides?: RequestInit) => {
    const headers = new Headers(options?.headers);
    new Headers(overrides?.headers).forEach((value, name) =>
      headers.set(name, value),
    );

    return updatePetWithForm(args.pathParams.petId, args.queryParams, {
      ...options,
      ...overrides,
      headers,
    });
  };

  return customHandler(fetcher, ctx);
};

/**
 * Delete a pet.
 * @summary Deletes a pet.
 */

export type deletePetArgs = {
  pathParams: {
    petId: number;
  };
};

export const deletePetHandler = async (
  args: deletePetArgs,
  options?: RequestInit,
  ctx?: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const fetcher = (overrides?: RequestInit) => {
    const headers = new Headers(options?.headers);
    new Headers(overrides?.headers).forEach((value, name) =>
      headers.set(name, value),
    );

    return deletePet(args.pathParams.petId, {
      ...options,
      ...overrides,
      headers,
    });
  };

  return customHandler(fetcher, ctx);
};

/**
 * Returns a map of status codes to quantities.
 * @summary Returns pet inventories by status.
 */

export const getInventoryHandler = async (
  options?: RequestInit,
  ctx?: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const fetcher = (overrides?: RequestInit) => {
    const headers = new Headers(options?.headers);
    new Headers(overrides?.headers).forEach((value, name) =>
      headers.set(name, value),
    );

    return getInventory({ ...options, ...overrides, headers });
  };

  return customHandler(fetcher, ctx);
};

/**
 * For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
 * @summary Find purchase order by ID.
 */

export type getOrderByIdArgs = {
  pathParams: {
    orderId: number;
  };
};

export const getOrderByIdHandler = async (
  args: getOrderByIdArgs,
  options?: RequestInit,
  ctx?: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const fetcher = (overrides?: RequestInit) => {
    const headers = new Headers(options?.headers);
    new Headers(overrides?.headers).forEach((value, name) =>
      headers.set(name, value),
    );

    return getOrderById(args.pathParams.orderId, {
      ...options,
      ...overrides,
      headers,
    });
  };

  return customHandler(fetcher, ctx);
};

/**
 * For valid response try integer IDs with value < 1000. Anything above 1000 or non-integers will generate API errors.
 * @summary Delete purchase order by identifier.
 */

export type deleteOrderArgs = {
  pathParams: {
    orderId: number;
  };
};

export const deleteOrderHandler = async (
  args: deleteOrderArgs,
  options?: RequestInit,
  ctx?: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const fetcher = (overrides?: RequestInit) => {
    const headers = new Headers(options?.headers);
    new Headers(overrides?.headers).forEach((value, name) =>
      headers.set(name, value),
    );

    return deleteOrder(args.pathParams.orderId, {
      ...options,
      ...overrides,
      headers,
    });
  };

  return customHandler(fetcher, ctx);
};

/**
 * Log into the system.
 * @summary Logs user into the system.
 */

export type loginUserArgs = {
  queryParams: LoginUserParams;
};

export const loginUserHandler = async (
  args: loginUserArgs,
  options?: RequestInit,
  ctx?: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const fetcher = (overrides?: RequestInit) => {
    const headers = new Headers(options?.headers);
    new Headers(overrides?.headers).forEach((value, name) =>
      headers.set(name, value),
    );

    return loginUser(args.queryParams, { ...options, ...overrides, headers });
  };

  return customHandler(fetcher, ctx);
};

/**
 * Log user out of the system.
 * @summary Logs out current logged in user session.
 */

export const logoutUserHandler = async (
  options?: RequestInit,
  ctx?: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const fetcher = (overrides?: RequestInit) => {
    const headers = new Headers(options?.headers);
    new Headers(overrides?.headers).forEach((value, name) =>
      headers.set(name, value),
    );

    return logoutUser({ ...options, ...overrides, headers });
  };

  return customHandler(fetcher, ctx);
};

/**
 * Get user detail based on username.
 * @summary Get user by user name.
 */

export type getUserByNameArgs = {
  pathParams: {
    username: string;
  };
};

export const getUserByNameHandler = async (
  args: getUserByNameArgs,
  options?: RequestInit,
  ctx?: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const fetcher = (overrides?: RequestInit) => {
    const headers = new Headers(options?.headers);
    new Headers(overrides?.headers).forEach((value, name) =>
      headers.set(name, value),
    );

    return getUserByName(args.pathParams.username, {
      ...options,
      ...overrides,
      headers,
    });
  };

  return customHandler(fetcher, ctx);
};

/**
 * This can only be done by the logged in user.
 * @summary Delete user resource.
 */

export type deleteUserArgs = {
  pathParams: {
    username: string;
  };
};

export const deleteUserHandler = async (
  args: deleteUserArgs,
  options?: RequestInit,
  ctx?: RequestHandlerExtra<ServerRequest, ServerNotification>,
) => {
  const fetcher = (overrides?: RequestInit) => {
    const headers = new Headers(options?.headers);
    new Headers(overrides?.headers).forEach((value, name) =>
      headers.set(name, value),
    );

    return deleteUser(args.pathParams.username, {
      ...options,
      ...overrides,
      headers,
    });
  };

  return customHandler(fetcher, ctx);
};
