/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const Cat = zod.object({
  "petsRequested": zod.number().optional(),
  "type": zod.enum(['cat'])
})

export type Cat = zod.infer<typeof Cat>;
