/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Binary Request Body
 * Raw binary request bodies
 * OpenAPI spec version: 1.0.0
 */
export type replaceLotteryLogoResponse204 = {
  data: void;
  status: 204;
};

export type replaceLotteryLogoResponseSuccess =
  replaceLotteryLogoResponse204 & {
    headers: Headers;
  };
export type replaceLotteryLogoResponse = replaceLotteryLogoResponseSuccess;

export const getReplaceLotteryLogoUrl = (id: number) => {
  return `/lottery/${id}/logo`;
};

/**
 * This endpoint sets or replaces lottery logo.
 * @summary Replace lottery logo
 */
export const replaceLotteryLogo = async (
  id: number,
  replaceLotteryLogoBody: Blob,
  options?: RequestInit,
): Promise<replaceLotteryLogoResponse> => {
  const res = await fetch(getReplaceLotteryLogoUrl(id), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'image/png', ...options?.headers },
    body: replaceLotteryLogoBody,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: replaceLotteryLogoResponse['data'] = body
    ? JSON.parse(body)
    : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as replaceLotteryLogoResponse;
};
