/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Const
 * OpenAPI spec version: 1.0.0
 */

export const StringConstValue = {
  value: 'string',
  valueWithoutType: 'string',
  /** @nullable */
  valueNullable: 'string',
} as const;
export type StringConst = typeof StringConstValue;
