/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * MSW Problem Details Content-Type
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from 'axios';

import type { Pet, Problem } from './model';

import { faker } from '@faker-js/faker';

import { HttpResponse, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

export const getMSWProblemDetailsContentType = (
  axiosInstance: AxiosInstance = axios,
) => {
  /**
   * @summary Get a pet or a Problem Details error
   */
  const getPet = (
    petId: number,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<Pet>> => {
    return axiosInstance.get(`/pets/${petId}`, options);
  };

  return { getPet };
};
export type GetPetResult = AxiosResponse<Pet>;

export const getGetPetResponseMock = (
  overrideResponse: Partial<Extract<Pet, object>> = {},
): Pet => ({
  id: faker.number.int(),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  ...overrideResponse,
});

export const getGetPetResponseMock200 = (
  overrideResponse: Partial<Extract<Pet, object>> = {},
): Pet => ({
  id: faker.number.int(),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  ...overrideResponse,
});

export const getGetPetResponseMock404 = (
  overrideResponse: Partial<Extract<Problem, object>> = {},
): Problem => ({
  type: faker.string.alpha({ length: { min: 10, max: 20 } }),
  title: faker.string.alpha({ length: { min: 10, max: 20 } }),
  status: faker.number.int(),
  detail: faker.string.alpha({ length: { min: 10, max: 20 } }),
  ...overrideResponse,
});

export const getGetPetMockHandler = (
  overrideResponse?:
    | Pet
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<Pet> | Pet),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/pets/:petId',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetPetResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetPetMockHandler200 = (
  overrideResponse?:
    | Pet
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<Pet> | Pet),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/pets/:petId',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetPetResponseMock200(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getGetPetMockHandler404 = (
  overrideResponse?:
    | Problem
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<Problem> | Problem),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/pets/:petId',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetPetResponseMock404(),
        {
          status: 404,
          headers: { 'Content-Type': 'application/problem+json' },
        },
      );
    },
    options,
  );
};
export const getMSWProblemDetailsContentTypeMock = () => [
  getGetPetMockHandler(),
];
