/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

import type {
  CreatePetsBody,
  CreatePetsParams,
  CreatePetsPathParameters,
  DeletePetByIdPathParameters,
  HealthCheckPathParameters,
  ListPetsParams,
  ListPetsPathParameters,
  Pet,
  PetWithTag,
  Pets,
  ShowPetByIdPathParameters,
  ShowPetWithOwnerPathParameters,
} from './model';

/**
 * @summary List all pets
 */
export const listPets = (
  { version = 1 }: ListPetsPathParameters = {},
  params: ListPetsParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Pets>> => {
  return axios.get(`/v${version}/pets`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getListPetsUrl = (
  { version = 1 }: ListPetsPathParameters = {},
  params: ListPetsParams,
) => {
  return axios
    .create({
      baseURL: '',
      params: null,
    })
    .getUri({
      url: `/v${version}/pets`,
      baseURL: '',
      params,
    });
};

/**
 * @summary Create a pet
 */
export const createPets = (
  { version = 1 }: CreatePetsPathParameters = {},
  createPetsBody: CreatePetsBody,
  params: CreatePetsParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Pet>> => {
  return axios.post(`/v${version}/pets`, createPetsBody, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getCreatePetsUrl = (
  { version = 1 }: CreatePetsPathParameters = {},
  params: CreatePetsParams,
) => {
  return axios
    .create({
      baseURL: '',
      params: null,
    })
    .getUri({
      url: `/v${version}/pets`,
      baseURL: '',
      params,
    });
};

/**
 * @summary Info for a specific pet
 */
export const showPetById = (
  { version = 1, petId }: ShowPetByIdPathParameters,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Pet>> => {
  return axios.get(`/v${version}/pets/${petId}`, options);
};
export const getShowPetByIdUrl = ({
  version = 1,
  petId,
}: ShowPetByIdPathParameters) => {
  return axios
    .create({
      baseURL: '',
      params: null,
    })
    .getUri({
      url: `/v${version}/pets/${petId}`,
      baseURL: '',
    });
};

/**
 * @summary Deletes a specific pet
 */
export const deletePetById = (
  { version = 1, petId }: DeletePetByIdPathParameters,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.delete(`/v${version}/pets/${petId}`, options);
};
export const getDeletePetByIdUrl = ({
  version = 1,
  petId,
}: DeletePetByIdPathParameters) => {
  return axios
    .create({
      baseURL: '',
      params: null,
    })
    .getUri({
      url: `/v${version}/pets/${petId}`,
      baseURL: '',
    });
};

/**
 * @summary health check
 */
export const healthCheck = (
  { version = 1 }: HealthCheckPathParameters = {},
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<string>> => {
  return axios.get(`/v${version}/health`, {
    responseType: 'text',
    ...options,
  });
};
export const getHealthCheckUrl = ({
  version = 1,
}: HealthCheckPathParameters = {}) => {
  return axios
    .create({
      baseURL: '',
      params: null,
    })
    .getUri({
      url: `/v${version}/health`,
      baseURL: '',
    });
};

/**
 * @summary combinate nullable and $ref
 */
export const showPetWithOwner = (
  { version = 1, petId }: ShowPetWithOwnerPathParameters,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<PetWithTag>> => {
  return axios.get(`/v${version}/pets/${petId}/owner`, options);
};
export const getShowPetWithOwnerUrl = ({
  version = 1,
  petId,
}: ShowPetWithOwnerPathParameters) => {
  return axios
    .create({
      baseURL: '',
      params: null,
    })
    .getUri({
      url: `/v${version}/pets/${petId}/owner`,
      baseURL: '',
    });
};

export type ListPetsResult = AxiosResponse<Pets>;
export type CreatePetsResult = AxiosResponse<Pet>;
export type ShowPetByIdResult = AxiosResponse<Pet>;
export type DeletePetByIdResult = AxiosResponse<void>;
export type HealthCheckResult = AxiosResponse<string>;
export type ShowPetWithOwnerResult = AxiosResponse<PetWithTag>;
