/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * Issue 3663 - allOf constraint-only required overlay
 * OpenAPI spec version: 1.0.0
 */
export interface FooPartial {
  readonly id?: string;
  name?: string;
  detail?: string;
}

export interface FooRequiredFields {}

export type Foo = FooPartial &
  FooRequiredFields &
  Required<Pick<FooPartial & FooRequiredFields, 'id' | 'name'>>;

export type BarInline = FooPartial &
  unknown &
  Required<Pick<FooPartial & unknown, 'id' | 'name'>>;

export type getFooResponse200 = {
  data: Foo;
  status: 200;
};

export type getFooResponseSuccess = getFooResponse200 & {
  headers: Headers;
};
export type getFooResponse = getFooResponseSuccess;

export const getGetFooUrl = () => {
  return `/foo`;
};

export const getFoo = async (
  options?: RequestInit,
): Promise<getFooResponse> => {
  const res = await fetch(getGetFooUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getFooResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getFooResponse;
};

export type getBarResponse200 = {
  data: BarInline;
  status: 200;
};

export type getBarResponseSuccess = getBarResponse200 & {
  headers: Headers;
};
export type getBarResponse = getBarResponseSuccess;

export const getGetBarUrl = () => {
  return `/bar`;
};

export const getBar = async (
  options?: RequestInit,
): Promise<getBarResponse> => {
  const res = await fetch(getGetBarUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getBarResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as getBarResponse;
};
