/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Multi query params
 * OpenAPI spec version: 1.0.0
 */

export type GetUsersUserIdOrdersStatus =
  (typeof GetUsersUserIdOrdersStatus)[keyof typeof GetUsersUserIdOrdersStatus];

export const GetUsersUserIdOrdersStatus = {
  pending: 'pending',
  completed: 'completed',
  cancelled: 'cancelled',
} as const;
