/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Infinite Query Require Param
 * OpenAPI spec version: 1.0.0
 */

export type ListDashboardsParams = {
  /**
   * @minimum 1
   */
  page?: number;
  /**
   * @minimum 1
   * @maximum 200
   */
  pageSize?: number;
};
