/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * Orval MRE
 * Orval MRE
 * OpenAPI spec version: 1.0.0
 */
import type { PointInFutureRelativeKind } from './pointInFutureRelativeKind';

export interface PointInFutureRelative {
  kind: PointInFutureRelativeKind;
  value: string;
}
