/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * issue-607
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type { ApiResponse } from './model';

export type optionsResponse200 = {
  data: ApiResponse;
  status: 200;
};

export type optionsResponseSuccess = optionsResponse200 & {
  headers: Headers;
};
export type optionsResponse = optionsResponseSuccess;

export const getOptionsUrl = (petId: number) => {
  return `/pet/${petId}/options`;
};

export const options = async (
  petId: number,
  options?: RequestInit,
): Promise<optionsResponse> => {
  const res = await fetch(getOptionsUrl(petId), {
    ...options,
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: optionsResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as optionsResponse;
};

const optionsRequestFn = options;
export const getOptionsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof optionsRequestFn>>,
    TError,
    { petId: number },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof optionsRequestFn>>,
  TError,
  { petId: number },
  TContext
> => {
  const mutationKey = ['options'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof optionsRequestFn>>,
    { petId: number }
  > = (props) => {
    const { petId } = props ?? {};

    return optionsRequestFn(petId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type OptionsMutationResult = NonNullable<
  Awaited<ReturnType<typeof optionsRequestFn>>
>;

export type OptionsMutationError = unknown;

export const useOptions = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof optionsRequestFn>>,
      TError,
      { petId: number },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof optionsRequestFn>>,
  TError,
  { petId: number },
  TContext
> => {
  return useMutation(getOptionsMutationOptions(options), queryClient);
};
