/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Swagger Delay in name
 * OpenAPI spec version: 1.0.0
 */

export type DelayInNameParams = {
  /**
   * How many items to return at one time (max 100)
   */
  limit?: string;
};
