/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';

import { customServer } from '../../../mutators/mcp-custom-server';

import {
  listPetsHandler,
  createPetsHandler,
  showPetByIdHandler,
  deletePetByIdHandler,
  healthCheckHandler,
  showPetWithOwnerHandler,
} from './handlers';
import {
  ListPetsQueryParams,
  CreatePetsQueryParams,
  CreatePetsBody,
  ShowPetByIdParams,
  DeletePetByIdParams,
  ShowPetWithOwnerParams,
} from './tool-schemas.zod';

const createMcpServer = () => {
  const server = new McpServer({
    name: 'swaggerPetstoreServer',
    version: '1.0.0',
  });

  server.tool(
    'listPets',
    'List all pets',
    {
      queryParams: ListPetsQueryParams,
    },
    listPetsHandler,
  );

  server.tool(
    'createPets',
    'Create a pet',
    {
      queryParams: CreatePetsQueryParams,
      bodyParams: CreatePetsBody,
    },
    createPetsHandler,
  );

  server.tool(
    'showPetById',
    'Info for a specific pet',
    {
      pathParams: ShowPetByIdParams,
    },
    showPetByIdHandler,
  );

  server.tool(
    'deletePetById',
    'Deletes a specific pet',
    {
      pathParams: DeletePetByIdParams,
    },
    deletePetByIdHandler,
  );

  server.tool('healthCheck', 'health check', healthCheckHandler);

  server.tool(
    'showPetWithOwner',
    'combinate nullable and $ref',
    {
      pathParams: ShowPetWithOwnerParams,
    },
    showPetWithOwnerHandler,
  );

  return server;
};

customServer(createMcpServer);
