/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreatePetsBody,
  Error,
  Pet,
  UploadPetContentBody,
  UploadPetContentRefBody,
} from './model';

import { faker } from '@faker-js/faker';

import { HttpResponse, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx =
  | 400
  | 401
  | 402
  | 403
  | 404
  | 405
  | 406
  | 407
  | 408
  | 409
  | 410
  | 411
  | 412
  | 413
  | 414
  | 415
  | 416
  | 417
  | 418
  | 419
  | 420
  | 421
  | 422
  | 423
  | 424
  | 426
  | 428
  | 429
  | 431
  | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes =
  | HTTPStatusCode1xx
  | HTTPStatusCode2xx
  | HTTPStatusCode3xx
  | HTTPStatusCode4xx
  | HTTPStatusCode5xx;

export type createPetsResponse200 = {
  data: Pet;
  status: 200;
};

export type createPetsResponseDefault = {
  data: Error;
  status: Exclude<HTTPStatusCodes, 200>;
};

export type createPetsResponseSuccess = createPetsResponse200 & {
  headers: Headers;
};
export type createPetsResponseError = createPetsResponseDefault & {
  headers: Headers;
};

export type createPetsResponse =
  | createPetsResponseSuccess
  | createPetsResponseError;

export const getCreatePetsUrl = () => {
  return `/pets`;
};

/**
 * @summary Create a pet
 */
export const createPets = async (
  createPetsBody: CreatePetsBody,
  options?: RequestInit,
): Promise<createPetsResponse> => {
  const formUrlEncoded = new URLSearchParams();
  formUrlEncoded.append(`name`, createPetsBody.name);
  formUrlEncoded.append(`tag`, createPetsBody.tag);

  const res = await fetch(getCreatePetsUrl(), {
    ...options,
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options?.headers,
    },
    body: formUrlEncoded,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createPetsResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createPetsResponse;
};

export type uploadPetContentResponse200 = {
  data: Pet;
  status: 200;
};

export type uploadPetContentResponseDefault = {
  data: Error;
  status: Exclude<HTTPStatusCodes, 200>;
};

export type uploadPetContentResponseSuccess = uploadPetContentResponse200 & {
  headers: Headers;
};
export type uploadPetContentResponseError = uploadPetContentResponseDefault & {
  headers: Headers;
};

export type uploadPetContentResponse =
  | uploadPetContentResponseSuccess
  | uploadPetContentResponseError;

export const getUploadPetContentUrl = () => {
  return `/pets/upload`;
};

/**
 * @summary Upload pet content as url-encoded form
 */
export const uploadPetContent = async (
  uploadPetContentBody: UploadPetContentBody,
  options?: RequestInit,
): Promise<uploadPetContentResponse> => {
  const formUrlEncoded = new URLSearchParams();
  formUrlEncoded.append(`name`, uploadPetContentBody.name);
  if (uploadPetContentBody.content !== undefined) {
    formUrlEncoded.append(`content`, uploadPetContentBody.content);
  }

  const res = await fetch(getUploadPetContentUrl(), {
    ...options,
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options?.headers,
    },
    body: formUrlEncoded,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: uploadPetContentResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as uploadPetContentResponse;
};

export type uploadPetContentRefResponse200 = {
  data: Pet;
  status: 200;
};

export type uploadPetContentRefResponseDefault = {
  data: Error;
  status: Exclude<HTTPStatusCodes, 200>;
};

export type uploadPetContentRefResponseSuccess =
  uploadPetContentRefResponse200 & {
    headers: Headers;
  };
export type uploadPetContentRefResponseError =
  uploadPetContentRefResponseDefault & {
    headers: Headers;
  };

export type uploadPetContentRefResponse =
  | uploadPetContentRefResponseSuccess
  | uploadPetContentRefResponseError;

export const getUploadPetContentRefUrl = () => {
  return `/pets/upload-ref`;
};

/**
 * @summary Upload pet content using a $ref to a binary component schema
 */
export const uploadPetContentRef = async (
  uploadPetContentRefBody: UploadPetContentRefBody,
  options?: RequestInit,
): Promise<uploadPetContentRefResponse> => {
  const formUrlEncoded = new URLSearchParams();
  formUrlEncoded.append(`name`, uploadPetContentRefBody.name);
  if (uploadPetContentRefBody.content !== undefined) {
    formUrlEncoded.append(`content`, uploadPetContentRefBody.content);
  }

  const res = await fetch(getUploadPetContentRefUrl(), {
    ...options,
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options?.headers,
    },
    body: formUrlEncoded,
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: uploadPetContentRefResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as uploadPetContentRefResponse;
};

export const getCreatePetsResponseMock = (
  overrideResponse: Partial<Extract<Pet, object>> = {},
): Pet => ({
  '@id': faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  id: faker.number.int(),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  tag: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  email: faker.helpers.arrayElement([faker.internet.email(), undefined]),
  callingCode: faker.helpers.arrayElement([
    faker.helpers.arrayElement(['+33', '+420', '+33'] as const),
    undefined,
  ]),
  country: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      "People's Republic of China",
      'Uruguay',
    ] as const),
    undefined,
  ]),
  ...overrideResponse,
});

export const getUploadPetContentResponseMock = (
  overrideResponse: Partial<Extract<Pet, object>> = {},
): Pet => ({
  '@id': faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  id: faker.number.int(),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  tag: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  email: faker.helpers.arrayElement([faker.internet.email(), undefined]),
  callingCode: faker.helpers.arrayElement([
    faker.helpers.arrayElement(['+33', '+420', '+33'] as const),
    undefined,
  ]),
  country: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      "People's Republic of China",
      'Uruguay',
    ] as const),
    undefined,
  ]),
  ...overrideResponse,
});

export const getUploadPetContentRefResponseMock = (
  overrideResponse: Partial<Extract<Pet, object>> = {},
): Pet => ({
  '@id': faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  id: faker.number.int(),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  tag: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  email: faker.helpers.arrayElement([faker.internet.email(), undefined]),
  callingCode: faker.helpers.arrayElement([
    faker.helpers.arrayElement(['+33', '+420', '+33'] as const),
    undefined,
  ]),
  country: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      "People's Republic of China",
      'Uruguay',
    ] as const),
    undefined,
  ]),
  ...overrideResponse,
});

export const getCreatePetsMockHandler = (
  overrideResponse?:
    | Pet
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<Pet> | Pet),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/pets',
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getCreatePetsResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getUploadPetContentMockHandler = (
  overrideResponse?:
    | Pet
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<Pet> | Pet),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/pets/upload',
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getUploadPetContentResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getUploadPetContentRefMockHandler = (
  overrideResponse?:
    | Pet
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<Pet> | Pet),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/pets/upload-ref',
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getUploadPetContentRefResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};
export const getSwaggerPetstoreMock = () => [
  getCreatePetsMockHandler(),
  getUploadPetContentMockHandler(),
  getUploadPetContentRefMockHandler(),
];
