/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Mixed Content Responses
 * API with endpoints returning different content types per status code
 * OpenAPI spec version: 1.0.0
 */
import type { GetData200, GetMixedSuccess200 } from './model';

export type getDataResponse200 = {
  data: GetData200;
  status: 200;
};

export type getDataResponse429 = {
  data: string;
  status: 429;
};

export type getDataResponseSuccess = getDataResponse200 & {
  headers: Headers;
};
export type getDataResponseError = getDataResponse429 & {
  headers: Headers;
};

export type getDataResponse = getDataResponseSuccess | getDataResponseError;

export const getGetDataUrl = () => {
  return `/data`;
};

/**
 * @summary Returns JSON on success, plain text on rate limit
 */
export const getData = async (
  options?: RequestInit,
): Promise<getDataResponse> => {
  const res = await fetch(getGetDataUrl(), {
    ...options,
    method: 'GET',
  });

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getDataResponse['data'] = body
    ? contentType.includes('json')
      ? JSON.parse(body)
      : body
    : {};
  return { data, status: res.status, headers: res.headers } as getDataResponse;
};

export type getTextResponse200 = {
  data: string;
  status: 200;
};

export type getTextResponseSuccess = getTextResponse200 & {
  headers: Headers;
};
export type getTextResponse = getTextResponseSuccess;

export const getGetTextUrl = () => {
  return `/text`;
};

/**
 * @summary Returns plain text
 */
export const getText = async (
  options?: RequestInit,
): Promise<getTextResponse> => {
  const res = await fetch(getGetTextUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getTextResponse['data'] = body !== null ? body : '';
  return { data, status: res.status, headers: res.headers } as getTextResponse;
};

export type getImageResponse200 = {
  data: Blob;
  status: 200;
};

export type getImageResponseSuccess = getImageResponse200 & {
  headers: Headers;
};
export type getImageResponse = getImageResponseSuccess;

export const getGetImageUrl = () => {
  return `/image`;
};

/**
 * @summary Returns a binary image
 */
export const getImage = async (
  options?: RequestInit,
): Promise<getImageResponse> => {
  const res = await fetch(getGetImageUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.blob();
  const data: getImageResponse['data'] = body as getImageResponse['data'];
  return { data, status: res.status, headers: res.headers } as getImageResponse;
};

export type getMixedSuccessResponse200 = {
  data: GetMixedSuccess200;
  status: 200;
};

export type getMixedSuccessResponse206 = {
  data: string;
  status: 206;
};

export type getMixedSuccessResponseSuccess = (
  | getMixedSuccessResponse200
  | getMixedSuccessResponse206
) & {
  headers: Headers;
};
export type getMixedSuccessResponse = getMixedSuccessResponseSuccess;

export const getGetMixedSuccessUrl = () => {
  return `/mixed-success`;
};

/**
 * @summary Returns JSON on full success, plain text on partial success
 */
export const getMixedSuccess = async (
  options?: RequestInit,
): Promise<getMixedSuccessResponse> => {
  const res = await fetch(getGetMixedSuccessUrl(), {
    ...options,
    method: 'GET',
  });

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMixedSuccessResponse['data'] = body
    ? contentType.includes('json')
      ? JSON.parse(body)
      : body
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getMixedSuccessResponse;
};
