/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import type { SearchPetsStatus } from './searchPetsStatus';

export type SearchPetsParams = {
  /**
   * @nullable
   */
  requirednullableString: string | null;
  /**
   * @nullable
   */
  requirednullableStringTwo: string | null;
  /**
   * @nullable
   */
  nonRequirednullableString?: string | null;
  /**
   * Filter by adoption status
   */
  status?: SearchPetsStatus;
  /**
   * Only return pets adopted on or after this date
   */
  since?: Date;
  /**
   * Maximum number of results to return
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
};
