/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Orval Regression Tests
 * OpenAPI spec version: 0.0.0
 */
import type { RefNullableBase } from './refNullableBase';

export type RefMemberUnionBase =
  | ((RefNullableBase | null) & {
      id?: string;
      [key: string]: unknown;
    })
  | ({
      right?: string;
    } & {
      id?: string;
      [key: string]: unknown;
    });
