/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * AnyOf Schema
 * OpenAPI spec version: 1.0.0
 */

export * from './a';
export * from './cat';
export * from './catDetail';
export * from './catExpandDetail';
export * from './dog';
export * from './dogDetail';
export * from './dogType';
export * from './getItemsParams';
export * from './getItemsTest';
export * from './pet';
