/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * AnyOf Schema
 * OpenAPI spec version: 1.0.0
 */
import type { Cat } from './cat';
import type { Dog } from './dog';

export type Pet = Cat | Dog;
