/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Angular zod inline array responses
 * OpenAPI spec version: 1.0.0
 */
import { HttpClient } from '@angular/common/http';
import type { HttpContext, HttpEvent, HttpParams } from '@angular/common/http';

import { Injectable, inject } from '@angular/core';

import type { Observable } from 'rxjs';

import type { Item, Items } from './model';

import type {
  HttpHeaders,
  HttpResponse as AngularHttpResponse,
} from '@angular/common/http';

interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
    | HttpParams
    | Record<
        string,
        string | number | boolean | Array<string | number | boolean>
      >;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: { includeHeaders?: string[] } | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};

@Injectable({ providedIn: 'root' })
export class AngularZodInlineArrayResponsesService {
  private readonly http = inject(HttpClient);
  listItems<TData = Item[]>(options?: HttpClientBodyOptions): Observable<TData>;
  listItems<TData = Item[]>(
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  listItems<TData = Item[]>(
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  listItems<TData = Item[]>(
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`/items`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/items`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      });
    }

    return this.http.get<TData>(`/items`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
    });
  }

  listNamedItems<TData = Items>(
    options?: HttpClientBodyOptions,
  ): Observable<TData>;
  listNamedItems<TData = Items>(
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  listNamedItems<TData = Items>(
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  listNamedItems<TData = Items>(
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`/named-items`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/named-items`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      });
    }

    return this.http.get<TData>(`/named-items`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
    });
  }

  listStrings<TData = string[]>(
    options?: HttpClientBodyOptions,
  ): Observable<TData>;
  listStrings<TData = string[]>(
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  listStrings<TData = string[]>(
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  listStrings<TData = string[]>(
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`/strings`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/strings`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      });
    }

    return this.http.get<TData>(`/strings`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
    });
  }

  getItem<TData = Item>(options?: HttpClientBodyOptions): Observable<TData>;
  getItem<TData = Item>(
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  getItem<TData = Item>(
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  getItem<TData = Item>(
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`/item`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/item`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      });
    }

    return this.http.get<TData>(`/item`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
    });
  }
}
