/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Typeless enums
 * OpenAPI spec version: 1.0.0
 */

export * from './colorObject';
export * from './colorObjectColor';
export * from './colors1';
export * from './colors2';
