/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * AllOf Shared Base Schema
 * OpenAPI spec version: 1.0.0
 */
import type { Dog } from './dog';

export interface Response {
  dog?: Dog;
}
