/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * AllOf Shared Base Schema
 * OpenAPI spec version: 1.0.0
 */
import type { Cat } from './cat';

export interface Shelter {
  id: string;
  address: string;
  cats?: Cat[];
}
