/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import { createFactory } from 'hono/factory';
import { zValidator } from '../../endpoints.validator';
import { DeletePetByIdContext } from '../../pets.context';
import { DeletePetByIdParams } from '../../pets.zod';

const factory = createFactory();
export const deletePetByIdHandlers = factory.createHandlers(
  zValidator('param', DeletePetByIdParams),
  async (c: DeletePetByIdContext) => {},
);
