/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Mock Constraints
 * Test one-sided string and array constraints for MSW mock generation
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

import type { ConstrainedItem } from './model';

import { faker } from '@faker-js/faker';

import { HttpResponse, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

/**
 * @summary Get items with one-sided constraints
 */
export const getItems = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ConstrainedItem>> => {
  return axios.get(`/items`, options);
};

export type GetItemsResult = AxiosResponse<ConstrainedItem>;

export const getGetItemsResponseMock = (
  overrideResponse: Partial<Extract<ConstrainedItem, object>> = {},
): ConstrainedItem => ({
  maxLengthOnly: faker.helpers.arrayElement([
    faker.string.alpha({ length: { max: 5 } }),
    undefined,
  ]),
  minLengthOnly: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 30 } }),
    undefined,
  ]),
  maxItemsOnly: faker.helpers.arrayElement([
    Array.from({ length: faker.number.int({ max: 2 }) }, (_, i) => i + 1).map(
      () => faker.string.alpha({ length: { min: 10, max: 20 } }),
    ),
    undefined,
  ]),
  minItemsOnly: faker.helpers.arrayElement([
    Array.from({ length: faker.number.int({ min: 5 }) }, (_, i) => i + 1).map(
      () => faker.string.alpha({ length: { min: 10, max: 20 } }),
    ),
    undefined,
  ]),
  bothBounds: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 2, max: 8 } }),
    undefined,
  ]),
  ...overrideResponse,
});

export const getGetItemsMockHandler = (
  overrideResponse?:
    | ConstrainedItem
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<ConstrainedItem> | ConstrainedItem),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/items',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetItemsResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};
export const getMockConstraintsMock = () => [getGetItemsMockHandler()];
