/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Enums
 * OpenAPI spec version: 1.0.0
 */

export type DogGroup = (typeof DogGroup)[keyof typeof DogGroup];

export const DogGroup = {
  /** Dog Group 1 */
  NUMBER_1: 1,
  /** Dog Group 2 */
  NUMBER_2: 2,
  /** Dog Group 3 */
  NUMBER_3: 3,
} as const;
