/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Factory Methods Test Spec
 * OpenAPI spec version: 1.0.0
 */

import type { DeepCircularB } from './deepCircularB';
import type { DeepCircularC } from './deepCircularC';

export function createDeepCircularB(): DeepCircularB {
  return {
    c: {} as DeepCircularC
  };
}
