/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Factory Methods Test Spec
 * OpenAPI spec version: 1.0.0
 */

import type { Status } from './status';

export function createStatus(): Status {
  return "ACTIVE";
}
