/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Angular httpResource both regression
 * OpenAPI spec version: 1.0.0
 */
import { HttpResponse, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import { getHealthCheckResponseMock } from '../../faker/health/health.faker';

export { getHealthCheckResponseMock } from '../../faker/health/health.faker';

export const getHealthCheckMockHandler = (
  overrideResponse?:
    | string
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<string> | string),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/health',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      const resolvedBody =
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getHealthCheckResponseMock();
      const textBody =
        typeof resolvedBody === 'string'
          ? resolvedBody
          : JSON.stringify(resolvedBody ?? null);
      return HttpResponse.text(textBody, { status: 200 });
    },
    options,
  );
};
export const getHealthMock = () => [getHealthCheckMockHandler()];
