/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */

export * from './Cat';
export * from './CatType';
export * from './CreatePetsBody';
export * from './CreatePetsParams';
export * from './CreatePetsSort';
export * from './Dachshund';
export * from './DachshundBreed';
export * from './Dog';
export * from './DogType';
export * from './Error';
export * from './Labradoodle';
export * from './LabradoodleBreed';
export * from './ListPetsParams';
export * from './ListPetsSort';
export * from './Pet';
export * from './PetCallingCode';
export * from './PetCountry';
export * from './Pets';
export * from './PetWithTag';
