/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import type { Cat } from './Cat';
import type { Dog } from './Dog';
import type { PetCallingCode } from './PetCallingCode';
import type { PetCountry } from './PetCountry';

export type Pet =
  | (Dog & {
      '@id'?: string;
      id: number;
      name: string;
      tag?: string;
      email?: string;
      callingCode?: PetCallingCode;
      country?: PetCountry;
    })
  | (Cat & {
      '@id'?: string;
      id: number;
      name: string;
      tag?: string;
      email?: string;
      callingCode?: PetCallingCode;
      country?: PetCountry;
    });
