/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Faker array item factories
 * OpenAPI spec version: 1.0.0
 */
import type { GetNullable200RowsItem } from './getNullable200RowsItem';

export type GetNullable200 = {
  rows?: GetNullable200RowsItem[];
};
