/**
 * Generated by orval v8.5.0 🍺
 * Do not edit manually.
 * Enums
 * OpenAPI spec version: 1.0.0
 */
import type { RequiredBulldogColour } from './requiredBulldogColour';

export interface RequiredBulldog {
  colour: RequiredBulldogColour;
}
