/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Enums
 * OpenAPI spec version: 1.0.0
 */

export enum RequiredSiameseColoursItem {
  /** Represents black colour */
  Black = 'BLACK',
  /** Represents brown colour */
  Brown = 'BROWN',
  /** Represents white colour */
  White = 'WHITE',
  /** Represents grey colour */
  Grey = 'GREY',
}
