/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import type { DachshundBreed } from './dachshundBreed';

export interface Dachshund {
  breed: DachshundBreed;
  length: number;
}
