/**
 * Generated by orval v6.28.0 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */

export type LabradoodleBreed =
  (typeof LabradoodleBreed)[keyof typeof LabradoodleBreed];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LabradoodleBreed = {
  Labradoodle: 'Labradoodle',
} as const;
