/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import type { CountryCode } from './countryCode';

export interface Pet {
  '@id'?: string;
  id: number;
  name: string;
  tag?: string;
  age?: number;
  countryCode?: CountryCode;
}
