/**
 * Generated by orval v6.6.0 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */

export type PetCountry = 'People\'s Republic of China' | 'Uruguay';


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PetCountry = {
  Peoples_Republic_of_China: 'People\'s Republic of China' as PetCountry,
  Uruguay: 'Uruguay' as PetCountry,
};
