/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Issue 1107 - cross-file $ref type alias exports
 * OpenAPI spec version: 1.0.0
 */
import type { Pet } from './pet';

export type Pets = Pet[];
