/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import type { AnotherSchema } from './anotherSchema';

export interface Pet {
  id: number;
  file?: AnotherSchema;
}
