/**
 * Generated by orval v8.4.2 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import { createQuery } from '@tanstack/svelte-query';
import type {
  CreateQueryOptions,
  CreateQueryResult,
  QueryFunction,
  QueryKey,
} from '@tanstack/svelte-query';

import type { Error } from '.././model';

/**
 * @summary health check
 */
export const getHealthCheckUrl = () => {
  return `/health`;
};

export const healthCheck = async (options?: RequestInit): Promise<string> => {
  const res = await fetch(getHealthCheckUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: string = body ? JSON.parse(body) : {};
  return data;
};

export const getHealthCheckQueryKey = () => {
  return [`/health`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = Error,
>(options?: {
  query?: CreateQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = Error;

/**
 * @summary health check
 */

export function createHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = Error,
>(options?: {
  query?: CreateQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  fetch?: RequestInit;
}): CreateQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = createQuery(queryOptions) as CreateQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
}
