/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

export interface Pet {
  id: number;
  name: string;
  tag?: string;
}

export type Pets = Pet[];

export interface Error {
  code: number;
  message: string;
}

export type ListPetsParams = {
  /**
   * How many items to return at one time (max 100)
   */
  limit?: string;
};

export type CreatePetsBody = {
  name: string;
  tag: string;
};

/**
 * @summary List all pets
 */
export const listPets = (
  params?: ListPetsParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Pets>> => {
  return axios.get(`/pets`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};
export const getListPetsUrl = (params?: ListPetsParams) => {
  return axios
    .create({
      baseURL: '',
      params: null,
    })
    .getUri({
      url: `/pets`,
      baseURL: '',
      params,
    });
};

/**
 * @summary Create a pet
 */
export const createPets = (
  createPetsBody: CreatePetsBody,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.post(`/pets`, createPetsBody, options);
};
export const getCreatePetsUrl = () => {
  return axios
    .create({
      baseURL: '',
      params: null,
    })
    .getUri({
      url: `/pets`,
      baseURL: '',
    });
};

/**
 * @summary Info for a specific pet
 */
export const showPetById = (
  petId: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<Pet>> => {
  return axios.get(`/pets/${petId}`, options);
};
export const getShowPetByIdUrl = (petId: string) => {
  return axios
    .create({
      baseURL: '',
      params: null,
    })
    .getUri({
      url: `/pets/${petId}`,
      baseURL: '',
    });
};

export type ListPetsResult = AxiosResponse<Pets>;
export type CreatePetsResult = AxiosResponse<void>;
export type ShowPetByIdResult = AxiosResponse<Pet>;
