/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useQuery } from '@tanstack/vue-query';
import type {
  DataTag,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseInfiniteQueryOptions,
  UseInfiniteQueryReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query';

import { computed, toValue, unref } from 'vue';
import type { MaybeRefOrGetter } from 'vue';

import type {
  CreatePetsBody,
  CreatePetsParams,
  Error,
  ListPetsParams,
  Pet,
  PetWithTag,
  Pets,
} from './model';

import { customInstance } from '../../../mutators/custom-instance';
/**
 * @summary List all pets
 */
export const listPets = (
  params: MaybeRefOrGetter<ListPetsParams>,
  version: MaybeRefOrGetter<number> = 1,
  signal?: AbortSignal,
) => {
  params = toValue(params);
  version = toValue(version);

  return customInstance<Pets>({
    url: `/v${version}/pets`,
    method: 'GET',
    params,
    signal,
  });
};

export const getListPetsInfiniteQueryKey = (
  params?: MaybeRefOrGetter<ListPetsParams>,
  version: MaybeRefOrGetter<number> = 1,
) => {
  return [
    'infinite',
    'v',
    version,
    'pets',
    ...(params ? [params] : []),
  ] as const;
};

export const getListPetsQueryKey = (
  params?: MaybeRefOrGetter<ListPetsParams>,
  version: MaybeRefOrGetter<number> = 1,
) => {
  return ['v', version, 'pets', ...(params ? [params] : [])] as const;
};

export const getListPetsInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof listPets>>,
    ListPetsParams['limit']
  >,
  TError = Error,
>(
  params: MaybeRefOrGetter<ListPetsParams>,
  version: MaybeRefOrGetter<number> = 1,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof listPets>>,
        TError,
        TData,
        QueryKey,
        ListPetsParams['limit']
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getListPetsInfiniteQueryKey(params, version);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listPets>>,
    QueryKey,
    ListPetsParams['limit']
  > = ({ signal, pageParam }) =>
    listPets(
      { ...toValue(params), limit: pageParam ?? toValue(params)?.['limit'] },
      version,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled: computed(
      () => toValue(version) !== null && toValue(version) !== undefined,
    ),
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof listPets>>,
    TError,
    TData,
    QueryKey,
    ListPetsParams['limit']
  >;
};

export type ListPetsInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof listPets>>
>;
export type ListPetsInfiniteQueryError = Error;

/**
 * @summary List all pets
 */

export function useListPetsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof listPets>>,
    ListPetsParams['limit']
  >,
  TError = Error,
>(
  params: MaybeRefOrGetter<ListPetsParams>,
  version: MaybeRefOrGetter<number> = 1,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof listPets>>,
        TError,
        TData,
        QueryKey,
        ListPetsParams['limit']
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListPetsInfiniteQueryOptions(
    params,
    version,
    options,
  );

  const query = useInfiniteQuery(
    queryOptions,
    queryClient,
  ) as UseInfiniteQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

export const getListPetsQueryOptions = <
  TData = Awaited<ReturnType<typeof listPets>>,
  TError = Error,
>(
  params: MaybeRefOrGetter<ListPetsParams>,
  version: MaybeRefOrGetter<number> = 1,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listPets>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getListPetsQueryKey(params, version);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listPets>>> = ({
    signal,
  }) => listPets(params, version, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(
      () => toValue(version) !== null && toValue(version) !== undefined,
    ),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof listPets>>, TError, TData>;
};

export type ListPetsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listPets>>
>;
export type ListPetsQueryError = Error;

/**
 * @summary List all pets
 */

export function useListPets<
  TData = Awaited<ReturnType<typeof listPets>>,
  TError = Error,
>(
  params: MaybeRefOrGetter<ListPetsParams>,
  version: MaybeRefOrGetter<number> = 1,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listPets>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListPetsQueryOptions(params, version, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * @summary Create a pet
 */
export const createPets = (
  createPetsBody: MaybeRefOrGetter<CreatePetsBody>,
  params: MaybeRefOrGetter<CreatePetsParams>,
  version: MaybeRefOrGetter<number> = 1,
  signal?: AbortSignal,
) => {
  createPetsBody = toValue(createPetsBody);
  params = toValue(params);
  version = toValue(version);

  return customInstance<Pet>({
    url: `/v${version}/pets`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createPetsBody,
    params,
    signal,
  });
};

export const getCreatePetsQueryKey = (
  createPetsBody?: MaybeRefOrGetter<CreatePetsBody>,
  params?: MaybeRefOrGetter<CreatePetsParams>,
  version: MaybeRefOrGetter<number> = 1,
) => {
  return [
    'POST',
    'v',
    version,
    'pets',
    ...(params ? [params] : []),
    createPetsBody,
  ] as const;
};

export const getCreatePetsQueryOptions = <
  TData = Awaited<ReturnType<typeof createPets>>,
  TError = Error,
>(
  createPetsBody: MaybeRefOrGetter<CreatePetsBody>,
  params: MaybeRefOrGetter<CreatePetsParams>,
  version: MaybeRefOrGetter<number> = 1,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof createPets>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getCreatePetsQueryKey(createPetsBody, params, version);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof createPets>>> = ({
    signal,
  }) => createPets(createPetsBody, params, version, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(
      () => toValue(version) !== null && toValue(version) !== undefined,
    ),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof createPets>>, TError, TData>;
};

export type CreatePetsQueryResult = NonNullable<
  Awaited<ReturnType<typeof createPets>>
>;
export type CreatePetsQueryError = Error;

/**
 * @summary Create a pet
 */

export function useCreatePets<
  TData = Awaited<ReturnType<typeof createPets>>,
  TError = Error,
>(
  createPetsBody: MaybeRefOrGetter<CreatePetsBody>,
  params: MaybeRefOrGetter<CreatePetsParams>,
  version: MaybeRefOrGetter<number> = 1,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof createPets>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCreatePetsQueryOptions(
    createPetsBody,
    params,
    version,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * @summary Info for a specific pet
 */
export const showPetById = (
  petId: MaybeRefOrGetter<string>,
  version: MaybeRefOrGetter<number> = 1,
  signal?: AbortSignal,
) => {
  petId = toValue(petId);
  version = toValue(version);

  return customInstance<Pet>({
    url: `/v${version}/pets/${petId}`,
    method: 'GET',
    signal,
  });
};

export const getShowPetByIdQueryKey = (
  petId: MaybeRefOrGetter<string>,
  version: MaybeRefOrGetter<number> = 1,
) => {
  return ['v', version, 'pets', petId] as const;
};

export const getShowPetByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof showPetById>>,
  TError = Error,
>(
  petId: MaybeRefOrGetter<string>,
  version: MaybeRefOrGetter<number> = 1,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof showPetById>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getShowPetByIdQueryKey(petId, version);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof showPetById>>> = ({
    signal,
  }) => showPetById(petId, version, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(
      () =>
        toValue(version) !== null &&
        toValue(version) !== undefined &&
        toValue(petId) !== null &&
        toValue(petId) !== undefined,
    ),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof showPetById>>, TError, TData>;
};

export type ShowPetByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof showPetById>>
>;
export type ShowPetByIdQueryError = Error;

/**
 * @summary Info for a specific pet
 */

export function useShowPetById<
  TData = Awaited<ReturnType<typeof showPetById>>,
  TError = Error,
>(
  petId: MaybeRefOrGetter<string>,
  version: MaybeRefOrGetter<number> = 1,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof showPetById>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getShowPetByIdQueryOptions(petId, version, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * @summary Deletes a specific pet
 */
export const deletePetById = (
  petId: MaybeRefOrGetter<string>,
  version: MaybeRefOrGetter<number> = 1,
  signal?: AbortSignal,
) => {
  petId = toValue(petId);
  version = toValue(version);

  return customInstance<void>({
    url: `/v${version}/pets/${petId}`,
    method: 'DELETE',
    signal,
  });
};

export const getDeletePetByIdQueryKey = (
  petId: MaybeRefOrGetter<string>,
  version: MaybeRefOrGetter<number> = 1,
) => {
  return ['DELETE', 'v', version, 'pets', petId] as const;
};

export const getDeletePetByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof deletePetById>>,
  TError = Error,
>(
  petId: MaybeRefOrGetter<string>,
  version: MaybeRefOrGetter<number> = 1,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof deletePetById>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getDeletePetByIdQueryKey(petId, version);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof deletePetById>>> = ({
    signal,
  }) => deletePetById(petId, version, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(
      () =>
        toValue(version) !== null &&
        toValue(version) !== undefined &&
        toValue(petId) !== null &&
        toValue(petId) !== undefined,
    ),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof deletePetById>>,
    TError,
    TData
  >;
};

export type DeletePetByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof deletePetById>>
>;
export type DeletePetByIdQueryError = Error;

/**
 * @summary Deletes a specific pet
 */

export function useDeletePetById<
  TData = Awaited<ReturnType<typeof deletePetById>>,
  TError = Error,
>(
  petId: MaybeRefOrGetter<string>,
  version: MaybeRefOrGetter<number> = 1,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof deletePetById>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDeletePetByIdQueryOptions(petId, version, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * @summary health check
 */
export const healthCheck = (
  version: MaybeRefOrGetter<number> = 1,
  signal?: AbortSignal,
) => {
  version = toValue(version);

  return customInstance<string>({
    url: `/v${version}/health`,
    method: 'GET',
    signal,
  });
};

export const getHealthCheckQueryKey = (
  version: MaybeRefOrGetter<number> = 1,
) => {
  return ['v', version, 'health'] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = Error,
>(
  version: MaybeRefOrGetter<number> = 1,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getHealthCheckQueryKey(version);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck(version, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(
      () => toValue(version) !== null && toValue(version) !== undefined,
    ),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>;
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = Error;

/**
 * @summary health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = Error,
>(
  version: MaybeRefOrGetter<number> = 1,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getHealthCheckQueryOptions(version, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * @summary combinate nullable and $ref
 */
export const showPetWithOwner = (
  petId: MaybeRefOrGetter<string>,
  version: MaybeRefOrGetter<number> = 1,
  signal?: AbortSignal,
) => {
  petId = toValue(petId);
  version = toValue(version);

  return customInstance<PetWithTag>({
    url: `/v${version}/pets/${petId}/owner`,
    method: 'GET',
    signal,
  });
};

export const getShowPetWithOwnerQueryKey = (
  petId: MaybeRefOrGetter<string>,
  version: MaybeRefOrGetter<number> = 1,
) => {
  return ['v', version, 'pets', petId, 'owner'] as const;
};

export const getShowPetWithOwnerQueryOptions = <
  TData = Awaited<ReturnType<typeof showPetWithOwner>>,
  TError = Error,
>(
  petId: MaybeRefOrGetter<string>,
  version: MaybeRefOrGetter<number> = 1,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof showPetWithOwner>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getShowPetWithOwnerQueryKey(petId, version);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof showPetWithOwner>>
  > = ({ signal }) => showPetWithOwner(petId, version, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(
      () =>
        toValue(version) !== null &&
        toValue(version) !== undefined &&
        toValue(petId) !== null &&
        toValue(petId) !== undefined,
    ),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof showPetWithOwner>>,
    TError,
    TData
  >;
};

export type ShowPetWithOwnerQueryResult = NonNullable<
  Awaited<ReturnType<typeof showPetWithOwner>>
>;
export type ShowPetWithOwnerQueryError = Error;

/**
 * @summary combinate nullable and $ref
 */

export function useShowPetWithOwner<
  TData = Awaited<ReturnType<typeof showPetWithOwner>>,
  TError = Error,
>(
  petId: MaybeRefOrGetter<string>,
  version: MaybeRefOrGetter<number> = 1,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof showPetWithOwner>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getShowPetWithOwnerQueryOptions(petId, version, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}
