/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import { Hono } from 'hono';

import { listPetsHandlers } from './src/handlers/list-pets';
import { createPetsHandlers } from './src/handlers/create-pets';
import { showPetByIdHandlers } from './src/handlers/show-pet-by-id';
import { deletePetByIdHandlers } from './src/handlers/delete-pet-by-id';
import { healthCheckHandlers } from './src/handlers/health-check';
import { showPetWithOwnerHandlers } from './src/handlers/show-pet-with-owner';

const app = new Hono()
  /**
   * @summary List all pets
   */

  .get('/pets', ...listPetsHandlers)

  /**
   * @summary Create a pet
   */

  .post('/pets', ...createPetsHandlers)

  /**
   * @summary Info for a specific pet
   */

  .get('/pets/:petId', ...showPetByIdHandlers)

  /**
   * @summary Deletes a specific pet
   */

  .delete('/pets/:petId', ...deletePetByIdHandlers)

  /**
   * @summary health check
   */

  .get('/health', ...healthCheckHandlers)

  /**
   * @summary combinate nullable and $ref
   */

  .get('/pets/:petId/owner', ...showPetWithOwnerHandlers);

export default app;
