/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import { Hono } from 'hono';

import { listPetsHandlers } from './src/handlers/listPets';
import { createPetsHandlers } from './src/handlers/createPets';
import { showPetByIdHandlers } from './src/handlers/showPetById';
import { deletePetByIdHandlers } from './src/handlers/deletePetById';
import { healthCheckHandlers } from './src/handlers/healthCheck';
import { showPetWithOwnerHandlers } from './src/handlers/showPetWithOwner';

const app = new Hono()
  /**
   * @summary List all pets
   */

  .get('/pets', ...listPetsHandlers)

  /**
   * @summary Create a pet
   */

  .post('/pets', ...createPetsHandlers)

  /**
   * @summary Info for a specific pet
   */

  .get('/pets/:petId', ...showPetByIdHandlers)

  /**
   * @summary Deletes a specific pet
   */

  .delete('/pets/:petId', ...deletePetByIdHandlers)

  /**
   * @summary health check
   */

  .get('/health', ...healthCheckHandlers)

  /**
   * @summary combinate nullable and $ref
   */

  .get('/pets/:petId/owner', ...showPetWithOwnerHandlers);

export default app;
