/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient,
  HttpHeaders,
  HttpResponse as AngularHttpResponse,
  httpResource,
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams,
  HttpResourceOptions,
  HttpResourceRef,
  HttpResourceRequest,
} from '@angular/common/http';

import { Injectable, inject } from '@angular/core';
import type { ResourceStatus, Signal } from '@angular/core';

import { Observable } from 'rxjs';

import { Pet, Pets } from '../model';
import type {
  CreatePetsBody,
  ListPetsParams,
  PetOutput,
  PetsOutput,
  SearchPetsParams,
} from '../model';

import { map } from 'rxjs';

export interface OrvalHttpResourceRequestExtension {
  /** Extra headers merged over generated headers. Pass a function to read signals reactively. */
  headers?:
    | HttpResourceRequest['headers']
    | (() => HttpResourceRequest['headers']);
  /** Angular HttpContext forwarded to the underlying request. Pass a function to derive it reactively. */
  context?: HttpContext | (() => HttpContext);
  /** Last-resort escape hatch: transform the final request descriptor. Runs inside the resource's reactive context. */
  request?: (request: HttpResourceRequest) => HttpResourceRequest;
}

export type OrvalHttpResourceOptions<
  TValue,
  TRaw = unknown,
  TOmitParse extends boolean = true,
> = (TOmitParse extends true
  ? Omit<HttpResourceOptions<TValue, TRaw>, 'parse'>
  : HttpResourceOptions<TValue, TRaw>) &
  OrvalHttpResourceRequestExtension;

function mergeOrvalResourceHeaders(
  base: HttpResourceRequest['headers'],
  extra: HttpResourceRequest['headers'],
): HttpResourceRequest['headers'] {
  if (!base) return extra;
  if (!extra) return base;
  if (base instanceof HttpHeaders || extra instanceof HttpHeaders) {
    const toHeaderValue = (
      value: string | readonly string[],
    ): string | string[] =>
      Array.isArray(value) ? Array.from(value, String) : String(value);
    let merged =
      base instanceof HttpHeaders
        ? base
        : Object.entries(base).reduce(
            (headers, [key, value]) => headers.set(key, toHeaderValue(value)),
            new HttpHeaders(),
          );
    const extraRecord =
      extra instanceof HttpHeaders
        ? extra.keys().reduce<Record<string, string[]>>((record, key) => {
            const values = extra.getAll(key);
            if (values) record[key] = values;
            return record;
          }, {})
        : extra;
    for (const [key, value] of Object.entries(extraRecord)) {
      merged = merged.set(key, toHeaderValue(value));
    }
    return merged;
  }
  return { ...base, ...extra };
}

export function applyOrvalRequestExtension(
  request: string | HttpResourceRequest,
  options?: OrvalHttpResourceRequestExtension,
): HttpResourceRequest {
  const base: HttpResourceRequest =
    typeof request === 'string' ? { url: request } : request;
  if (
    !options ||
    (options.headers === undefined &&
      options.context === undefined &&
      options.request === undefined)
  ) {
    return base;
  }
  let next: HttpResourceRequest = { ...base };
  const extraHeaders =
    typeof options.headers === 'function' ? options.headers() : options.headers;
  if (extraHeaders !== undefined) {
    next = {
      ...next,
      headers: mergeOrvalResourceHeaders(next.headers, extraHeaders),
    };
  }
  const context =
    typeof options.context === 'function' ? options.context() : options.context;
  if (context !== undefined) {
    next = { ...next, context };
  }
  return options.request ? options.request(next) : next;
}

type AngularHttpParamValue =
  | string
  | number
  | boolean
  | Array<string | number | boolean>;
type AngularHttpParamValueWithNullable = AngularHttpParamValue | null;

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys?: ReadonlySet<string>,
  preserveRequiredNullables?: false,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValue>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: true,
  passthroughKeys?: undefined,
): Record<string, AngularHttpParamValueWithNullable>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> | undefined,
  preserveRequiredNullables: boolean | undefined,
  passthroughKeys: ReadonlySet<string>,
): Record<string, unknown>;
function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: ReadonlySet<string> = new Set(),
  preserveRequiredNullables = false,
  passthroughKeys: ReadonlySet<string> = new Set(),
): Record<string, unknown> {
  const filteredParams: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(params)) {
    if (passthroughKeys.has(key)) {
      if (value !== undefined) {
        filteredParams[key] = value;
      }
      continue;
    }
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' ||
            typeof item === 'number' ||
            typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (
      preserveRequiredNullables &&
      value === null &&
      requiredNullableKeys.has(key)
    ) {
      filteredParams[key] = null;
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
}
export type ListPetsAccept =
  (typeof ListPetsAccept)[keyof typeof ListPetsAccept];

export const ListPetsAccept = {
  application_json: 'application/json',
  application_xml: 'application/xml',
} as const;

export type ShowPetByIdAccept =
  (typeof ShowPetByIdAccept)[keyof typeof ShowPetByIdAccept];

export const ShowPetByIdAccept = {
  text_plain: 'text/plain',
  application_xml: 'application/xml',
  application_json: 'application/json',
} as const;

export type UpdatePetByIdAccept =
  (typeof UpdatePetByIdAccept)[keyof typeof UpdatePetByIdAccept];

export const UpdatePetByIdAccept = {
  application_json: 'application/json',
  text_plain: 'text/plain',
} as const;

export type PatchPetByIdAccept =
  (typeof PatchPetByIdAccept)[keyof typeof PatchPetByIdAccept];

export const PatchPetByIdAccept = {
  application_json: 'application/json',
  text_plain: 'text/plain',
} as const;

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function searchPetsResource(
  params: Signal<SearchPetsParams>,
  version: Signal<number> | undefined,
  options: OrvalHttpResourceOptions<PetsOutput, unknown, true> & {
    defaultValue: NoInfer<PetsOutput>;
  },
): HttpResourceRef<PetsOutput>;
export function searchPetsResource(
  params: Signal<SearchPetsParams>,
  version?: Signal<number>,
  options?: OrvalHttpResourceOptions<PetsOutput, unknown, true>,
): HttpResourceRef<PetsOutput | undefined>;
export function searchPetsResource(
  params: Signal<SearchPetsParams>,
  version?: Signal<number>,
  options?: OrvalHttpResourceOptions<PetsOutput, unknown, true>,
): HttpResourceRef<PetsOutput | undefined> {
  return httpResource<PetsOutput>(
    () => {
      const request = {
        url: `/v${version?.() ?? 1}/search`,
        params: filterParams(
          params?.() ?? {},
          new Set<string>([
            'requirednullableString',
            'requirednullableStringTwo',
          ]),
        ),
      };
      return applyOrvalRequestExtension(request, options);
    },
    {
      ...(options ?? {}),
      parse: Pets.parse,
    },
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function listPetsResource(
  accept: 'application/json',
  params?: Signal<ListPetsParams>,
  version?: Signal<number>,
  options?: OrvalHttpResourceOptions<PetsOutput, unknown, true>,
): HttpResourceRef<PetsOutput | undefined>;
export function listPetsResource(
  accept: 'application/xml',
  params?: Signal<ListPetsParams>,
  version?: Signal<number>,
  options?: OrvalHttpResourceOptions<string, string, true>,
): HttpResourceRef<string | undefined>;
export function listPetsResource(
  accept: ListPetsAccept = 'application/json',
  params?: Signal<ListPetsParams>,
  version?: Signal<number>,
  options?:
    | OrvalHttpResourceOptions<PetsOutput, unknown, true>
    | OrvalHttpResourceOptions<string, string, true>,
): HttpResourceRef<PetsOutput | string | undefined> {
  const buildRequest = (): HttpResourceRequest => {
    const request = {
      url: `/v${version?.() ?? 1}/pets`,
      params: filterParams(params?.() ?? {}, new Set<string>([])),
    };
    const normalizedRequest: HttpResourceRequest = request;
    const extendedRequest = applyOrvalRequestExtension(
      normalizedRequest,
      options,
    );
    return {
      ...extendedRequest,
      headers:
        extendedRequest.headers instanceof HttpHeaders
          ? extendedRequest.headers.set('Accept', accept)
          : { ...(extendedRequest.headers ?? {}), Accept: accept },
    };
  };

  if (accept.includes('json') || accept.includes('+json')) {
    return httpResource<PetsOutput>(buildRequest, {
      ...(options ?? {}),
      parse: Pets.parse,
    } as unknown as OrvalHttpResourceOptions<PetsOutput, unknown, true>);
  }

  if (accept.startsWith('text/') || accept.includes('xml')) {
    return httpResource.text<string>(
      buildRequest,
      options as unknown as OrvalHttpResourceOptions<string, string, true>,
    );
  }

  return httpResource<PetsOutput>(buildRequest, {
    ...(options ?? {}),
    parse: Pets.parse,
  } as unknown as OrvalHttpResourceOptions<PetsOutput, unknown, true>);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function showPetByIdResource(
  petId: Signal<string>,
  accept: 'text/plain',
  version?: Signal<number>,
  options?: OrvalHttpResourceOptions<string, string, true>,
): HttpResourceRef<string | undefined>;
export function showPetByIdResource(
  petId: Signal<string>,
  accept: 'application/xml',
  version?: Signal<number>,
  options?: OrvalHttpResourceOptions<string, string, true>,
): HttpResourceRef<string | undefined>;
export function showPetByIdResource(
  petId: Signal<string>,
  accept: 'application/json',
  version?: Signal<number>,
  options?: OrvalHttpResourceOptions<PetOutput, unknown, true>,
): HttpResourceRef<PetOutput | undefined>;
export function showPetByIdResource(
  petId: Signal<string>,
  accept: ShowPetByIdAccept = 'application/json',
  version?: Signal<number>,
  options?:
    | OrvalHttpResourceOptions<string, string, true>
    | OrvalHttpResourceOptions<PetOutput, unknown, true>,
): HttpResourceRef<string | PetOutput | undefined> {
  const buildRequest = (): HttpResourceRequest => {
    const request = `/v${version?.() ?? 1}/pets/${petId()}`;
    const normalizedRequest: HttpResourceRequest = { url: request };
    const extendedRequest = applyOrvalRequestExtension(
      normalizedRequest,
      options,
    );
    return {
      ...extendedRequest,
      headers:
        extendedRequest.headers instanceof HttpHeaders
          ? extendedRequest.headers.set('Accept', accept)
          : { ...(extendedRequest.headers ?? {}), Accept: accept },
    };
  };

  if (accept.includes('json') || accept.includes('+json')) {
    return httpResource<PetOutput>(buildRequest, {
      ...(options ?? {}),
      parse: Pet.parse,
    } as unknown as OrvalHttpResourceOptions<PetOutput, unknown, true>);
  }

  if (accept.startsWith('text/') || accept.includes('xml')) {
    return httpResource.text<string>(
      buildRequest,
      options as unknown as OrvalHttpResourceOptions<string, string, true>,
    );
  }

  return httpResource<PetOutput>(buildRequest, {
    ...(options ?? {}),
    parse: Pet.parse,
  } as unknown as OrvalHttpResourceOptions<PetOutput, unknown, true>);
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function showPetTextResource(
  petId: Signal<string>,
  version: Signal<number> | undefined,
  options: OrvalHttpResourceOptions<string, string, true> & {
    defaultValue: NoInfer<string>;
  },
): HttpResourceRef<string>;
export function showPetTextResource(
  petId: Signal<string>,
  version?: Signal<number>,
  options?: OrvalHttpResourceOptions<string, string, true>,
): HttpResourceRef<string | undefined>;
export function showPetTextResource(
  petId: Signal<string>,
  version?: Signal<number>,
  options?: OrvalHttpResourceOptions<string, string, true>,
): HttpResourceRef<string | undefined> {
  return httpResource.text<string>(
    () =>
      applyOrvalRequestExtension(
        `/v${version?.() ?? 1}/pets/${petId()}/text`,
        options,
      ),
    options,
  );
}

/**
 * @experimental httpResource is experimental (Angular v19.2+)
 */
export function downloadFileResource(
  petId: Signal<number>,
  version: Signal<number> | undefined,
  options: OrvalHttpResourceOptions<Blob, Blob, true> & {
    defaultValue: NoInfer<Blob>;
  },
): HttpResourceRef<Blob>;
export function downloadFileResource(
  petId: Signal<number>,
  version?: Signal<number>,
  options?: OrvalHttpResourceOptions<Blob, Blob, true>,
): HttpResourceRef<Blob | undefined>;
export function downloadFileResource(
  petId: Signal<number>,
  version?: Signal<number>,
  options?: OrvalHttpResourceOptions<Blob, Blob, true>,
): HttpResourceRef<Blob | undefined> {
  return httpResource.blob<Blob>(
    () =>
      applyOrvalRequestExtension(
        `/v${version?.() ?? 1}/pet/${petId()}/downloadImage`,
        options,
      ),
    options,
  );
}

interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
    | HttpParams
    | Record<
        string,
        string | number | boolean | Array<string | number | boolean>
      >;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: { includeHeaders?: string[] } | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};

@Injectable({ providedIn: 'root' })
export class PetsService {
  private readonly http = inject(HttpClient);

  createPets<TData = void>(
    createPetsBody: CreatePetsBody,
    version?: number,
    options?: HttpClientBodyOptions,
  ): Observable<TData>;
  createPets<TData = void>(
    createPetsBody: CreatePetsBody,
    version?: number,
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  createPets<TData = void>(
    createPetsBody: CreatePetsBody,
    version?: number,
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  createPets<TData = void>(
    createPetsBody: CreatePetsBody,
    version: number = 1,
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(`/v${version}/pets`, createPetsBody, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      });
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(`/v${version}/pets`, createPetsBody, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      });
    }

    return this.http.post<TData>(`/v${version}/pets`, createPetsBody, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
    });
  }

  updatePetById(
    petId: string,
    pet: Pet,
    accept: 'application/json',
    version?: number,
    options?: HttpClientOptions,
  ): Observable<PetOutput>;
  updatePetById(
    petId: string,
    pet: Pet,
    accept: 'text/plain',
    version?: number,
    options?: HttpClientOptions,
  ): Observable<string>;
  updatePetById(
    petId: string,
    pet: Pet,
    accept?: UpdatePetByIdAccept,
    version?: number,
    options?: HttpClientOptions,
  ): Observable<PetOutput | string>;
  updatePetById(
    petId: string,
    pet: Pet,
    accept: UpdatePetByIdAccept = 'application/json',
    version: number = 1,
    options?: HttpClientOptions,
  ): Observable<PetOutput | string> {
    const headers =
      options?.headers instanceof HttpHeaders
        ? options.headers.set('Accept', accept)
        : { ...(options?.headers ?? {}), Accept: accept };

    if (accept.includes('json') || accept.includes('+json')) {
      return this.http
        .put<PetOutput>(`/v${version}/pets/${petId}/update`, pet, {
          ...options,
          responseType: 'json',
          headers,
        })
        .pipe(map((data) => Pet.parse(data)));
    } else if (accept.startsWith('text/') || accept.includes('xml')) {
      return this.http.put(`/v${version}/pets/${petId}/update`, pet, {
        ...options,
        responseType: 'text',
        headers,
      }) as Observable<any>;
    }

    return this.http
      .put<PetOutput>(`/v${version}/pets/${petId}/update`, pet, {
        ...options,
        responseType: 'json',
        headers,
      })
      .pipe(map((data) => Pet.parse(data)));
  }

  patchPetById(
    petId: string,
    pet: Pet | undefined,
    accept: 'application/json',
    version?: number,
    options?: HttpClientOptions,
  ): Observable<PetOutput>;
  patchPetById(
    petId: string,
    pet: Pet | undefined,
    accept: 'text/plain',
    version?: number,
    options?: HttpClientOptions,
  ): Observable<string>;
  patchPetById(
    petId: string,
    pet?: Pet,
    accept?: PatchPetByIdAccept,
    version?: number,
    options?: HttpClientOptions,
  ): Observable<PetOutput | string>;
  patchPetById(
    petId: string,
    pet?: Pet,
    accept: PatchPetByIdAccept = 'application/json',
    version: number = 1,
    options?: HttpClientOptions,
  ): Observable<PetOutput | string> {
    const headers =
      options?.headers instanceof HttpHeaders
        ? options.headers.set('Accept', accept)
        : { ...(options?.headers ?? {}), Accept: accept };

    if (accept.includes('json') || accept.includes('+json')) {
      return this.http
        .patch<PetOutput>(`/v${version}/pets/${petId}/update`, pet, {
          ...options,
          responseType: 'json',
          headers,
        })
        .pipe(map((data) => Pet.parse(data)));
    } else if (accept.startsWith('text/') || accept.includes('xml')) {
      return this.http.patch(`/v${version}/pets/${petId}/update`, pet, {
        ...options,
        responseType: 'text',
        headers,
      }) as Observable<any>;
    }

    return this.http
      .patch<PetOutput>(`/v${version}/pets/${petId}/update`, pet, {
        ...options,
        responseType: 'json',
        headers,
      })
      .pipe(map((data) => Pet.parse(data)));
  }

  uploadFile<TData = void>(
    petId: number,
    uploadFileBody?: Blob,
    version?: number,
    options?: HttpClientBodyOptions,
  ): Observable<TData>;
  uploadFile<TData = void>(
    petId: number,
    uploadFileBody?: Blob,
    version?: number,
    options?: HttpClientEventOptions,
  ): Observable<HttpEvent<TData>>;
  uploadFile<TData = void>(
    petId: number,
    uploadFileBody?: Blob,
    version?: number,
    options?: HttpClientResponseOptions,
  ): Observable<AngularHttpResponse<TData>>;
  uploadFile<TData = void>(
    petId: number,
    uploadFileBody?: Blob,
    version: number = 1,
    options?: HttpClientObserveOptions,
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
        `/v${version}/pet/${petId}/uploadImage`,
        uploadFileBody,
        {
          ...(options as Omit<NonNullable<typeof options>, 'observe'>),
          observe: 'events',
        },
      );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
        `/v${version}/pet/${petId}/uploadImage`,
        uploadFileBody,
        {
          ...(options as Omit<NonNullable<typeof options>, 'observe'>),
          observe: 'response',
        },
      );
    }

    return this.http.post<TData>(
      `/v${version}/pet/${petId}/uploadImage`,
      uploadFileBody,
      {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      },
    );
  }
}

export type SearchPetsResourceResult = NonNullable<PetsOutput>;
export type ListPetsResourceResult = NonNullable<PetsOutput | string>;
export type ShowPetByIdResourceResult = NonNullable<string | PetOutput>;
export type ShowPetTextResourceResult = NonNullable<string>;
export type DownloadFileResourceResult = NonNullable<Blob>;

export type CreatePetsClientResult = NonNullable<void>;
export type UpdatePetByIdClientResult = NonNullable<Pet | string>;
export type PatchPetByIdClientResult = NonNullable<Pet | string>;
export type UploadFileClientResult = NonNullable<void>;

/**
 * Utility type for httpResource results with status tracking.
 * Inspired by @angular-architects/ngrx-toolkit withResource pattern.
 *
 * Uses `globalThis.Error` to avoid collision with API model types named `Error`.
 */
export interface ResourceState<T> {
  readonly value: Signal<T | undefined>;
  readonly status: Signal<ResourceStatus>;
  readonly error: Signal<globalThis.Error | undefined>;
  readonly isLoading: Signal<boolean>;
  readonly hasValue: () => boolean;
  readonly reload: () => boolean;
}

/**
 * Wraps an HttpResourceRef to expose a consistent ResourceState interface.
 * Useful when integrating with NgRx SignalStore via withResource().
 */
export function toResourceState<T>(ref: HttpResourceRef<T>): ResourceState<T> {
  return {
    value: ref.value,
    status: ref.status,
    error: ref.error,
    isLoading: ref.isLoading,
    hasValue: () => ref.hasValue(),
    reload: () => ref.reload(),
  };
}
