/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Issue 3590 - binary response without response.imports
 * OpenAPI spec version: 1.0.0
 */
import { faker } from '@faker-js/faker';

export type getPetPhotoResponse200 = {
  data: Blob;
  status: 200;
};

export type getPetPhotoResponseSuccess = getPetPhotoResponse200 & {
  headers: Headers;
};
export type getPetPhotoResponse = getPetPhotoResponseSuccess;

export const getGetPetPhotoUrl = (petId: number) => {
  return `/pets/${petId}/photo`;
};

export const getPetPhoto = async (
  petId: number,
  options?: RequestInit,
): Promise<getPetPhotoResponse> => {
  const res = await fetch(getGetPetPhotoUrl(petId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.blob();
  const data: getPetPhotoResponse['data'] = body as getPetPhotoResponse['data'];
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as getPetPhotoResponse;
};

export const getGetPetPhotoResponseMock = (): ArrayBuffer =>
  new ArrayBuffer(faker.number.int({ min: 1, max: 64 }));
