/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Tags Split Shared Models
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const Pet = zod.object({
  id: zod.string(),
  name: zod.string(),
  tag: zod.string().optional(),
});

export type Pet = zod.input<typeof Pet>;
export type PetOutput = zod.output<typeof Pet>;
