/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import { HttpClient, HttpHeaders } from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams,
  HttpResponse as AngularHttpResponse,
} from '@angular/common/http';

import { Injectable, inject } from '@angular/core';

import { Observable } from 'rxjs';

import { Pet, Pets } from '../../model-zod/index.zod';
import type {
  CreatePetsBody,
  ListPetsParams,
  SearchPetsParams,
} from '../../model-zod/index.zod';

import { map } from 'rxjs';

interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
    | HttpParams
    | Record<
        string,
        string | number | boolean | Array<string | number | boolean>
      >;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: { includeHeaders?: string[] } | boolean;
}

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: Set<string> = new Set(),
): Record<
  string,
  string | number | boolean | Array<string | number | boolean>
> {
  const filteredParams: Record<
    string,
    string | number | boolean | null | Array<string | number | boolean>
  > = {};
  for (const [key, value] of Object.entries(params)) {
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' ||
            typeof item === 'number' ||
            typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (value === null && requiredNullableKeys.has(key)) {
      filteredParams[key] = value;
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value as string | number | boolean;
    }
  }
  return filteredParams as Record<
    string,
    string | number | boolean | Array<string | number | boolean>
  >;
}

@Injectable({ providedIn: 'root' })
export class PetsService {
  private readonly http = inject(HttpClient);
  /**
   * @summary Search pets by query params
   */
  searchPets<TData = Pets>(
    params: SearchPetsParams,
    options?: HttpClientOptions & { observe?: 'body' },
  ): Observable<TData>;
  searchPets<TData = Pets>(
    params: SearchPetsParams,
    options?: HttpClientOptions & { observe: 'events' },
  ): Observable<HttpEvent<TData>>;
  searchPets<TData = Pets>(
    params: SearchPetsParams,
    options?: HttpClientOptions & { observe: 'response' },
  ): Observable<AngularHttpResponse<TData>>;
  searchPets<TData = Pets>(
    params: SearchPetsParams,
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' },
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams(
      { ...params, ...options?.params },
      new Set<string>(['requirednullableString', 'requirednullableStringTwo']),
    );

    if (options?.observe === 'events') {
      return this.http.get<TData>(`/search`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams,
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/search`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams,
      });
    }

    return this.http
      .get<TData>(`/search`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
        params: filteredParams,
      })
      .pipe(map((data) => Pets.parse(data) as TData));
  }
  /**
   * @summary List all pets
   */
  listPets(
    accept: 'application/json',
    params?: ListPetsParams,
    options?: HttpClientOptions,
  ): Observable<Pets>;
  listPets(
    accept: 'application/xml',
    params?: ListPetsParams,
    options?: HttpClientOptions,
  ): Observable<string>;
  listPets(
    accept?: string,
    params?: ListPetsParams,
    options?: HttpClientOptions,
  ): Observable<Pets | string | Blob>;
  listPets(
    accept: string = 'application/json',
    params?: ListPetsParams,
    options?: HttpClientOptions,
  ): Observable<Pets | string | Blob> {
    const headers =
      options?.headers instanceof HttpHeaders
        ? options.headers.set('Accept', accept)
        : { ...(options?.headers ?? {}), Accept: accept };

    if (accept.includes('json') || accept.includes('+json')) {
      return this.http
        .get<Pets>(`/pets`, {
          ...options,
          responseType: 'json',
          headers,
        })
        .pipe(map((data) => Pets.parse(data)));
    } else if (accept.startsWith('text/') || accept.includes('xml')) {
      return this.http.get(`/pets`, {
        ...options,
        responseType: 'text',
        headers,
      }) as Observable<string>;
    } else {
      return this.http.get(`/pets`, {
        ...options,
        responseType: 'blob',
        headers,
      }) as Observable<Blob>;
    }
  }
  /**
   * @summary Create a pet
   */
  createPets<TData = void>(
    createPetsBody: CreatePetsBody,
    options?: HttpClientOptions & { observe?: 'body' },
  ): Observable<TData>;
  createPets<TData = void>(
    createPetsBody: CreatePetsBody,
    options?: HttpClientOptions & { observe: 'events' },
  ): Observable<HttpEvent<TData>>;
  createPets<TData = void>(
    createPetsBody: CreatePetsBody,
    options?: HttpClientOptions & { observe: 'response' },
  ): Observable<AngularHttpResponse<TData>>;
  createPets<TData = void>(
    createPetsBody: CreatePetsBody,
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' },
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(`/pets`, createPetsBody, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      });
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(`/pets`, createPetsBody, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      });
    }

    return this.http.post<TData>(`/pets`, createPetsBody, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
    });
  }
  /**
   * @summary Info for a specific pet
   */
  showPetById(
    petId: string,
    accept: 'text/plain',
    options?: HttpClientOptions,
  ): Observable<string>;
  showPetById(
    petId: string,
    accept: 'application/xml',
    options?: HttpClientOptions,
  ): Observable<string>;
  showPetById(
    petId: string,
    accept: 'application/json',
    options?: HttpClientOptions,
  ): Observable<Pet>;
  showPetById(
    petId: string,
    accept?: string,
    options?: HttpClientOptions,
  ): Observable<Pet | string | Blob>;
  showPetById(
    petId: string,
    accept: string = 'text/plain',
    options?: HttpClientOptions,
  ): Observable<Pet | string | Blob> {
    const headers =
      options?.headers instanceof HttpHeaders
        ? options.headers.set('Accept', accept)
        : { ...(options?.headers ?? {}), Accept: accept };

    if (accept.includes('json') || accept.includes('+json')) {
      return this.http
        .get<Pet>(`/pets/${petId}`, {
          ...options,
          responseType: 'json',
          headers,
        })
        .pipe(map((data) => Pet.parse(data)));
    } else if (accept.startsWith('text/') || accept.includes('xml')) {
      return this.http.get(`/pets/${petId}`, {
        ...options,
        responseType: 'text',
        headers,
      }) as Observable<string>;
    } else {
      return this.http.get(`/pets/${petId}`, {
        ...options,
        responseType: 'blob',
        headers,
      }) as Observable<Blob>;
    }
  }
  /**
   * @summary Info for a specific pet as plain text
   */
  showPetText(
    petId: string,
    options?: HttpClientOptions & { observe?: 'body' },
  ): Observable<string>;
  showPetText(
    petId: string,
    options?: HttpClientOptions & { observe: 'events' },
  ): Observable<HttpEvent<string>>;
  showPetText(
    petId: string,
    options?: HttpClientOptions & { observe: 'response' },
  ): Observable<AngularHttpResponse<string>>;
  showPetText(
    petId: string,
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' },
  ): Observable<string | HttpEvent<string> | AngularHttpResponse<string>> {
    if (options?.observe === 'events') {
      return this.http.get(`/pets/${petId}/text`, {
        responseType: 'text',
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      });
    }

    if (options?.observe === 'response') {
      return this.http.get(`/pets/${petId}/text`, {
        responseType: 'text',
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      });
    }

    return this.http.get(`/pets/${petId}/text`, {
      responseType: 'text',
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
    });
  }
  /**
   * Upload image of the pet.
   * @summary Uploads an image.
   */
  uploadFile<TData = void>(
    petId: number,
    uploadFileBody: Blob,
    options?: HttpClientOptions & { observe?: 'body' },
  ): Observable<TData>;
  uploadFile<TData = void>(
    petId: number,
    uploadFileBody: Blob,
    options?: HttpClientOptions & { observe: 'events' },
  ): Observable<HttpEvent<TData>>;
  uploadFile<TData = void>(
    petId: number,
    uploadFileBody: Blob,
    options?: HttpClientOptions & { observe: 'response' },
  ): Observable<AngularHttpResponse<TData>>;
  uploadFile<TData = void>(
    petId: number,
    uploadFileBody: Blob,
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' },
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(
        `/pet/${petId}/uploadImage`,
        uploadFileBody,
        {
          ...(options as Omit<NonNullable<typeof options>, 'observe'>),
          observe: 'events',
        },
      );
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(
        `/pet/${petId}/uploadImage`,
        uploadFileBody,
        {
          ...(options as Omit<NonNullable<typeof options>, 'observe'>),
          observe: 'response',
        },
      );
    }

    return this.http.post<TData>(`/pet/${petId}/uploadImage`, uploadFileBody, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
    });
  }
  /**
   * Download image of the pet.
   * @summary Download an image.
   */
  downloadFile(
    petId: number,
    options?: HttpClientOptions & { observe?: 'body' },
  ): Observable<Blob>;
  downloadFile(
    petId: number,
    options?: HttpClientOptions & { observe: 'events' },
  ): Observable<HttpEvent<Blob>>;
  downloadFile(
    petId: number,
    options?: HttpClientOptions & { observe: 'response' },
  ): Observable<AngularHttpResponse<Blob>>;
  downloadFile(
    petId: number,
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' },
  ): Observable<Blob | HttpEvent<Blob> | AngularHttpResponse<Blob>> {
    if (options?.observe === 'events') {
      return this.http.get(`/pet/${petId}/downloadImage`, {
        responseType: 'blob',
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      });
    }

    if (options?.observe === 'response') {
      return this.http.get(`/pet/${petId}/downloadImage`, {
        responseType: 'blob',
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      });
    }

    return this.http.get(`/pet/${petId}/downloadImage`, {
      responseType: 'blob',
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
    });
  }
}
