/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useQuery } from '@tanstack/solid-query';
import type {
  DataTag,
  DefinedInitialDataInfiniteOptions,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  SolidInfiniteQueryOptions,
  SolidQueryOptions,
  UndefinedInitialDataInfiniteOptions,
  UndefinedInitialDataOptions,
  UseInfiniteQueryResult,
  UseQueryResult,
} from '@tanstack/solid-query';

import { mergeProps } from 'solid-js';

import type {
  CreatePetsBody,
  CreatePetsParams,
  Error,
  ListPetsParams,
  Pet,
  PetWithTag,
  Pets,
} from './model';

import { faker } from '@faker-js/faker';

import { HttpResponse, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import type { Cat, Dachshund, Dog, Labradoodle } from './model';

export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx =
  | 400
  | 401
  | 402
  | 403
  | 404
  | 405
  | 406
  | 407
  | 408
  | 409
  | 410
  | 411
  | 412
  | 413
  | 414
  | 415
  | 416
  | 417
  | 418
  | 419
  | 420
  | 421
  | 422
  | 423
  | 424
  | 426
  | 428
  | 429
  | 431
  | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes =
  | HTTPStatusCode1xx
  | HTTPStatusCode2xx
  | HTTPStatusCode3xx
  | HTTPStatusCode4xx
  | HTTPStatusCode5xx;

export type listPetsResponse200 = {
  data: Pets;
  status: 200;
};

export type listPetsResponseDefault = {
  data: Error;
  status: Exclude<HTTPStatusCodes, 200>;
};

export type listPetsResponseSuccess = listPetsResponse200 & {
  headers: Headers;
};
export type listPetsResponseError = listPetsResponseDefault & {
  headers: Headers;
};

export type listPetsResponse = listPetsResponseSuccess | listPetsResponseError;

export const getListPetsUrl = (params: ListPetsParams, version: number = 1) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v${version}/pets?${stringifiedParams}`
    : `/v${version}/pets`;
};

/**
 * @summary List all pets
 */
export const listPets = async (
  params: ListPetsParams,
  version: number = 1,
  options?: RequestInit,
): Promise<listPetsResponse> => {
  const res = await fetch(getListPetsUrl(params, version), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listPetsResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as listPetsResponse;
};

export const getListPetsInfiniteQueryKey = (
  params?: ListPetsParams,
  version: number = 1,
) => {
  return [
    'infinite',
    `/v${version}/pets`,
    ...(params ? [params] : []),
  ] as const;
};

export const getListPetsQueryKey = (
  params?: ListPetsParams,
  version: number = 1,
) => {
  return [`/v${version}/pets`, ...(params ? [params] : [])] as const;
};

export const getListPetsInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof listPets>>,
    ListPetsParams['limit']
  >,
  TError = Error,
>(
  params: ListPetsParams,
  version: number = 1,
  options: {
    query: Omit<
      Partial<
        SolidInfiniteQueryOptions<
          Awaited<ReturnType<typeof listPets>>,
          TError,
          TData,
          QueryKey,
          ListPetsParams['limit']
        >
      >,
      'initialPageParam' | 'getNextPageParam' | 'initialData'
    > &
      Pick<
        SolidInfiniteQueryOptions<
          Awaited<ReturnType<typeof listPets>>,
          TError,
          TData,
          QueryKey,
          ListPetsParams['limit']
        >,
        'initialPageParam' | 'getNextPageParam'
      >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = getListPetsInfiniteQueryKey(params, version);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listPets>>,
    QueryKey,
    ListPetsParams['limit']
  > = ({ signal, pageParam }) =>
    listPets({ ...params, limit: pageParam ?? params?.['limit'] }, version, {
      signal,
      ...fetchOptions,
    });

  return {
    queryKey,
    queryFn,
    enabled: version !== null && version !== undefined,
    ...queryOptions,
  };
};

export type ListPetsInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof listPets>>
>;
export type ListPetsInfiniteQueryError = Error;

export function useListPetsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof listPets>>,
    ListPetsParams['limit']
  >,
  TError = Error,
>(
  params: ListPetsParams,
  version: undefined | number,
  options: {
    query: Omit<
      Partial<
        SolidInfiniteQueryOptions<
          Awaited<ReturnType<typeof listPets>>,
          TError,
          TData,
          QueryKey,
          ListPetsParams['limit']
        >
      >,
      'initialPageParam' | 'getNextPageParam' | 'initialData'
    > &
      Pick<
        SolidInfiniteQueryOptions<
          Awaited<ReturnType<typeof listPets>>,
          TError,
          TData,
          QueryKey,
          ListPetsParams['limit']
        >,
        'initialPageParam' | 'getNextPageParam'
      > &
      Pick<
        ReturnType<
          DefinedInitialDataInfiniteOptions<
            Awaited<ReturnType<typeof listPets>>,
            TError,
            TData,
            QueryKey,
            ListPetsParams['limit']
          >
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListPetsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof listPets>>,
    ListPetsParams['limit']
  >,
  TError = Error,
>(
  params: ListPetsParams,
  version: undefined | number,
  options: {
    query: Omit<
      Partial<
        SolidInfiniteQueryOptions<
          Awaited<ReturnType<typeof listPets>>,
          TError,
          TData,
          QueryKey,
          ListPetsParams['limit']
        >
      >,
      'initialPageParam' | 'getNextPageParam' | 'initialData'
    > &
      Pick<
        SolidInfiniteQueryOptions<
          Awaited<ReturnType<typeof listPets>>,
          TError,
          TData,
          QueryKey,
          ListPetsParams['limit']
        >,
        'initialPageParam' | 'getNextPageParam'
      > &
      Pick<
        ReturnType<
          UndefinedInitialDataInfiniteOptions<
            Awaited<ReturnType<typeof listPets>>,
            TError,
            TData,
            QueryKey,
            ListPetsParams['limit']
          >
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListPetsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof listPets>>,
    ListPetsParams['limit']
  >,
  TError = Error,
>(
  params: ListPetsParams,
  version: undefined | number,
  options: {
    query: Omit<
      Partial<
        SolidInfiniteQueryOptions<
          Awaited<ReturnType<typeof listPets>>,
          TError,
          TData,
          QueryKey,
          ListPetsParams['limit']
        >
      >,
      'initialPageParam' | 'getNextPageParam' | 'initialData'
    > &
      Pick<
        SolidInfiniteQueryOptions<
          Awaited<ReturnType<typeof listPets>>,
          TError,
          TData,
          QueryKey,
          ListPetsParams['limit']
        >,
        'initialPageParam' | 'getNextPageParam'
      >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List all pets
 */

export function useListPetsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof listPets>>,
    ListPetsParams['limit']
  >,
  TError = Error,
>(
  params: ListPetsParams,
  version: number = 1,
  options: {
    query: Omit<
      Partial<
        SolidInfiniteQueryOptions<
          Awaited<ReturnType<typeof listPets>>,
          TError,
          TData,
          QueryKey,
          ListPetsParams['limit']
        >
      >,
      'initialPageParam' | 'getNextPageParam' | 'initialData'
    > &
      Pick<
        SolidInfiniteQueryOptions<
          Awaited<ReturnType<typeof listPets>>,
          TError,
          TData,
          QueryKey,
          ListPetsParams['limit']
        >,
        'initialPageParam' | 'getNextPageParam'
      >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListPetsInfiniteQueryOptions(
    params,
    version,
    options,
  );

  const query = useInfiniteQuery(
    () => getListPetsInfiniteQueryOptions(params, version, options),
    queryClient,
  );

  return mergeProps(query, { queryKey: queryOptions.queryKey }) as any;
}

export const getListPetsQueryOptions = <
  TData = Awaited<ReturnType<typeof listPets>>,
  TError = Error,
>(
  params: ListPetsParams,
  version: number = 1,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<Awaited<ReturnType<typeof listPets>>, TError, TData>
      >,
      'initialData'
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = getListPetsQueryKey(params, version);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listPets>>> = ({
    signal,
  }) => listPets(params, version, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: version !== null && version !== undefined,
    ...queryOptions,
  };
};

export type ListPetsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listPets>>
>;
export type ListPetsQueryError = Error;

export function useListPets<
  TData = Awaited<ReturnType<typeof listPets>>,
  TError = Error,
>(
  params: ListPetsParams,
  version: undefined | number,
  options: {
    query: Omit<
      Partial<
        SolidQueryOptions<Awaited<ReturnType<typeof listPets>>, TError, TData>
      >,
      'initialData'
    > &
      Pick<
        ReturnType<
          DefinedInitialDataOptions<
            Awaited<ReturnType<typeof listPets>>,
            TError,
            TData
          >
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListPets<
  TData = Awaited<ReturnType<typeof listPets>>,
  TError = Error,
>(
  params: ListPetsParams,
  version?: number,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<Awaited<ReturnType<typeof listPets>>, TError, TData>
      >,
      'initialData'
    > &
      Pick<
        ReturnType<
          UndefinedInitialDataOptions<
            Awaited<ReturnType<typeof listPets>>,
            TError,
            TData
          >
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListPets<
  TData = Awaited<ReturnType<typeof listPets>>,
  TError = Error,
>(
  params: ListPetsParams,
  version?: number,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<Awaited<ReturnType<typeof listPets>>, TError, TData>
      >,
      'initialData'
    >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List all pets
 */

export function useListPets<
  TData = Awaited<ReturnType<typeof listPets>>,
  TError = Error,
>(
  params: ListPetsParams,
  version: number = 1,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<Awaited<ReturnType<typeof listPets>>, TError, TData>
      >,
      'initialData'
    >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListPetsQueryOptions(params, version, options);

  const query = useQuery(
    () => getListPetsQueryOptions(params, version, options),
    queryClient,
  );

  return mergeProps(query, { queryKey: queryOptions.queryKey }) as any;
}

export type createPetsResponse200 = {
  data: Pet;
  status: 200;
};

export type createPetsResponseDefault = {
  data: Error;
  status: Exclude<HTTPStatusCodes, 200>;
};

export type createPetsResponseSuccess = createPetsResponse200 & {
  headers: Headers;
};
export type createPetsResponseError = createPetsResponseDefault & {
  headers: Headers;
};

export type createPetsResponse =
  | createPetsResponseSuccess
  | createPetsResponseError;

export const getCreatePetsUrl = (
  params: CreatePetsParams,
  version: number = 1,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v${version}/pets?${stringifiedParams}`
    : `/v${version}/pets`;
};

/**
 * @summary Create a pet
 */
export const createPets = async (
  createPetsBody: CreatePetsBody,
  params: CreatePetsParams,
  version: number = 1,
  options?: RequestInit,
): Promise<createPetsResponse> => {
  const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
  const res = await fetch(getCreatePetsUrl(params, version), {
    ...options,
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(createPetsBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createPetsResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as createPetsResponse;
};

export const getCreatePetsQueryKey = (
  createPetsBody?: CreatePetsBody,
  params?: CreatePetsParams,
  version: number = 1,
) => {
  return [
    'POST',
    `/v${version}/pets`,
    ...(params ? [params] : []),
    createPetsBody,
  ] as const;
};

export const getCreatePetsQueryOptions = <
  TData = Awaited<ReturnType<typeof createPets>>,
  TError = Error,
>(
  createPetsBody: CreatePetsBody,
  params: CreatePetsParams,
  version: number = 1,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<Awaited<ReturnType<typeof createPets>>, TError, TData>
      >,
      'initialData'
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = getCreatePetsQueryKey(createPetsBody, params, version);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof createPets>>> = ({
    signal,
  }) =>
    createPets(createPetsBody, params, version, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: version !== null && version !== undefined,
    ...queryOptions,
  };
};

export type CreatePetsQueryResult = NonNullable<
  Awaited<ReturnType<typeof createPets>>
>;
export type CreatePetsQueryError = Error;

export function useCreatePets<
  TData = Awaited<ReturnType<typeof createPets>>,
  TError = Error,
>(
  createPetsBody: CreatePetsBody,
  params: CreatePetsParams,
  version: undefined | number,
  options: {
    query: Omit<
      Partial<
        SolidQueryOptions<Awaited<ReturnType<typeof createPets>>, TError, TData>
      >,
      'initialData'
    > &
      Pick<
        ReturnType<
          DefinedInitialDataOptions<
            Awaited<ReturnType<typeof createPets>>,
            TError,
            TData
          >
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCreatePets<
  TData = Awaited<ReturnType<typeof createPets>>,
  TError = Error,
>(
  createPetsBody: CreatePetsBody,
  params: CreatePetsParams,
  version?: number,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<Awaited<ReturnType<typeof createPets>>, TError, TData>
      >,
      'initialData'
    > &
      Pick<
        ReturnType<
          UndefinedInitialDataOptions<
            Awaited<ReturnType<typeof createPets>>,
            TError,
            TData
          >
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCreatePets<
  TData = Awaited<ReturnType<typeof createPets>>,
  TError = Error,
>(
  createPetsBody: CreatePetsBody,
  params: CreatePetsParams,
  version?: number,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<Awaited<ReturnType<typeof createPets>>, TError, TData>
      >,
      'initialData'
    >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Create a pet
 */

export function useCreatePets<
  TData = Awaited<ReturnType<typeof createPets>>,
  TError = Error,
>(
  createPetsBody: CreatePetsBody,
  params: CreatePetsParams,
  version: number = 1,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<Awaited<ReturnType<typeof createPets>>, TError, TData>
      >,
      'initialData'
    >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCreatePetsQueryOptions(
    createPetsBody,
    params,
    version,
    options,
  );

  const query = useQuery(
    () => getCreatePetsQueryOptions(createPetsBody, params, version, options),
    queryClient,
  );

  return mergeProps(query, { queryKey: queryOptions.queryKey }) as any;
}

export type showPetByIdResponse200 = {
  data: Pet;
  status: 200;
};

export type showPetByIdResponseDefault = {
  data: Error;
  status: Exclude<HTTPStatusCodes, 200>;
};

export type showPetByIdResponseSuccess = showPetByIdResponse200 & {
  headers: Headers;
};
export type showPetByIdResponseError = showPetByIdResponseDefault & {
  headers: Headers;
};

export type showPetByIdResponse =
  | showPetByIdResponseSuccess
  | showPetByIdResponseError;

export const getShowPetByIdUrl = (petId: string, version: number = 1) => {
  return `/v${version}/pets/${petId}`;
};

/**
 * @summary Info for a specific pet
 */
export const showPetById = async (
  petId: string,
  version: number = 1,
  options?: RequestInit,
): Promise<showPetByIdResponse> => {
  const res = await fetch(getShowPetByIdUrl(petId, version), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: showPetByIdResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as showPetByIdResponse;
};

export const getShowPetByIdQueryKey = (petId: string, version: number = 1) => {
  return [`/v${version}/pets/${petId}`] as const;
};

export const getShowPetByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof showPetById>>,
  TError = Error,
>(
  petId: string,
  version: number = 1,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof showPetById>>,
          TError,
          TData
        >
      >,
      'initialData'
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = getShowPetByIdQueryKey(petId, version);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof showPetById>>> = ({
    signal,
  }) => showPetById(petId, version, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled:
      version !== null &&
      version !== undefined &&
      petId !== null &&
      petId !== undefined,
    ...queryOptions,
  };
};

export type ShowPetByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof showPetById>>
>;
export type ShowPetByIdQueryError = Error;

export function useShowPetById<
  TData = Awaited<ReturnType<typeof showPetById>>,
  TError = Error,
>(
  petId: string,
  version: undefined | number,
  options: {
    query: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof showPetById>>,
          TError,
          TData
        >
      >,
      'initialData'
    > &
      Pick<
        ReturnType<
          DefinedInitialDataOptions<
            Awaited<ReturnType<typeof showPetById>>,
            TError,
            TData
          >
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useShowPetById<
  TData = Awaited<ReturnType<typeof showPetById>>,
  TError = Error,
>(
  petId: string,
  version?: number,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof showPetById>>,
          TError,
          TData
        >
      >,
      'initialData'
    > &
      Pick<
        ReturnType<
          UndefinedInitialDataOptions<
            Awaited<ReturnType<typeof showPetById>>,
            TError,
            TData
          >
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useShowPetById<
  TData = Awaited<ReturnType<typeof showPetById>>,
  TError = Error,
>(
  petId: string,
  version?: number,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof showPetById>>,
          TError,
          TData
        >
      >,
      'initialData'
    >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Info for a specific pet
 */

export function useShowPetById<
  TData = Awaited<ReturnType<typeof showPetById>>,
  TError = Error,
>(
  petId: string,
  version: number = 1,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof showPetById>>,
          TError,
          TData
        >
      >,
      'initialData'
    >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getShowPetByIdQueryOptions(petId, version, options);

  const query = useQuery(
    () => getShowPetByIdQueryOptions(petId, version, options),
    queryClient,
  );

  return mergeProps(query, { queryKey: queryOptions.queryKey }) as any;
}

export type deletePetByIdResponse204 = {
  data: void;
  status: 204;
};

export type deletePetByIdResponseDefault = {
  data: Error;
  status: Exclude<HTTPStatusCodes, 204>;
};

export type deletePetByIdResponseSuccess = deletePetByIdResponse204 & {
  headers: Headers;
};
export type deletePetByIdResponseError = deletePetByIdResponseDefault & {
  headers: Headers;
};

export type deletePetByIdResponse =
  | deletePetByIdResponseSuccess
  | deletePetByIdResponseError;

export const getDeletePetByIdUrl = (petId: string, version: number = 1) => {
  return `/v${version}/pets/${petId}`;
};

/**
 * @summary Deletes a specific pet
 */
export const deletePetById = async (
  petId: string,
  version: number = 1,
  options?: RequestInit,
): Promise<deletePetByIdResponse> => {
  const res = await fetch(getDeletePetByIdUrl(petId, version), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deletePetByIdResponse['data'] = body
    ? JSON.parse(body)
    : undefined;
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deletePetByIdResponse;
};

export const getDeletePetByIdQueryKey = (
  petId: string,
  version: number = 1,
) => {
  return ['DELETE', `/v${version}/pets/${petId}`] as const;
};

export const getDeletePetByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof deletePetById>>,
  TError = Error,
>(
  petId: string,
  version: number = 1,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof deletePetById>>,
          TError,
          TData
        >
      >,
      'initialData'
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = getDeletePetByIdQueryKey(petId, version);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof deletePetById>>> = ({
    signal,
  }) => deletePetById(petId, version, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled:
      version !== null &&
      version !== undefined &&
      petId !== null &&
      petId !== undefined,
    ...queryOptions,
  };
};

export type DeletePetByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof deletePetById>>
>;
export type DeletePetByIdQueryError = Error;

export function useDeletePetById<
  TData = Awaited<ReturnType<typeof deletePetById>>,
  TError = Error,
>(
  petId: string,
  version: undefined | number,
  options: {
    query: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof deletePetById>>,
          TError,
          TData
        >
      >,
      'initialData'
    > &
      Pick<
        ReturnType<
          DefinedInitialDataOptions<
            Awaited<ReturnType<typeof deletePetById>>,
            TError,
            TData
          >
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeletePetById<
  TData = Awaited<ReturnType<typeof deletePetById>>,
  TError = Error,
>(
  petId: string,
  version?: number,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof deletePetById>>,
          TError,
          TData
        >
      >,
      'initialData'
    > &
      Pick<
        ReturnType<
          UndefinedInitialDataOptions<
            Awaited<ReturnType<typeof deletePetById>>,
            TError,
            TData
          >
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDeletePetById<
  TData = Awaited<ReturnType<typeof deletePetById>>,
  TError = Error,
>(
  petId: string,
  version?: number,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof deletePetById>>,
          TError,
          TData
        >
      >,
      'initialData'
    >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Deletes a specific pet
 */

export function useDeletePetById<
  TData = Awaited<ReturnType<typeof deletePetById>>,
  TError = Error,
>(
  petId: string,
  version: number = 1,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof deletePetById>>,
          TError,
          TData
        >
      >,
      'initialData'
    >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDeletePetByIdQueryOptions(petId, version, options);

  const query = useQuery(
    () => getDeletePetByIdQueryOptions(petId, version, options),
    queryClient,
  );

  return mergeProps(query, { queryKey: queryOptions.queryKey }) as any;
}

export type healthCheckResponse200 = {
  data: string;
  status: 200;
};

export type healthCheckResponseDefault = {
  data: Error;
  status: Exclude<HTTPStatusCodes, 200>;
};

export type healthCheckResponseSuccess = healthCheckResponse200 & {
  headers: Headers;
};
export type healthCheckResponseError = healthCheckResponseDefault & {
  headers: Headers;
};

export type healthCheckResponse =
  | healthCheckResponseSuccess
  | healthCheckResponseError;

export const getHealthCheckUrl = (version: number = 1) => {
  return `/v${version}/health`;
};

/**
 * @summary health check
 */
export const healthCheck = async (
  version: number = 1,
  options?: RequestInit,
): Promise<healthCheckResponse> => {
  const res = await fetch(getHealthCheckUrl(version), {
    ...options,
    method: 'GET',
  });

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: healthCheckResponse['data'] = body
    ? contentType.includes('json')
      ? JSON.parse(body)
      : body
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as healthCheckResponse;
};

export const getHealthCheckQueryKey = (version: number = 1) => {
  return [`/v${version}/health`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = Error,
>(
  version: number = 1,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof healthCheck>>,
          TError,
          TData
        >
      >,
      'initialData'
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = getHealthCheckQueryKey(version);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck(version, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: version !== null && version !== undefined,
    ...queryOptions,
  };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = Error;

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = Error,
>(
  version: undefined | number,
  options: {
    query: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof healthCheck>>,
          TError,
          TData
        >
      >,
      'initialData'
    > &
      Pick<
        ReturnType<
          DefinedInitialDataOptions<
            Awaited<ReturnType<typeof healthCheck>>,
            TError,
            TData
          >
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = Error,
>(
  version?: number,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof healthCheck>>,
          TError,
          TData
        >
      >,
      'initialData'
    > &
      Pick<
        ReturnType<
          UndefinedInitialDataOptions<
            Awaited<ReturnType<typeof healthCheck>>,
            TError,
            TData
          >
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = Error,
>(
  version?: number,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof healthCheck>>,
          TError,
          TData
        >
      >,
      'initialData'
    >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = Error,
>(
  version: number = 1,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof healthCheck>>,
          TError,
          TData
        >
      >,
      'initialData'
    >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getHealthCheckQueryOptions(version, options);

  const query = useQuery(
    () => getHealthCheckQueryOptions(version, options),
    queryClient,
  );

  return mergeProps(query, { queryKey: queryOptions.queryKey }) as any;
}

export type showPetWithOwnerResponse200 = {
  data: PetWithTag;
  status: 200;
};

export type showPetWithOwnerResponseDefault = {
  data: Error;
  status: Exclude<HTTPStatusCodes, 200>;
};

export type showPetWithOwnerResponseSuccess = showPetWithOwnerResponse200 & {
  headers: Headers;
};
export type showPetWithOwnerResponseError = showPetWithOwnerResponseDefault & {
  headers: Headers;
};

export type showPetWithOwnerResponse =
  | showPetWithOwnerResponseSuccess
  | showPetWithOwnerResponseError;

export const getShowPetWithOwnerUrl = (petId: string, version: number = 1) => {
  return `/v${version}/pets/${petId}/owner`;
};

/**
 * @summary combinate nullable and $ref
 */
export const showPetWithOwner = async (
  petId: string,
  version: number = 1,
  options?: RequestInit,
): Promise<showPetWithOwnerResponse> => {
  const res = await fetch(getShowPetWithOwnerUrl(petId, version), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: showPetWithOwnerResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as showPetWithOwnerResponse;
};

export const getShowPetWithOwnerQueryKey = (
  petId: string,
  version: number = 1,
) => {
  return [`/v${version}/pets/${petId}/owner`] as const;
};

export const getShowPetWithOwnerQueryOptions = <
  TData = Awaited<ReturnType<typeof showPetWithOwner>>,
  TError = Error,
>(
  petId: string,
  version: number = 1,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof showPetWithOwner>>,
          TError,
          TData
        >
      >,
      'initialData'
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = getShowPetWithOwnerQueryKey(petId, version);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof showPetWithOwner>>
  > = ({ signal }) =>
    showPetWithOwner(petId, version, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled:
      version !== null &&
      version !== undefined &&
      petId !== null &&
      petId !== undefined,
    ...queryOptions,
  };
};

export type ShowPetWithOwnerQueryResult = NonNullable<
  Awaited<ReturnType<typeof showPetWithOwner>>
>;
export type ShowPetWithOwnerQueryError = Error;

export function useShowPetWithOwner<
  TData = Awaited<ReturnType<typeof showPetWithOwner>>,
  TError = Error,
>(
  petId: string,
  version: undefined | number,
  options: {
    query: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof showPetWithOwner>>,
          TError,
          TData
        >
      >,
      'initialData'
    > &
      Pick<
        ReturnType<
          DefinedInitialDataOptions<
            Awaited<ReturnType<typeof showPetWithOwner>>,
            TError,
            TData
          >
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useShowPetWithOwner<
  TData = Awaited<ReturnType<typeof showPetWithOwner>>,
  TError = Error,
>(
  petId: string,
  version?: number,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof showPetWithOwner>>,
          TError,
          TData
        >
      >,
      'initialData'
    > &
      Pick<
        ReturnType<
          UndefinedInitialDataOptions<
            Awaited<ReturnType<typeof showPetWithOwner>>,
            TError,
            TData
          >
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useShowPetWithOwner<
  TData = Awaited<ReturnType<typeof showPetWithOwner>>,
  TError = Error,
>(
  petId: string,
  version?: number,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof showPetWithOwner>>,
          TError,
          TData
        >
      >,
      'initialData'
    >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary combinate nullable and $ref
 */

export function useShowPetWithOwner<
  TData = Awaited<ReturnType<typeof showPetWithOwner>>,
  TError = Error,
>(
  petId: string,
  version: number = 1,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof showPetWithOwner>>,
          TError,
          TData
        >
      >,
      'initialData'
    >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getShowPetWithOwnerQueryOptions(petId, version, options);

  const query = useQuery(
    () => getShowPetWithOwnerQueryOptions(petId, version, options),
    queryClient,
  );

  return mergeProps(query, { queryKey: queryOptions.queryKey }) as any;
}

export const getListPetsResponseLabradoodleMock = (
  overrideResponse: Partial<Labradoodle> = {},
): Labradoodle => ({
  ...{
    cuteness: faker.number.int(),
    breed: faker.helpers.arrayElement(['Labradoodle'] as const),
  },
  ...overrideResponse,
});

export const getListPetsResponseDachshundMock = (
  overrideResponse: Partial<Dachshund> = {},
): Dachshund => ({
  ...{
    length: faker.number.int(),
    breed: faker.helpers.arrayElement(['Dachshund'] as const),
  },
  ...overrideResponse,
});

export const getListPetsResponseDogMock = (
  overrideResponse: Omit<Partial<Dog>, 'breed'> = {},
): Dog => ({
  ...{
    ...faker.helpers.arrayElement([
      { ...getListPetsResponseLabradoodleMock() },
      { ...getListPetsResponseDachshundMock() },
    ]),
    barksPerMinute: faker.helpers.arrayElement([faker.number.int(), undefined]),
    type: faker.helpers.arrayElement(['dog'] as const),
  },
  ...overrideResponse,
});

export const getListPetsResponseCatMock = (
  overrideResponse: Partial<Cat> = {},
): Cat => ({
  ...{
    petsRequested: faker.helpers.arrayElement([faker.number.int(), undefined]),
    type: faker.helpers.arrayElement(['cat'] as const),
  },
  ...overrideResponse,
});

export const getListPetsResponseMock = (): Pets =>
  Array.from(
    { length: faker.number.int({ min: 1, max: 10 }) },
    (_, i) => i + 1,
  ).map(() => ({
    ...faker.helpers.arrayElement([
      { ...getListPetsResponseDogMock() },
      { ...getListPetsResponseCatMock() },
    ]),
    '@id': faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    id: faker.number.int(),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    tag: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    email: faker.helpers.arrayElement([faker.internet.email(), undefined]),
    callingCode: faker.helpers.arrayElement([
      faker.helpers.arrayElement(['+33', '+420', '+33'] as const),
      undefined,
    ]),
    country: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        "People's Republic of China",
        'Uruguay',
      ] as const),
      undefined,
    ]),
  }));

export const getCreatePetsResponseLabradoodleMock = (
  overrideResponse: Partial<Labradoodle> = {},
): Labradoodle => ({
  ...{
    cuteness: faker.number.int(),
    breed: faker.helpers.arrayElement(['Labradoodle'] as const),
  },
  ...overrideResponse,
});

export const getCreatePetsResponseDachshundMock = (
  overrideResponse: Partial<Dachshund> = {},
): Dachshund => ({
  ...{
    length: faker.number.int(),
    breed: faker.helpers.arrayElement(['Dachshund'] as const),
  },
  ...overrideResponse,
});

export const getCreatePetsResponseDogMock = (
  overrideResponse: Omit<Partial<Dog>, 'breed'> = {},
): Dog => ({
  ...{
    ...faker.helpers.arrayElement([
      { ...getCreatePetsResponseLabradoodleMock() },
      { ...getCreatePetsResponseDachshundMock() },
    ]),
    barksPerMinute: faker.helpers.arrayElement([faker.number.int(), undefined]),
    type: faker.helpers.arrayElement(['dog'] as const),
  },
  ...overrideResponse,
});

export const getCreatePetsResponseCatMock = (
  overrideResponse: Partial<Cat> = {},
): Cat => ({
  ...{
    petsRequested: faker.helpers.arrayElement([faker.number.int(), undefined]),
    type: faker.helpers.arrayElement(['cat'] as const),
  },
  ...overrideResponse,
});

export const getCreatePetsResponseMock = (): Pet => ({
  ...faker.helpers.arrayElement([
    { ...getCreatePetsResponseDogMock() },
    { ...getCreatePetsResponseCatMock() },
  ]),
  '@id': faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  id: faker.number.int(),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  tag: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  email: faker.helpers.arrayElement([faker.internet.email(), undefined]),
  callingCode: faker.helpers.arrayElement([
    faker.helpers.arrayElement(['+33', '+420', '+33'] as const),
    undefined,
  ]),
  country: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      "People's Republic of China",
      'Uruguay',
    ] as const),
    undefined,
  ]),
});

export const getShowPetByIdResponseLabradoodleMock = (
  overrideResponse: Partial<Labradoodle> = {},
): Labradoodle => ({
  ...{
    cuteness: faker.number.int(),
    breed: faker.helpers.arrayElement(['Labradoodle'] as const),
  },
  ...overrideResponse,
});

export const getShowPetByIdResponseDachshundMock = (
  overrideResponse: Partial<Dachshund> = {},
): Dachshund => ({
  ...{
    length: faker.number.int(),
    breed: faker.helpers.arrayElement(['Dachshund'] as const),
  },
  ...overrideResponse,
});

export const getShowPetByIdResponseDogMock = (
  overrideResponse: Omit<Partial<Dog>, 'breed'> = {},
): Dog => ({
  ...{
    ...faker.helpers.arrayElement([
      { ...getShowPetByIdResponseLabradoodleMock() },
      { ...getShowPetByIdResponseDachshundMock() },
    ]),
    barksPerMinute: faker.helpers.arrayElement([faker.number.int(), undefined]),
    type: faker.helpers.arrayElement(['dog'] as const),
  },
  ...overrideResponse,
});

export const getShowPetByIdResponseCatMock = (
  overrideResponse: Partial<Cat> = {},
): Cat => ({
  ...{
    petsRequested: faker.helpers.arrayElement([faker.number.int(), undefined]),
    type: faker.helpers.arrayElement(['cat'] as const),
  },
  ...overrideResponse,
});

export const getShowPetByIdResponseMock = (): Pet => ({
  ...faker.helpers.arrayElement([
    { ...getShowPetByIdResponseDogMock() },
    { ...getShowPetByIdResponseCatMock() },
  ]),
  '@id': faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  id: faker.number.int(),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  tag: faker.helpers.arrayElement([
    faker.string.alpha({ length: { min: 10, max: 20 } }),
    undefined,
  ]),
  email: faker.helpers.arrayElement([faker.internet.email(), undefined]),
  callingCode: faker.helpers.arrayElement([
    faker.helpers.arrayElement(['+33', '+420', '+33'] as const),
    undefined,
  ]),
  country: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      "People's Republic of China",
      'Uruguay',
    ] as const),
    undefined,
  ]),
});

export const getHealthCheckResponseMock = (): string => faker.word.sample();

export const getShowPetWithOwnerResponseLabradoodleMock = (
  overrideResponse: Partial<Labradoodle> = {},
): Labradoodle => ({
  ...{
    cuteness: faker.number.int(),
    breed: faker.helpers.arrayElement(['Labradoodle'] as const),
  },
  ...overrideResponse,
});

export const getShowPetWithOwnerResponseDachshundMock = (
  overrideResponse: Partial<Dachshund> = {},
): Dachshund => ({
  ...{
    length: faker.number.int(),
    breed: faker.helpers.arrayElement(['Dachshund'] as const),
  },
  ...overrideResponse,
});

export const getShowPetWithOwnerResponseDogMock = (
  overrideResponse: Omit<Partial<Dog>, 'breed'> = {},
): Dog => ({
  ...{
    ...faker.helpers.arrayElement([
      { ...getShowPetWithOwnerResponseLabradoodleMock() },
      { ...getShowPetWithOwnerResponseDachshundMock() },
    ]),
    barksPerMinute: faker.helpers.arrayElement([faker.number.int(), undefined]),
    type: faker.helpers.arrayElement(['dog'] as const),
  },
  ...overrideResponse,
});

export const getShowPetWithOwnerResponseCatMock = (
  overrideResponse: Partial<Cat> = {},
): Cat => ({
  ...{
    petsRequested: faker.helpers.arrayElement([faker.number.int(), undefined]),
    type: faker.helpers.arrayElement(['cat'] as const),
  },
  ...overrideResponse,
});

export const getShowPetWithOwnerResponseMock = (
  overrideResponse: Partial<Extract<PetWithTag, object>> = {},
): PetWithTag => ({
  tag: faker.string.alpha({ length: { min: 10, max: 20 } }),
  pet: {
    ...faker.helpers.arrayElement([
      { ...getShowPetWithOwnerResponseDogMock() },
      { ...getShowPetWithOwnerResponseCatMock() },
    ]),
    '@id': faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    id: faker.number.int(),
    name: faker.string.alpha({ length: { min: 10, max: 20 } }),
    tag: faker.helpers.arrayElement([
      faker.string.alpha({ length: { min: 10, max: 20 } }),
      undefined,
    ]),
    email: faker.helpers.arrayElement([faker.internet.email(), undefined]),
    callingCode: faker.helpers.arrayElement([
      faker.helpers.arrayElement(['+33', '+420', '+33'] as const),
      undefined,
    ]),
    country: faker.helpers.arrayElement([
      faker.helpers.arrayElement([
        "People's Republic of China",
        'Uruguay',
      ] as const),
      undefined,
    ]),
  },
  ...overrideResponse,
});

export const getListPetsMockHandler = (
  overrideResponse?:
    | Pets
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<Pets> | Pets),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/v:version/pets',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getListPetsResponseMock(),
        { status: 200, headers: { 'Content-Type': 'application/hal+json' } },
      );
    },
    options,
  );
};

export const getCreatePetsMockHandler = (
  overrideResponse?:
    | Pet
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<Pet> | Pet),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/v:version/pets',
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getCreatePetsResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getShowPetByIdMockHandler = (
  overrideResponse?:
    | Pet
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<Pet> | Pet),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/v:version/pets/:petId',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getShowPetByIdResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};

export const getDeletePetByIdMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.delete>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.delete(
    '*/v:version/pets/:petId',
    async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 204 });
    },
    options,
  );
};

export const getHealthCheckMockHandler = (
  overrideResponse?:
    | string
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<string> | string),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/v:version/health',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      const resolvedBody =
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getHealthCheckResponseMock();
      const textBody =
        typeof resolvedBody === 'string'
          ? resolvedBody
          : JSON.stringify(resolvedBody ?? null);
      return HttpResponse.text(textBody, { status: 200 });
    },
    options,
  );
};

export const getShowPetWithOwnerMockHandler = (
  overrideResponse?:
    | PetWithTag
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<PetWithTag> | PetWithTag),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/v:version/pets/:petId/owner',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getShowPetWithOwnerResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};
export const getSwaggerPetstoreMock = () => [
  getListPetsMockHandler(),
  getCreatePetsMockHandler(),
  getShowPetByIdMockHandler(),
  getDeletePetByIdMockHandler(),
  getHealthCheckMockHandler(),
  getShowPetWithOwnerMockHandler(),
];
