/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Enums Inline
 * Test spec with inline (dereferenced) enum properties
 * OpenAPI spec version: 1.0.0
 */
import { faker } from '@faker-js/faker';

import { HttpResponse, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';

import type { User } from '../model';

export const getGetUserResponseMock = (
  overrideResponse: Partial<Extract<User, object>> = {},
): User => ({
  id: faker.number.int(),
  name: faker.string.alpha({ length: { min: 10, max: 20 } }),
  countryCode: faker.helpers.arrayElement([
    faker.helpers.arrayElement([
      'US',
      'JP',
      'DE',
      'FR',
    ] as User['countryCode'][]),
    undefined,
  ]),
  language: faker.helpers.arrayElement([
    faker.helpers.arrayElement(['EN', 'JP'] as User['language'][]),
    undefined,
  ]),
  ...overrideResponse,
});

export const getGetUserMockHandler = (
  overrideResponse?:
    | User
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<User> | User),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    '*/api/user',
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      return HttpResponse.json(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetUserResponseMock(),
        { status: 200 },
      );
    },
    options,
  );
};
export const getUserMock = () => [getGetUserMockHandler()];
