/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Tags Split Shared Models
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

import { CreatePetBody, Pet, PetList } from '../model';

export const ListPetsQueryParams = zod.object({
  limit: zod.number().optional(),
  sort: zod.enum(['asc', 'desc']).optional(),
});

export const ListPetsResponse = PetList;

export const CreatePetBodySchema = CreatePetBody;

export const CreatePetResponse = Pet;

export const GetPetByIdParams = zod.object({
  petId: zod.string(),
});

export const GetPetByIdResponse = Pet;
