import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import type { RequestHandlerOptions } from 'msw';

/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * One Of Required Example
 * OpenAPI spec version: v1.0
 */
import axios from 'axios';
import { HttpResponse, http } from 'msw';

import type { RequestUser } from './model';

export const createUser = (
  requestUser: RequestUser,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<void>> => {
  return axios.post(`/users`, requestUser, options);
};

export type CreateUserResult = AxiosResponse<void>;

export const getCreateUserMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    '*/users',
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      if (typeof overrideResponse === 'function') {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 201 });
    },
    options,
  );
};
export const getOneOfRequiredExampleMock = () => [getCreateUserMockHandler()];
