/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * useDates only-date params
 * OpenAPI spec version: 0.0.0
 */
import type { ThingsList200, ThingsListParams } from './model';

export type thingsListResponse200 = {
  data: ThingsList200;
  status: 200;
};

export type thingsListResponseSuccess = thingsListResponse200 & {
  headers: Headers;
};
export type thingsListResponse = thingsListResponseSuccess;

export const getThingsListUrl = (params?: ThingsListParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(
        key,
        value === null
          ? 'null'
          : value instanceof Date
            ? value.toISOString()
            : String(value),
      );
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/things?${stringifiedParams}`
    : `/things`;
};

export const thingsList = async (
  params?: ThingsListParams,
  options?: RequestInit,
): Promise<thingsListResponse> => {
  const res = await fetch(getThingsListUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: thingsListResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as thingsListResponse;
};
