/**
 * Generated by orval v8.10.0 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

export const CreatePetsParams = zod.object({
  "limit": zod.string().optional(),
  "sort": zod.enum(['name', '-name', 'email', '-email'])
})

export type CreatePetsParams = zod.input<typeof CreatePetsParams>;
export type CreatePetsParamsOutput = zod.output<typeof CreatePetsParams>;
