/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * NestedArrays
 * OpenAPI spec version: 1.0.0
 */
import {
  z as zod
} from 'zod';

/**
 * @summary sample
 */
export const postApiSampleResponseItemsItemMin = 2;

export const postApiSampleResponseItemsItemMax = 5;


export const postApiSampleResponse = zod.object({
  "items": zod.array(zod.array(zod.string()).min(postApiSampleResponseItemsItemMin).max(postApiSampleResponseItemsItemMax))
})
