/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/solid-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  SolidMutationOptions,
  SolidQueryOptions,
  UndefinedInitialDataOptions,
  UseMutationResult,
  UseQueryResult,
} from '@tanstack/solid-query';

import { mergeProps } from 'solid-js';

import type {
  CreatePetsBody,
  CreatePetsParams,
  Error,
  ListPetsParams,
  Pet,
  PetWithTag,
  Pets,
} from '../model';

export const getListPetsUrl = (params: ListPetsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/pets?${stringifiedParams}` : `/pets`;
};

/**
 * @summary List all pets
 */
export const listPets = async (
  params: ListPetsParams,
  options?: RequestInit,
): Promise<Pets> => {
  const res = await fetch(getListPetsUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: Pets = body ? JSON.parse(body) : {};
  return data;
};

export const getListPetsQueryKey = (params?: ListPetsParams) => {
  return [`/pets`, ...(params ? [params] : [])] as const;
};

export const getListPetsQueryOptions = <
  TData = Awaited<ReturnType<typeof listPets>>,
  TError = Error,
>(
  params: ListPetsParams,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<Awaited<ReturnType<typeof listPets>>, TError, TData>
      >,
      'initialData'
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = getListPetsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listPets>>> = ({
    signal,
  }) => listPets(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions };
};

export type ListPetsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listPets>>
>;
export type ListPetsQueryError = Error;

export function useListPets<
  TData = Awaited<ReturnType<typeof listPets>>,
  TError = Error,
>(
  params: ListPetsParams,
  options: {
    query: Omit<
      Partial<
        SolidQueryOptions<Awaited<ReturnType<typeof listPets>>, TError, TData>
      >,
      'initialData'
    > &
      Pick<
        ReturnType<
          DefinedInitialDataOptions<
            Awaited<ReturnType<typeof listPets>>,
            TError,
            TData
          >
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListPets<
  TData = Awaited<ReturnType<typeof listPets>>,
  TError = Error,
>(
  params: ListPetsParams,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<Awaited<ReturnType<typeof listPets>>, TError, TData>
      >,
      'initialData'
    > &
      Pick<
        ReturnType<
          UndefinedInitialDataOptions<
            Awaited<ReturnType<typeof listPets>>,
            TError,
            TData
          >
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListPets<
  TData = Awaited<ReturnType<typeof listPets>>,
  TError = Error,
>(
  params: ListPetsParams,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<Awaited<ReturnType<typeof listPets>>, TError, TData>
      >,
      'initialData'
    >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List all pets
 */

export function useListPets<
  TData = Awaited<ReturnType<typeof listPets>>,
  TError = Error,
>(
  params: ListPetsParams,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<Awaited<ReturnType<typeof listPets>>, TError, TData>
      >,
      'initialData'
    >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListPetsQueryOptions(params, options);

  const query = useQuery(
    () => getListPetsQueryOptions(params, options),
    queryClient,
  );

  return mergeProps(query, { queryKey: queryOptions.queryKey }) as any;
}

export const getCreatePetsUrl = (params: CreatePetsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/pets?${stringifiedParams}` : `/pets`;
};

/**
 * @summary Create a pet
 */
export const createPets = async (
  createPetsBody: CreatePetsBody,
  params: CreatePetsParams,
  options?: RequestInit,
): Promise<Pet> => {
  const getHeaders = (h: HeadersInit | Headers): Record<string, string> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
  const res = await fetch(getCreatePetsUrl(params), {
    ...options,
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      ...getHeaders(options?.headers),
    },
    body: JSON.stringify(createPetsBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: Pet = body ? JSON.parse(body) : {};
  return data;
};

export const getCreatePetsMutationOptions = <
  TError = Error,
  TContext = unknown,
>(options?: {
  mutation?: SolidMutationOptions<
    Awaited<ReturnType<typeof createPets>>,
    TError,
    { data: CreatePetsBody; params: CreatePetsParams },
    TContext
  >;
  fetch?: RequestInit;
}): SolidMutationOptions<
  Awaited<ReturnType<typeof createPets>>,
  TError,
  { data: CreatePetsBody; params: CreatePetsParams },
  TContext
> => {
  const mutationKey = ['createPets'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createPets>>,
    { data: CreatePetsBody; params: CreatePetsParams }
  > = (props) => {
    const { data, params } = props ?? {};

    return createPets(data, params, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreatePetsMutationResult = NonNullable<
  Awaited<ReturnType<typeof createPets>>
>;
export type CreatePetsMutationBody = CreatePetsBody;
export type CreatePetsMutationError = Error;

/**
 * @summary Create a pet
 */
export const useCreatePets = <TError = Error, TContext = unknown>(
  options?: {
    mutation?: SolidMutationOptions<
      Awaited<ReturnType<typeof createPets>>,
      TError,
      { data: CreatePetsBody; params: CreatePetsParams },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createPets>>,
  TError,
  { data: CreatePetsBody; params: CreatePetsParams },
  TContext
> => {
  return useMutation(() => getCreatePetsMutationOptions(options), queryClient);
};
export const getShowPetByIdUrl = (petId: string) => {
  return `/pets/${petId}`;
};

/**
 * @summary Info for a specific pet
 */
export const showPetById = async (
  petId: string,
  options?: RequestInit,
): Promise<Pet> => {
  const res = await fetch(getShowPetByIdUrl(petId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: Pet = body ? JSON.parse(body) : {};
  return data;
};

export const getShowPetByIdQueryKey = (petId: string) => {
  return [`/pets/${petId}`] as const;
};

export const getShowPetByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof showPetById>>,
  TError = Error,
>(
  petId: string,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof showPetById>>,
          TError,
          TData
        >
      >,
      'initialData'
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = getShowPetByIdQueryKey(petId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof showPetById>>> = ({
    signal,
  }) => showPetById(petId, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: petId !== null && petId !== undefined,
    ...queryOptions,
  };
};

export type ShowPetByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof showPetById>>
>;
export type ShowPetByIdQueryError = Error;

export function useShowPetById<
  TData = Awaited<ReturnType<typeof showPetById>>,
  TError = Error,
>(
  petId: string,
  options: {
    query: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof showPetById>>,
          TError,
          TData
        >
      >,
      'initialData'
    > &
      Pick<
        ReturnType<
          DefinedInitialDataOptions<
            Awaited<ReturnType<typeof showPetById>>,
            TError,
            TData
          >
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useShowPetById<
  TData = Awaited<ReturnType<typeof showPetById>>,
  TError = Error,
>(
  petId: string,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof showPetById>>,
          TError,
          TData
        >
      >,
      'initialData'
    > &
      Pick<
        ReturnType<
          UndefinedInitialDataOptions<
            Awaited<ReturnType<typeof showPetById>>,
            TError,
            TData
          >
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useShowPetById<
  TData = Awaited<ReturnType<typeof showPetById>>,
  TError = Error,
>(
  petId: string,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof showPetById>>,
          TError,
          TData
        >
      >,
      'initialData'
    >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Info for a specific pet
 */

export function useShowPetById<
  TData = Awaited<ReturnType<typeof showPetById>>,
  TError = Error,
>(
  petId: string,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof showPetById>>,
          TError,
          TData
        >
      >,
      'initialData'
    >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getShowPetByIdQueryOptions(petId, options);

  const query = useQuery(
    () => getShowPetByIdQueryOptions(petId, options),
    queryClient,
  );

  return mergeProps(query, { queryKey: queryOptions.queryKey }) as any;
}

export const getDeletePetByIdUrl = (petId: string) => {
  return `/pets/${petId}`;
};

/**
 * @summary Deletes a specific pet
 */
export const deletePetById = async (
  petId: string,
  options?: RequestInit,
): Promise<void> => {
  const res = await fetch(getDeletePetByIdUrl(petId), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: void = body ? JSON.parse(body) : undefined;
  return data;
};

export const getDeletePetByIdMutationOptions = <
  TError = Error,
  TContext = unknown,
>(options?: {
  mutation?: SolidMutationOptions<
    Awaited<ReturnType<typeof deletePetById>>,
    TError,
    { petId: string },
    TContext
  >;
  fetch?: RequestInit;
}): SolidMutationOptions<
  Awaited<ReturnType<typeof deletePetById>>,
  TError,
  { petId: string },
  TContext
> => {
  const mutationKey = ['deletePetById'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deletePetById>>,
    { petId: string }
  > = (props) => {
    const { petId } = props ?? {};

    return deletePetById(petId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeletePetByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deletePetById>>
>;

export type DeletePetByIdMutationError = Error;

/**
 * @summary Deletes a specific pet
 */
export const useDeletePetById = <TError = Error, TContext = unknown>(
  options?: {
    mutation?: SolidMutationOptions<
      Awaited<ReturnType<typeof deletePetById>>,
      TError,
      { petId: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deletePetById>>,
  TError,
  { petId: string },
  TContext
> => {
  return useMutation(
    () => getDeletePetByIdMutationOptions(options),
    queryClient,
  );
};
export const getShowPetWithOwnerUrl = (petId: string) => {
  return `/pets/${petId}/owner`;
};

/**
 * @summary combinate nullable and $ref
 */
export const showPetWithOwner = async (
  petId: string,
  options?: RequestInit,
): Promise<PetWithTag> => {
  const res = await fetch(getShowPetWithOwnerUrl(petId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: PetWithTag = body ? JSON.parse(body) : {};
  return data;
};

export const getShowPetWithOwnerQueryKey = (petId: string) => {
  return [`/pets/${petId}/owner`] as const;
};

export const getShowPetWithOwnerQueryOptions = <
  TData = Awaited<ReturnType<typeof showPetWithOwner>>,
  TError = Error,
>(
  petId: string,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof showPetWithOwner>>,
          TError,
          TData
        >
      >,
      'initialData'
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = getShowPetWithOwnerQueryKey(petId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof showPetWithOwner>>
  > = ({ signal }) => showPetWithOwner(petId, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: petId !== null && petId !== undefined,
    ...queryOptions,
  };
};

export type ShowPetWithOwnerQueryResult = NonNullable<
  Awaited<ReturnType<typeof showPetWithOwner>>
>;
export type ShowPetWithOwnerQueryError = Error;

export function useShowPetWithOwner<
  TData = Awaited<ReturnType<typeof showPetWithOwner>>,
  TError = Error,
>(
  petId: string,
  options: {
    query: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof showPetWithOwner>>,
          TError,
          TData
        >
      >,
      'initialData'
    > &
      Pick<
        ReturnType<
          DefinedInitialDataOptions<
            Awaited<ReturnType<typeof showPetWithOwner>>,
            TError,
            TData
          >
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useShowPetWithOwner<
  TData = Awaited<ReturnType<typeof showPetWithOwner>>,
  TError = Error,
>(
  petId: string,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof showPetWithOwner>>,
          TError,
          TData
        >
      >,
      'initialData'
    > &
      Pick<
        ReturnType<
          UndefinedInitialDataOptions<
            Awaited<ReturnType<typeof showPetWithOwner>>,
            TError,
            TData
          >
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useShowPetWithOwner<
  TData = Awaited<ReturnType<typeof showPetWithOwner>>,
  TError = Error,
>(
  petId: string,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof showPetWithOwner>>,
          TError,
          TData
        >
      >,
      'initialData'
    >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary combinate nullable and $ref
 */

export function useShowPetWithOwner<
  TData = Awaited<ReturnType<typeof showPetWithOwner>>,
  TError = Error,
>(
  petId: string,
  options?: {
    query?: Omit<
      Partial<
        SolidQueryOptions<
          Awaited<ReturnType<typeof showPetWithOwner>>,
          TError,
          TData
        >
      >,
      'initialData'
    >;
    fetch?: RequestInit;
  },
  queryClient?: () => QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getShowPetWithOwnerQueryOptions(petId, options);

  const query = useQuery(
    () => getShowPetWithOwnerQueryOptions(petId, options),
    queryClient,
  );

  return mergeProps(query, { queryKey: queryOptions.queryKey }) as any;
}
